### ISSUE TITLE
Demo运行报错，java.lang.UnsupportedOperationException: Can't convert value at index 6 to color: type=0x1

### ISSUE THREAD

**Issue by hc1991** [Tencent/Shadow#1000]
2022-06-24 14:18:22.307 15467-15467/com.tencent.shadow.sample.host E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.shadow.sample.host:plugin, PID: 15467
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity}: java.lang.RuntimeException: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class com.jeremyfeinstein.slidingmenu.lib.SlidingMenu
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2896)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2974)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
     Caused by: java.lang.RuntimeException: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class com.jeremyfeinstein.slidingmenu.lib.SlidingMenu
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(ShadowActivityDelegate.kt:159)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7113)
        at android.app.Activity.performCreate(Activity.java:7104)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2849)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2974) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:192) 
        at android.app.ActivityThread.main(ActivityThread.java:6753) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825) 
     Caused by: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class com.jeremyfeinstein.slidingmenu.lib.SlidingMenu
     Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class com.jeremyfeinstein.slidingmenu.lib.SlidingMenu
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:656)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:835)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:775)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
        at com.tencent.shadow.core.runtime.ShadowActivity.setContentView(ShadowActivity.java:40)
        at com.tencent.shadow.sample.plugin.app.lib.gallery.MainActivity.onCreate(MainActivity.java:65)
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(ShadowActivityDelegate.kt:156)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7113)
        at android.app.Activity.performCreate(Activity.java:7104)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2849)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2974)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
2022-06-24 14:18:22.309 15467-15467/com.tencent.shadow.sample.host E/AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #52: Binary XML file line #52: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #52: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:656)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:835)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:775)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:908)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:869)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:911)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:869)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:521)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
        at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.setContent(SlidingMenu.java:353)
        at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:246)
        at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:197)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:656)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:835)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:775)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
        at com.tencent.shadow.core.runtime.ShadowActivity.setContentView(ShadowActivity.java:40)
        at com.tencent.shadow.sample.plugin.app.lib.gallery.MainActivity.onCreate(MainActivity.java:65)
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(ShadowActivityDelegate.kt:156)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7113)
        at android.app.Activity.performCreate(Activity.java:7104)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2849)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2974)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1675)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:192)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
     Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 6 to color: type=0x1
        at android.content.res.TypedArray.getColor(TypedArray.java:473)
        at android.widget.AbsListView.<init>(AbsListView.java:894)
        at android.widget.ListView.<init>(ListView.java:227)
        at android.widget.ExpandableListView.<init>(ExpandableListView.java:234)
        at android.widget.ExpandableListView.<init>(ExpandableListView.java:229)
        at android.widget.ExpandableListView.<init>(ExpandableListView.java:225)
        at com.ryg.expandable.ui.PinnedHeaderExpandableListView.<init>(PinnedHeaderExpandableListView.java:74)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:656) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:835) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:775) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:908) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:869) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:911) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:869) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:521) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
        at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.setContent(SlidingMenu.java:353) 
        at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:246) 
        at com.jeremyfeinstein.slidingmenu.lib.SlidingMenu.<init>(SlidingMenu.java:197)

**Comment by shifujun** [comment]
代码版本？改了什么？运行环境？运行命令？运行操作？

**Comment by hc1991** [comment]
> 代码版本？改了什么？运行环境？运行命令？运行操作？

环境：使用的模拟器，API27会有这个问题，大于API27都是正常的；
运行命令：AndroidStudio的运行按钮，运行Samp-Host 启动后 点击启动插件
代码版本：master分支，commitID：e7988d6d26d4804d598fc64e5e9e9c852edbb2d2
改什么：没有任何修改，clone下来的代码直接运行

**Comment by shifujun** [comment]
看起来可能是API 27以下对于资源ID分区的实现还是有bug。可能是那个getColor有问题，得再构造下测试用例看看。

不过肯定是要把使用MixResource方案的最高API提升到27了。

**Comment by hc1991** [comment]
> 看起来可能是API 27以下对于资源ID分区的实现还是有bug。可能是那个getColor有问题，得再构造下测试用例看看。
> 
> 不过肯定是要把使用MixResource方案的最高API提升到27了。

@shifujun 

Demo崩溃的问题解决了；
但是我尝试使用AndroidX中的AppCompatActivity，却遇到一个崩溃问题：
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:703)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
在插件Activity启动的时候无法读取到androidx.appcompat.R.styleable.AppCompatTheme主题中的androidx.appcompat.R.styleable.AppCompatTheme_windowActionBar属性，导致启动的时候Android系统认定主题没有使用AppCompat（实际上已经使用）

然后我在插件中使用如下代码测试：
![image](https://user-images.githubusercontent.com/17923307/175554830-d4ae24a6-6d00-42db-aa31-ab382f1a2f23.png)
打印的结果是false

然后我使用shadow工程中的demo进行了如下的测试：
1、在Host中增加了一个自定义属性，并在在主题中设置该属性。让Host的Application使用该主题
![image](https://user-images.githubusercontent.com/17923307/175559603-c98e11b1-2db4-4006-a2a6-2ab4990b11ac.png)
2、在Host的MainActivity中测试：
测试代码：
` String name = getResources().getResourceName(com.tencent.shadow.sample.host.lib.R.layout.host_ui_layer_layout);
        Resources.Theme t = getTheme();
        t.applyStyle(com.tencent.shadow.sample.host.lib.R.style.TestHostTheme, true);
        TypedArray ta = t.obtainStyledAttributes(com.tencent.shadow.sample.host.lib.R.styleable.DominoScroll);
        boolean re = ta.hasValue(com.tencent.shadow.sample.host.lib.R.styleable.DominoScroll_dominoContent);
        ta.recycle();
        Log.i("ttest", "host hasValue= " + re + ",name="+name);`
![image](https://user-images.githubusercontent.com/17923307/175559919-bc9b3629-29bb-4157-b07a-12a44041aad7.png)
能够获取到自定义的属性
3、在Plugin的MainActivity中测试：(这里将Host用到的主题和属性都移到了Host-lib中，使plugin能够正常访问)
测试代码：
` String name = getResources().getResourceName(com.tencent.shadow.sample.host.lib.R.layout.host_ui_layer_layout);
        Resources.Theme t = getTheme();
        t.applyStyle(com.tencent.shadow.sample.host.lib.R.style.TestHostTheme, true);
        TypedArray ta = t.obtainStyledAttributes(com.tencent.shadow.sample.host.lib.R.styleable.DominoScroll);
        boolean re = ta.hasValue(com.tencent.shadow.sample.host.lib.R.styleable.DominoScroll_dominoContent);

        ta.recycle();
        Log.i("ttest", "plugin hasValue= " + re + ",name=" +name);`
![image](https://user-images.githubusercontent.com/17923307/175560615-b6ba0828-2e21-4781-89e6-0f95c5125b0a.png)

经过上面三步测试，发现一个问题:
插件的拿到的Resource主题无法获取宿主中的属性，从而导致当启动androidX的AppCOmpatActivity‘时候无法获取’androidx.appcompat.R.styleable.AppCompatTheme_windowActionBar属性导致出现上述崩溃；
这个崩溃问题在API 31上没有出现，但是在API27上出现了
想问下是什么原因呢

**Comment by shifujun** [comment]
另外的问题应该在单独的issue里讨论。AppCompatActivity有自动化测试用例，可以在上面扩展测试场景复现问题，把代码push上来：

https://github.com/Tencent/Shadow/blob/10ce0228d9a0edde3d21f11fa3207eacae139450/projects/test/dynamic/host/test-dynamic-host/src/androidTest/java/com/tencent/shadow/test/cases/plugin_androidx/AppCompatActivityTest.java#L33

**Comment by shifujun** [comment]
https://cs.android.com/android/platform/superproject/+/android-8.0.0_r1:frameworks/base/core/java/android/widget/AbsListView.java;l=849-850

https://github.com/Tencent/Shadow/blob/08da57dd53ae76a002a1fa341b170fd469151e68/projects/sample/source/sample-plugin/sample-base-lib/src/main/res/layout/layout_main_above.xml#L46

报错的行看起来和`cacheColorHint`有关，删除`android:cacheColorHint="@null"`确实能避免这个错误。但是后续有其他错误：
```
 Caused by: android.content.res.Resources$NotFoundException: Drawable (missing name) with resource ID #0x7e000000
     Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7e000000
        at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:242)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:739)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:609)
        at android.content.res.Resources.loadDrawable(Resources.java:885)
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:953)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
        at android.widget.ExpandableListView.<init>(ExpandableListView.java:239)
        at android.widget.ExpandableListView.<init>(ExpandableListView.java:229)
        at android.widget.ExpandableListView.<init>(ExpandableListView.java:225)
        at com.ryg.expandable.ui.PinnedHeaderExpandableListView.<init>(PinnedHeaderExpandableListView.java:74)
```

**Comment by hc1991** [comment]
> 另外的问题应该在单独的issue里讨论。AppCompatActivity有自动化测试用例，可以在上面扩展测试场景复现问题，把代码push上来：

好的，自动化测试用例写的比较少。我从新提个issue
