### ISSUE TITLE
插件so加载问题

### ISSUE THREAD

**Issue by TestPlanB** [Tencent/Shadow#1001]
如果在插件中执行so的查找，会出现
----------------------
public class MainActivity extends Activity {
    static {
        System.loadLibrary("nativecpp");
    }
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
}

---------------
Process: com.tencent.shadow.sample.host:plugin, PID: 3438
                                                                                                    java.lang.UnsatisfiedLinkError: com.tencent.shadow.core.loader.classloaders.PluginClassLoader[DexPathList[[zip file "/data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/sample-manager/c6281a1e337cba6a78c4a4d3dbc2c0e8/plugin-debug.zip/plugin-app-plugin-debug.apk"],nativeLibraryDirectories=[/data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/sample-manager/lib/27CBA4E0-EE2F-4717-86AA-49CBEF5176F9_lib, /system/lib64, /system/system_ext/lib64]]] couldn't find "libnativecpp.so"
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1083)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1664)
                                                                                                    	at com.tencent.shadow.sample.plugin.MainActivity.<clinit>(MainActivity.java:8)
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at com.tencent.shadow.core.runtime.ShadowAppComponentFactory.instantiateActivity(ShadowAppComponentFactory.java:18)
                                                                                                    	at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(Unknown Source:239)
                                                                                                    	at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8129)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8113)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1359)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3727)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3912)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:257)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8215)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032)

----------
可以看到nativeLibraryDirectories找不到具体的so，但是在host上加载可以

**Comment by TestPlanB** [comment]
nativecpp 是一个demo so 随便编译一个即可配置文件如下
----------------------
apply plugin: 'com.android.application'
apply plugin: 'com.tencent.shadow.plugin'

android {
    compileSdkVersion 30
    defaultConfig {
        applicationId "com.tencent.shadow.sample.plugin"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters "arm64-v8a"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            signingConfig signingConfigs.create("release")
            signingConfig.initWith(buildTypes.debug.signingConfig)
        }
    }

    // 将插件applicationId设置为和宿主相同
    productFlavors {
        plugin {
            applicationId "com.tencent.shadow.sample.host"
        }
    }
    sourceSets {
        main {
            jniLibs.srcDir 'libs'
        }

    }
}

dependencies {
    //Shadow Transform后业务代码会有一部分实际引用runtime中的类
    //如果不以compileOnly方式依赖，会导致其他Transform或者Proguard找不到这些类
    pluginCompileOnly "com.tencent.shadow.core:runtime:$shadow_version"
}

//这段buildscript配置的dependencies是为了apply plugin: 'com.tencent.shadow.plugin'能找到实现
buildscript {
    repositories {
        if (!System.getenv().containsKey("DISABLE_TENCENT_MAVEN_MIRROR")) {
            maven { url 'https://mirrors.tencent.com/nexus/repository/maven-public/' }
        } else {
            google()
            jcenter()
        }
        maven {
            name = "GitHubPackages"
            url "https://maven.pkg.github.com/tencent/shadow"
            //一个只读账号兼容Github Packages暂时不支持匿名下载
            //https://github.community/t/download-from-github-package-registry-without-authentication/14407
            credentials {
                username = 'readonlypat'
                password = '\u0067hp_s3VOOZnLf1bTyvHWblPfaessrVYyEU4JdNbs'
            }
        }
        mavenLocal()
    }

    dependencies {
        classpath "com.tencent.shadow.core:gradle-plugin:$shadow_version"
    }
}

shadow {
    packagePlugin {
        pluginTypes {
            debug {
                loaderApkConfig = new Tuple2('sample-loader-debug.apk', ':sample-loader:assembleDebug')
                runtimeApkConfig = new Tuple2('sample-runtime-debug.apk', ':sample-runtime:assembleDebug')
                pluginApks {
                    pluginApk1 {
                        businessName = 'sample-plugin'//businessName相同的插件，context获取的Dir是相同的。businessName留空，表示和宿主相同业务，直接使用宿主的Dir。
                        partKey = 'sample-plugin'
                        buildTask = 'assemblePluginDebug'
                        apkName = 'plugin-app-plugin-debug.apk'
                        apkPath = 'plugin-app/build/outputs/apk/plugin/debug/plugin-app-plugin-debug.apk'
                    }
                }


            }

            release {
                loaderApkConfig = new Tuple2('sample-loader-release.apk', ':sample-loader:assembleRelease')
                runtimeApkConfig = new Tuple2('sample-runtime-release.apk', ':sample-runtime:assembleRelease')
                pluginApks {
                    pluginApk1 {
                        businessName = 'demo'
                        partKey = 'sample-plugin'
                        buildTask = 'assemblePluginRelease'
                        apkName = 'plugin-app-plugin-release.apk'
                        apkPath = 'plugin-app/build/outputs/apk/plugin/release/plugin-app-plugin-release.apk'
                    }
                }
            }
        }

        loaderApkProjectPath = 'sample-loader'

        runtimeApkProjectPath = 'sample-runtime'

        version = 4
        compactVersion = [1, 2, 3]
        uuidNickName = "1.1.5"
    }
}
