### ISSUE TITLE
尝试修改包名的问题

### ISSUE THREAD

**Issue by wlssing** [Tencent/Shadow#1019]
当我尝试修改包名
com.tencent.shadow.sample  改成com.xxx.yyy  将 tencent.shadow改成xxx  sample改成yyy
代码中变动也是这样  只改了一些常量  但并未修改其他的实现代码
但是并未能如愿  但是我还是不清楚怎么回事  希望得到您的指导  能安装 但是一点启动插件就崩溃 

2022-07-18 14:30:13.182 3022-3039/com.xxx.yyy.host E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/xxx/yyy/host/lib/LoadPluginCallback;
        at com.xxx.yyy.plugin.loader.SamplePluginLoader.loadPlugin(SamplePluginLoader.java:59)
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:86)
        at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:53)
        at android.os.Binder.execTransactInternal(Binder.java:1179)
        at android.os.Binder.execTransact(Binder.java:1143)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xxx.yyy.host.lib.LoadPluginCallback" on path: DexPathList[[zip file "/data/user/0/com.xxx.yyy.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/c3511cbb4098fcfc6a8b952f8a1c1d0a/plugin-debug.zip/base-runtime-debug.apk"],nativeLibraryDirectories=[/system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tencent.shadow.dynamic.apk.ApkClassLoader.loadClass(ApkClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.xxx.yyy.plugin.loader.SamplePluginLoader.loadPlugin(SamplePluginLoader.java:59) 
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:86) 
        at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:53) 
        at android.os.Binder.execTransactInternal(Binder.java:1179) 
        at android.os.Binder.execTransact(Binder.java:1143) 
    	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.xxx.yyy.host.lib.LoadPluginCallback" on path: DexPathList[[zip file "/data/user/0/com.xxx.yyy.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/c3511cbb4098fcfc6a8b952f8a1c1d0a/plugin-debug.zip/base-loader-debug.apk"],nativeLibraryDirectories=[/system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at com.tencent.shadow.dynamic.apk.ApkClassLoader.loadClass(ApkClassLoader.java:79)
        		... 6 more
    
    
    --------- beginning of crash
2022-07-18 14:30:13.184 3022-3039/com.xxx.yyy.host E/AndroidRuntime: FATAL EXCEPTION: Binder:3022_3
    Process: com.xxx.yyy.host:plugin, PID: 3022
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/xxx/yyy/host/lib/LoadPluginCallback;
        at com.xxx.yyy.plugin.loader.SamplePluginLoader.loadPlugin(SamplePluginLoader.java:59)
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:86)
        at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:53)
        at android.os.Binder.execTransactInternal(Binder.java:1179)
        at android.os.Binder.execTransact(Binder.java:1143)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xxx.yyy.host.lib.LoadPluginCallback" on path: DexPathList[[zip file "/data/user/0/com.xxx.yyy.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/c3511cbb4098fcfc6a8b952f8a1c1d0a/plugin-debug.zip/base-runtime-debug.apk"],nativeLibraryDirectories=[/system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tencent.shadow.dynamic.apk.ApkClassLoader.loadClass(ApkClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.xxx.yyy.plugin.loader.SamplePluginLoader.loadPlugin(SamplePluginLoader.java:59) 
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:86) 
        at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:53) 
        at android.os.Binder.execTransactInternal(Binder.java:1179) 
        at android.os.Binder.execTransact(Binder.java:1143) 
    	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.xxx.yyy.host.lib.LoadPluginCallback" on path: DexPathList[[zip file "/data/user/0/com.xxx.yyy.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/c3511cbb4098fcfc6a8b952f8a1c1d0a/plugin-debug.zip/base-loader-debug.apk"],nativeLibraryDirectories=[/system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at com.tencent.shadow.dynamic.apk.ApkClassLoader.loadClass(ApkClassLoader.java:79)
        		... 6 more
2022-07-18 14:30:13.199 3022-3039/? I/Process: Sending signal. PID: 3022 SIG: 9
2022-07-18 14:30:13.209 2848-2848/com.xxx.yyy.host I/com.tencent.shadow.dynamic.manager.BaseDynamicPluginManager: onServiceDisconnected
2022-07-18 14:30:13.212 2848-3005/com.xxx.yyy.host E/AndroidRuntime: FATAL EXCEPTION: pool-5-thread-1
    Process: com.xxx.yyy.host, PID: 2848
    java.lang.RuntimeException: android.os.DeadObjectException
        at com.xxx.yyy.manager.SamplePluginManager$1.run(SamplePluginManager.java:134)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:922)
     Caused by: android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:595)
        at com.tencent.shadow.dynamic.manager.BinderPluginLoader.loadPlugin(BinderPluginLoader.java:49)
        at com.xxx.yyy.manager.FastPluginManager.loadPlugin(FastPluginManager.java:138)
        at com.xxx.yyy.manager.SamplePluginManager$1.run(SamplePluginManager.java:119)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:922)

**Comment by wlssing** [comment]
就是各种白名单没添加
