### ISSUE TITLE
微信授权

### ISSUE THREAD

**Issue by wlssing** [Tencent/Shadow#1026]
```
2022-07-21 19:32:42.932 25635-25635/? E/Instrumentation: Uninitialized ActivityThread, likely app-created Instrumentation, disabling AppComponentFactory
    java.lang.Throwable
        at android.app.Instrumentation.getFactory(Instrumentation.java:1282)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1273)
        at com.tencent.mm.splash.l.newActivity(SourceFile:64)
        at com.tencent.mm.pluginguard.ActivityHookInstrumentation.newActivity(SourceFile:149)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3823)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4089)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2434)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.app.ActivityThread.main(ActivityThread.java:8344)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)

```

这种方式是不是不能使用 AppComponentFactory
我看原本框架中
```
class AppComponentFactoryTransform : SimpleRenameTransform(
    mapOf(
        "android.app.AppComponentFactory"
                to "com.tencent.shadow.core.runtime.ShadowAppComponentFactory"
    )
)
```
对AppComponentFactory进行了修改

**Comment by wlssing** [comment]
微信授权后  因为调不起了WXEntryActivity  所以获取不了微信的授权信息

**Comment by wlssing** [comment]
可以将WXEntryActivity放host中实现
