### ISSUE TITLE
multiDex打开之后出现PPS多实例异常

### ISSUE THREAD

**Issue by DiamondProx** [Tencent/Shadow#1031]
插件包太大，打开了multiDexEnabled=true后就报 PPS出现多实例

 Process: com.tencent.shadow.sample.host:plugin, PID: 14730
    java.lang.RuntimeException: Unable to create service com.tencent.shadow.sample.introduce_shadow_lib.MainPluginProcessService: java.lang.IllegalStateException: PPS出现多实例
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4233)
        at android.app.ActivityThread.access$200(ActivityThread.java:240)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2088)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:238)
        at android.app.ActivityThread.main(ActivityThread.java:7798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
     Caused by: java.lang.IllegalStateException: PPS出现多实例
        at com.tencent.shadow.dynamic.host.BasePluginProcessService.onCreate(BasePluginProcessService.java:32)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4221)
        at android.app.ActivityThread.access$200(ActivityThread.java:240) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2088) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:238) 
        at android.app.ActivityThread.main(ActivityThread.java:7798) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by DiamondProx** [comment]
@shifujun 哈喽，有空吗  ，帮忙瞧瞧呗
