### ISSUE TITLE
Shadow不支持IntentService

### ISSUE THREAD

**Issue by NicoToast** [Tencent/Shadow#105]
我就把TestService的继承由Service换成IntentService，执行TestStartServiceActivity中的startService，然后报类转换错误。
     Caused by: java.lang.ClassCastException: Cannot cast com.tencent.shadow.test.plugin.general_cases.lib.usecases.service.TestService to com.tencent.shadow.core.runtime.ShadowService
        at java.lang.Class.cast(Class.java:2441)
        at com.tencent.shadow.core.loader.managers.PluginServiceManager.newServiceInstance(PluginServiceManager.kt:230)
        at com.tencent.shadow.core.loader.managers.PluginServiceManager.createServiceAndCallOnCreate(PluginServiceManager.kt:216)
        at com.tencent.shadow.core.loader.managers.PluginServiceManager.startPluginService(PluginServiceManager.kt:74)
        at com.tencent.shadow.core.loader.managers.ComponentManager.startService(ComponentManager.kt:89)
        at com.tencent.shadow.core.runtime.ShadowContext.startService(ShadowContext.java:224)
        at com.tencent.shadow.test.plugin.general_cases.lib.usecases.service.TestStartServiceActivity.start(TestStartServiceActivity.java:64)

**Comment by shifujun** [comment]
这个很好支持的。只是因为这个IntentService是系统内置的类，我们不能修改它的字节码。

可以按照Service的处理方式针对这个IntentService做类似处理。把IntentService的代码拷贝出来实现成ShadowService就行了。

我最近业务需求很忙，你可以先自己试试写一下，真的很简单的。我有空了会加上实现的代码的。

**Comment by NicoToast** [comment]
明白了，我先试一下，感谢这么快的回复

**Comment by o0starshine0o** [comment]
这边写了个pr，支持IntentService
[链接](https://github.com/Tencent/Shadow/pull/363)
