### ISSUE TITLE
插件的notification 无法唤起

### ISSUE THREAD

**Issue by wlssing** [Tencent/Shadow#1056]
```
android.app.RemoteServiceException: Bad notification posted from package com.tencent.shadow.sample.host: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.tencent.shadow.sample.host id=0x7e060054) visible user=0 )
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1731)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6388)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:930)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
```
低版本 这里测试是7.0  崩溃   Android 12无任何反应    这种运行方式是插件的方式运行（sample-host）
独立运行（sample-host）是可以打开通知的

提交分了两次  

提交[第一次](https://github.com/wlssing/Shadow/commit/115d643fcfb564f61cfe95549c97422bd71e9b2c)  [第二次](https://github.com/wlssing/Shadow/commit/22da8acc42cd5106c1415b620b79ee7bdd575cfc) 第二次可要可不要

**Comment by wlssing** [comment]
https://github.com/Tencent/Shadow/issues/487#issue-820838333  同问题
