### ISSUE TITLE
java.lang.IllegalArgumentException: 无法绑定PPS

### ISSUE THREAD

**Issue by zhuqichao** [Tencent/Shadow#1063]
线上数据出现大量无法绑定PPS或者连接PPS超时错误引起的插件加载失败问题，本地无法复现，大佬能不能帮忙分析下可能的原因，说着有什么建议可以使本地复现出问题

**Comment by yexingyun** [comment]
我之前也同样遇到这种问题，后面再看好像没有了

**Comment by cyberau** [comment]
@zhuqichao 请问后来解决了吗？我把pps添加独立进程后，就一直绑定失败。

**Comment by fengkuangdadie** [comment]
我也遇到了这种报错；大佬们知道咋解决吗？
 E  FATAL EXCEPTION: pool-3-thread-1
                                                                                                    Process: com.example.demo, PID: 16820
                                                                                                    java.lang.RuntimeException: java.lang.IllegalArgumentException: 鏃犳硶缁戝畾PPS:com.tencent.shadow.sample.introduce_shadow_lib.MainPluginProcessService
                                                                                                    	at com.example.manager.MyPluginManager$1.run(MyPluginManager.java:120)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.IllegalArgumentException: 鏃犳硶缁戝畾PPS:com.tencent.shadow.sample.introduce_shadow_lib.MainPluginProcessService
                                                                                                    	at com.tencent.shadow.dynamic.manager.BaseDynamicPluginManager.bindPluginProcessService(BaseDynamicPluginManager.java:109)
                                                                                                    	at com.example.manager.MyPluginManager.loadPluginLoaderAndRuntime(MyPluginManager.java:249)
                                                                                                    	at com.example.manager.MyPluginManager.loadPlugin(MyPluginManager.java:257)
                                                                                                    	at com.example.manager.MyPluginManager.convertActivityIntent(MyPluginManager.java:243)
                                                                                                    	at com.example.manager.MyPluginManager.startPluginActivity(MyPluginManager.java:235)
                                                                                                    	at com.example.manager.MyPluginManager$1.run(MyPluginManager.java:118)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
