### ISSUE TITLE
编译最新git 代码，生成的依赖，集成报错

### ISSUE THREAD

**Issue by lao-Driver** [Tencent/Shadow#1071]
编译最新git 代码，生成的依赖，集成报错，用的java8版本，SDK和gradle版本跟git 一样，运行报错，请问这个是什么原因

2022-10-27 19:43:06.545 4067-4067/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hw.shadowplugin:plugin, PID: 4067
    java.lang.RuntimeException: partKey==sample-base className==androidx.startup.InitializationProvider authorities==com.hw.shadowplugin.androidx-startup
        at com.tencent.shadow.core.loader.managers.PluginContentProviderManager.createContentProviderAndCallOnCreate(PluginContentProviderManager.kt:110)
        at com.tencent.shadow.core.loader.ShadowPluginLoader.callApplicationOnCreate$realAction(ShadowPluginLoader.kt:121)
        at com.tencent.shadow.core.loader.ShadowPluginLoader.access$callApplicationOnCreate$realAction(ShadowPluginLoader.kt:43)
        at com.tencent.shadow.core.loader.ShadowPluginLoader$callApplicationOnCreate$1.run(ShadowPluginLoader.kt:132)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6190)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f0e001b
        at android.content.res.Resources.getText(Resources.java:335)
        at android.content.res.Resources.getString(Resources.java:381)
        at com.tencent.shadow.core.loader.blocs.MixResources$getString$1.invoke(CreateResourceBloc.kt:194)
        at com.tencent.shadow.core.loader.blocs.MixResources$getString$1.invoke(CreateResourceBloc.kt:194)
        at com.tencent.shadow.core.loader.blocs.MixResources.tryMainThenShared(CreateResourceBloc.kt:183)
        at com.tencent.shadow.core.loader.blocs.MixResources.getString(CreateResourceBloc.kt:194)
        at android.content.Context.getString(Context.java:476)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:183)
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
        at com.tencent.shadow.core.loader.managers.PluginContentProviderManager.createContentProviderAndCallOnCreate(PluginContentProviderManager.kt:107)
        at com.tencent.shadow.core.loader.ShadowPluginLoader.callApplicationOnCreate$realAction(ShadowPluginLoader.kt:121) 
        at com.tencent.shadow.core.loader.ShadowPluginLoader.access$callApplicationOnCreate$realAction(ShadowPluginLoader.kt:43) 
        at com.tencent.shadow.core.loader.ShadowPluginLoader$callApplicationOnCreate$1.run(ShadowPluginLoader.kt:132) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6190) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

**Comment by limingboGitHub** [comment]
宿主使用了startup库吧，加载插件的时候插件进程里找不到startup，要么不用startup库，要么尝试下插件也引入这个库
