### ISSUE TITLE
重复添加 ContentProvider

### ISSUE THREAD

**Issue by HeLiHuang** [Tencent/Shadow#1093]
022-11-09 08:47:11.921 29474-29620/com.gwm.app.dock.devices E/AndroidRuntime: FATAL EXCEPTION: pool-5-thread-1
    Process: com.gwm.app.dock.devices, PID: 29474
    java.lang.RuntimeException: java.lang.IllegalStateException: java.lang.RuntimeException: 重复添加 ContentProvider
        at com.gwm.app.dock.devices.manager.SamplePluginManager$2.run(SamplePluginManager.java:199)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException: java.lang.RuntimeException: 重复添加 ContentProvider
        at android.os.Parcel.createException(Parcel.java:1961)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at com.tencent.shadow.dynamic.manager.BinderPluginLoader.loadPlugin(BinderPluginLoader.java:50)
        at com.gwm.app.dock.devices.manager.FastPluginManager.loadPlugin(FastPluginManager.java:138)
        at com.gwm.app.dock.devices.manager.SamplePluginManager$2.run(SamplePluginManager.java:186)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 

如何解决，有遇到的吗？
我尝试把autherios改了，但是还是报这个错

**Comment by HeLiHuang** [comment]
一直卡这了

**Comment by aa5279aa** [comment]
修改插件项目中的manifest配置，然后彻底clear项目试下，我之前也遇到过类似过问题的。

**Comment by HeLiHuang** [comment]
看来你改过，你怎么改的配置？
我的配置就这些：
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"

    package="com.gwm.app.dock.devices.service">

    <uses-feature android:glEsVersion="0x00020000" />

    <application
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@android:style/Theme.NoTitleBar">
        <meta-data
            android:name="test_meta"
            android:value="test_value" />


        <service
            android:name="com.gwm.app.dock.devices.service.DeviceService"
            android:exported="true">
            <intent-filter>
                <action android:name="com.gwm.app.dock.remote" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </service>

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.general_cases.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths" />
        </provider>
    </application>

</manifest>
