### ISSUE TITLE
Demo加了moshi1.13.0后编译不过 javassist.NotFoundException

### ISSUE THREAD

**Issue by wt959790** [Tencent/Shadow#1102]
Demo插件里加了这几行代码
sample-app 
        gradle.build 
                apply plugin: 'kotlin-android'
                apply plugin: 'kotlin-kapt'
                api 'com.squareup.moshi:moshi:1.13.0'
                kapt 'com.squareup.moshi:moshi-kotlin-codegen:1.13.0'
rootProject
        gradle.properties
                android.jetifier.ignorelist=moshi-1.13.0
运行host
javassist.NotFoundException: com.squareup.moshi.RecordJsonAdapter$ComponentBinding
Caused by: javassist.NotFoundException: com.squareup.moshi.RecordJsonAdapter$ComponentBinding
	at javassist.ClassPool.get(ClassPool.java:430)
	at com.tencent.shadow.core.transform_kit.ReplaceClassName.checkAll(ReplaceClassName.kt:51)
	at com.tencent.shadow.core.transform_kit.AbstractTransform.checkReplacedClassHaveRightMethods(AbstractTransform.kt:147)
	at com.tencent.shadow.core.transform_kit.AbstractTransform.onCheckTransformedClasses(AbstractTransform.kt:110)
	at com.tencent.shadow.core.transform_kit.AbstractTransform.afterTransform(AbstractTransform.kt:76)
	at com.tencent.shadow.core.transform_kit.ClassTransform.transform(ClassTransform.kt:177)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:284)
	at com.android.build.gradle.internal.profile.NoOpAnalyticsService.recordBlock(NoOpAnalyticsService.kt:72)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:242)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	... 124 more

尝试ReplaceClassName.checkAll方法循环里 try...catch 然后各种dex报错...，大佬帮忙看看是啥原因导致的

**Comment by aa5279aa** [comment]
moshi加错了地方了吧，moshi不应该加入到运行时嘛，为什么编译时就用到了moshi的类？

**Comment by wt959790** [comment]
> 
退回1.12.0版本是可以的，只有这一个插件用moshi解析接口数据，codegen kapt生成jsonAdapter怎么加到运行时？
