### ISSUE TITLE
偶现插件安装失败

### ISSUE THREAD

**Issue by HeLiHuang** [Tencent/Shadow#1104]
11/17 10:00:26: Launching 'app' on QUALCOMM noch sa8155_v35_b16.
Install successfully finished in 1 s 967 ms.
$ adb shell am start -n "com.gwm.app.dock.devices/com.gwm.app.dock.devices.host.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 7738 on device 'qualcomm-noch_sa8155_v35_b16-1234567'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/pp.dock.device: The ClassLoaderContext is a special shared library.
D/GwmSkin: createAppContext=====com.gwm.app.dock.devices
I/GwmSkin: Inject GwmResourcesPlugin for com.gwm.app.dock.devices  this : android.content.res.GwmResourcesPlugin@ec16bcd
I/GwmSkin: create GwmPluginLoadUtils for com.gwm.app.dock.devices  mSkinService :: android.app.GwmSkinManager@4c18c82
I/GwmSkin: install skin packageName : com.gwm.app.dock.devices
D/GwmPrivacyManager: GwmPrivacyManager :: context(android.app.ContextImpl@dc49f93).
I/GwmSkin: install skinPath is empty!!!
D/GwmPrivacyManager: GwmPrivacyManager :: context(android.app.ContextImpl@285f7c9).
D/GwmSkin: createAppContext=====com.gwm.app.dock.devices
I/GwmSkin: Inject GwmResourcesPlugin for com.gwm.app.dock.devices  this : android.content.res.GwmResourcesPlugin@2ffeece
I/GwmSkin: onDestory this : android.content.res.GwmResourcesPlugin@ec16bcd
I/System.out: onCreate --------------------------> com.gwm.app.dock.devices.host.HostApplication@30fa1ef
D/GwmPrivacyManager: GwmPrivacyManager :: context(android.app.ContextImpl@a3e64e8).
D/GwmPrivacyManager: GwmPrivacyManager :: context(android.app.ContextImpl@2bfd701).
D/GwmPrivacyManager: GwmPrivacyManager :: context(android.app.ContextImpl@c83dfe7).
I/GwmSkin: Inject GwmResourcesPlugin for com.gwm.app.dock.devices  this : android.content.res.GwmResourcesPlugin@608e794
W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startForegroundService:1551 android.content.ContextWrapper.startForegroundService:669 com.gwm.app.dock.service.utils.ServiceUtil.startService:61 com.gwm.app.dock.service.utils.ServiceUtil.bindService:67 com.gwm.app.dock.service.pool.DockBinderPoolManager.bindService:127 
W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1625 android.content.ContextWrapper.bindService:698 com.gwm.app.dock.service.utils.ServiceUtil.bindService:72 com.gwm.app.dock.service.pool.DockBinderPoolManager.bindService:127 com.gwm.app.dock.service.DockDeviceController.init:57 
D/OpenGLRenderer: Skia GL Pipeline
I/GwmSkin: onSkinInstalled : com.gwm.app.dock.devices  pluginInfo==android.content.res.GwmPluginInfo@1f[ filePath=null, pkg=null ]
I/GwmSkin: com.gwm.app.dock.devices no need to refresh
D/SQLiteCursor: received count(*) from native_fill_window: 0
I/AdrenoGLES-0: QUALCOMM build                   : e8564cc, Icd7c2a0773
    Build Date                       : 01/25/21
    OpenGL ES Shader Compiler Version: EV031.30.02.00
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.AU.1.1.3.R1.08.00.00.802.002
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
I/AdrenoGLES-0: Build Config                     : S L 6.0.2 AArch64
I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/Adreno-GSL_RPC: <gsl_library_open:1589>:  library open -- refcount=1
I/Adreno-GSL_RPC: <gsl_rpc_connect:1211>: connecting using conn_id 0
I/uhab: habmm_socket_open: opened fd 67, refcnt 1, return 0, vcid 19100024
I/Adreno-GSL_RPC: <rpc_sockfd_create:685>: gsl_rpc_initialize: opening initial connection
I/Adreno-GSL_RPC: <rpc_handshake:1158>: client process name is com.gwm.app.dock.devices(devices)
I/Adreno-GSL_RPC: <rpc_handshake:1170>: client successfully connected to server, got connection id 10
I/uhab: habmm_socket_close: close fd 67, refcnt 0, vcid 19100024
I/Adreno-GSL_RPC: <gsl_rpc_connect:1211>: connecting using conn_id 10
I/uhab: habmm_socket_open: opened fd 64, refcnt 1, return 0, vcid 19100024
I/Adreno-GSL_RPC: <rpc_sockfd_create:695>: gsl_rpc_initialize: connecting from new thread
I/Adreno-GSL_RPC: <rpc_sub_handshake:1199>: thread successfully connected to server
I/Adreno-GSL_RPC: <gsl_rpc_initialize:1326>: using /data/misc/gpu/gsl_rpc_mempool.def file for mempool settings
I/AdrenoGLES-0: PFP: 0x00000000, ME: 0x00000000
W/Adreno-GSL_RPC: <gsl_dbq_create:2897>: HGSL:gsl_dbq_create failed, ret: -6
W/AdrenoUtils: <ReadGpuID_from_sysfs:198>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
W/AdrenoUtils: <ReadGpuID:222>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
I/Adreno-GSL_RPC: <gsl_library_open:1589>:  library open -- refcount=2
I/Adreno-GSL_RPC: <gsl_library_close:1645>:  library close -- refcount=1
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 1
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 1
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
W/Adreno-GSL_RPC: <gsl_dbq_create:2897>: HGSL:gsl_dbq_create failed, ret: -6
I/Adreno-GSL_RPC: <gsl_rpc_connect:1211>: connecting using conn_id 10
I/tag: DockBinderPoolManager$3.onServiceConnected(84): ....绑定服务成功..
I/uhab: habmm_socket_open: opened fd 64, refcnt 2, return 0, vcid 19100025
I/Adreno-GSL_RPC: <rpc_sockfd_create:695>: gsl_command_waittimestamp: connecting from new thread
I/Adreno-GSL_RPC: <rpc_sub_handshake:1199>: thread successfully connected to server
I/tag: DockCupAdapter$1.onTick(183): ...DockCountDownTimer计时器获取ICupBinder成功
I/tag: DockHumAdapter$1.onTick(164): ...DockCountDownTimer计时器获取IHumBinder成功
I/com.tencent.shadow.dynamic.host.DynamicPluginManager: enter fromId:1001 callback:null
I/com.tencent.shadow.dynamic.host.DynamicPluginManager: TextUtils.equals(mCurrentImplMd5, md5) : false
I/System.out: host  -----------------------> cup DockToHutCupMessageBean{deviceConn=0, switchStatus=0, workingMode=0, exceptionWarn=false, heatingCompleted=false, dryBurning=false, curTempVal=0, waterQualityStatus=0, tempSetVal=0, energyAlarm=false, registerStatus=0}
I/System.out: host  -----------------------> hum DockToHutHumMessageBean{deviceConn=0, switchStatus=0, gear=0, waterLack=false, exceptionWarn=false, curHumVal=100, humSetVal=0, autoSwitchStatus=false, sterilizeStatus=0, energyAlarm=false, registerStatus=0}
I/com.tencent.shadow.dynamic.host.DynamicPluginManager: enter fromId:1002 callback:com.gwm.app.dock.devices.host.MainActivity$3@68f4ba7
I/com.tencent.shadow.dynamic.host.DynamicPluginManager: TextUtils.equals(mCurrentImplMd5, md5) : false
I/pp.dock.device: The ClassLoaderContext is a special shared library.
W/pp.dock.device: Failed to stat, will retry: /data/user/0/com.gwm.app.dock.devices/files/pluginmanager.apk.arm64.flock: No such file or directory
W/pp.dock.device: Unsupported class loader
I/pp.dock.device: The ClassLoaderContext is a special shared library.
W/pp.dock.device: Failed to stat, will retry: /data/user/0/com.gwm.app.dock.devices/files/pluginmanager.apk.arm64.flock: No such file or directory
W/pp.dock.device: Skipping duplicate class check due to unsupported classloader
W/pp.dock.device: Unsupported class loader
W/pp.dock.device: Skipping duplicate class check due to unsupported classloader
I/com.tencent.shadow.dynamic.manager.BaseDynamicPluginManager: onCreate bundle:null
I/com.tencent.shadow.dynamic.manager.BaseDynamicPluginManager: onCreate bundle:null
E/com.tencent.shadow.core.manager.BasePluginManager: extractSo exception:
    com.tencent.shadow.core.manager.installplugin.InstallPluginException: 读取apk失败，apkFile==/data/user/0/com.gwm.app.dock.devices/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/ffbab788dbed0b7740e47926d639ea74/cup-plugin-app.zip/app-plugin-release-unsigned.apk
        at com.tencent.shadow.core.manager.BasePluginManager.getPluginPreferredAbi(BasePluginManager.java:440)
        at com.tencent.shadow.core.manager.BasePluginManager.extractSo(BasePluginManager.java:244)
        at com.gwm.app.dock.devices.manager.FastPluginManager.lambda$installPlugin$0$com-gwm-app-dock-devices-manager-FastPluginManager(FastPluginManager.java:88)
        at com.gwm.app.dock.devices.manager.FastPluginManager$$ExternalSyntheticLambda0.call(Unknown Source:8)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:238)
        at java.util.zip.ZipFile.<init>(ZipFile.java:152)
        at java.util.zip.ZipFile.<init>(ZipFile.java:166)
        at com.tencent.shadow.core.manager.installplugin.SafeZipFile.<init>(SafeZipFile.java:33)
        at com.tencent.shadow.core.manager.BasePluginManager.getPluginPreferredAbi(BasePluginManager.java:418)
        at com.tencent.shadow.core.manager.BasePluginManager.extractSo(BasePluginManager.java:244) 
        at com.gwm.app.dock.devices.manager.FastPluginManager.lambda$installPlugin$0$com-gwm-app-dock-devices-manager-FastPluginManager(FastPluginManager.java:88) 
        at com.gwm.app.dock.devices.manager.FastPluginManager$$ExternalSyntheticLambda0.call(Unknown Source:8) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
    
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
    Process: com.gwm.app.dock.devices, PID: 7738
    java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.tencent.shadow.core.manager.installplugin.InstallPluginException: 读取apk失败，apkFile==/data/user/0/com.gwm.app.dock.devices/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/ffbab788dbed0b7740e47926d639ea74/cup-plugin-app.zip/app-plugin-release-unsigned.apk
        at com.gwm.app.dock.devices.manager.SamplePluginManager$1.run(SamplePluginManager.java:157)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.util.concurrent.ExecutionException: com.tencent.shadow.core.manager.installplugin.InstallPluginException: 读取apk失败，apkFile==/data/user/0/com.gwm.app.dock.devices/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/ffbab788dbed0b7740e47926d639ea74/cup-plugin-app.zip/app-plugin-release-unsigned.apk
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.gwm.app.dock.devices.manager.FastPluginManager.installPlugin(FastPluginManager.java:104)
        at com.gwm.app.dock.devices.manager.SamplePluginManager$1.run(SamplePluginManager.java:138)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: com.tencent.shadow.core.manager.installplugin.InstallPluginException: 读取apk失败，apkFile==/data/user/0/com.gwm.app.dock.devices/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/ffbab788dbed0b7740e47926d639ea74/cup-plugin-app.zip/app-plugin-release-unsigned.apk
        at com.tencent.shadow.core.manager.BasePluginManager.getPluginPreferredAbi(BasePluginManager.java:440)
        at com.tencent.shadow.core.manager.BasePluginManager.extractSo(BasePluginManager.java:244)
        at com.gwm.app.dock.devices.manager.FastPluginManager.lambda$installPlugin$0$com-gwm-app-dock-devices-manager-FastPluginManager(FastPluginManager.java:88)
        at com.gwm.app.dock.devices.manager.FastPluginManager$$ExternalSyntheticLambda0.call(Unknown Source:8)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:238)
        at java.util.zip.ZipFile.<init>(ZipFile.java:152)
        at java.util.zip.ZipFile.<init>(ZipFile.java:166)
        at com.tencent.shadow.core.manager.installplugin.SafeZipFile.<init>(SafeZipFile.java:33)
        at com.tencent.shadow.core.manager.BasePluginManager.getPluginPreferredAbi(BasePluginManager.java:418)
        at com.tencent.shadow.core.manager.BasePluginManager.extractSo(BasePluginManager.java:244) 
        at com.gwm.app.dock.devices.manager.FastPluginManager.lambda$installPlugin$0$com-gwm-app-dock-devices-manager-FastPluginManager(FastPluginManager.java:88) 
        at com.gwm.app.dock.devices.manager.FastPluginManager$$ExternalSyntheticLambda0.call(Unknown Source:8) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
I/Process: Sending signal. PID: 7738 SIG: 9

**Comment by wangtaoxingxuan** [comment]
我这也遇见了类似的问题，请问该怎么解决呢？

**Comment by pippocao** [comment]
请问这个有解决办法了么？

**Comment by s-charvin** [comment]
怀疑是样本代码中 preparePlugin 异步进行，但插件加载在文件复制完成之前就开始尝试访问文件导致的。
