### ISSUE TITLE
如何把宿主的Context或Activity传给插件？

### ISSUE THREAD

**Issue by SunshineRoc** [Tencent/Shadow#1116]
有个需求，需要在不启动插件Activity的情况下，在宿主中打开插件的Dialog，因此需要把宿主的Context转换为插件的Activity。为探究实现的可行性，我在Shadow源码的HostAddPluginViewService类中，添加了以下代码：
`public class HostAddPluginViewService extends IntentService {

    private final String TAG = HostAddPluginViewService.class.getSimpleName();
    private final Handler uiHandler = new Handler(Looper.getMainLooper());

    public HostAddPluginViewService() {
        super("HostAddPluginViewService");
    }

    @Override
    protected void onHandleIntent(@Nullable Intent intent) {

        int id = intent.getIntExtra("id", 0);
        HostAddPluginViewContainer viewContainer
                = HostAddPluginViewContainerHolder.instances.remove(id);

        Log.v(TAG, "onHandleIntent()，加载插件View，进程ID=" + android.os.Process.myPid());

        // 新增的代码，测试把宿主Context转换为插件Activity的可行性
        Activity activity = (Activity) getBaseContext();

        uiHandler.post(() -> {
            View view = LayoutInflater.from(this).inflate(
                    R.layout.layout_host_add_plugin_view, null, false);
            viewContainer.addView(view);
        });
    }
}`

结果运行时报错，日志如下：

`com.tencent.shadow.sample.host E/AndroidRuntime: FATAL EXCEPTION: IntentService[HostAddPluginViewService]
    Process: com.tencent.shadow.sample.host:plugin, PID: 11502
    java.lang.ClassCastException: com.tencent.shadow.sample.host.HostApplication cannot be cast to com.tencent.shadow.core.runtime.ShadowActivity
        at com.tencent.shadow.sample.plugin.app.lib.usecases.service.HostAddPluginViewService.onHandleIntent(HostAddPluginViewService.java:36)
        at com.tencent.shadow.core.runtime.ShadowIntentService$ServiceHandler.handleMessage(ShadowIntentService.java:26)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by SunshineRoc** [comment]
上述例子中，
Activity activity = (Activity) getBaseContext() 
这行代码会导致下面的异常：
java.lang.ClassCastException: com.tencent.shadow.sample.host.HostApplication cannot be cast to com.tencent.shadow.core.runtime.ShadowActivity

**Comment by SunshineRoc** [comment]
收到，感谢回复与指点。

**Comment by SunshineRoc** [comment]
你好，非常感谢之前的指导，有个问题还想麻烦一下你，请问如何在插件里面使用宿主的Activity？有个需求，需要在插件里面使用宿主的Activity，我在[[84ab073](https://github.com/shifujun/Shadow/commit/84ab07311b5dec1f236ea89a605e9e53bd1587c8)]里面的ShowDialogService类中进行了模拟，代码如下：

    @Override
    protected void onHandleIntent(@Nullable Intent intent) {
        uiHandler.post(() -> {
            // 修改的代码，用于获取宿主的Activity
            Activity mainActivityInHost = (Activity) ObjectHolder.map.remove("MainActivity.this");

            AlertDialog.Builder builder = new AlertDialog.Builder(mainActivityInHost);
            builder.setMessage("show from ShowDialogService");
            AlertDialog alertDialog = builder.create();
            alertDialog.show();
        });
    }

结果运行报错，日志如下：
java.lang.ClassCastException: com.tencent.shadow.sample.host.MainActivity cannot be cast to com.tencent.shadow.core.runtime.ShadowActivity
        at com.tencent.shadow.sample.plugin.app.lib.usecases.service.ShowDialogService.lambda$onHandleIntent$0$com-tencent-shadow-sample-plugin-app-lib-usecases-service-ShowDialogService(ShowDialogService.java:27)
        at com.tencent.shadow.sample.plugin.app.lib.usecases.service.ShowDialogService$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:533)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)

**Comment by shifujun** [comment]
插件中没有Activity类型了。你换成自定义接口就好了。

**Comment by SunshineRoc** [comment]
能否以这个代码为例，介绍一下具体方法？万分感谢！

**Comment by shifujun** [comment]
你都没有具体的问题，我能介绍什么具体的方法呢？把宿主的Activity对象强制类型转换成插件Activity类型是你的目的吗？你肯定有其他的目的才对。你那个代码中Builder明明只需要Context类型，你非要强转一个Activity干什么呢？所以你的例子没有表达出你的目的。

而且你到底看没看代码，为什么MainActivity cannot be cast to ShadowActivity？如果这你都还回答不了，建议不要急于使用shadow。这不是一个可以拿来就用的免费服务，而是一个开源的技术交流项目。
