### ISSUE TITLE
PluginManagerThatSupportMultiLoader报错Didn't find class "android.content.ContextParams"

### ISSUE THREAD

**Issue by DiamondProx** [Tencent/Shadow#1118]
有两个单独的plugin1.zip  plugin2.zip   ,通过PluginManagerThatSupportMultiLoader用同一个进程加载。
流程1：先打开plugin1.zip，再打开plugin2.zip ，没问题
流程2：如果是先打开plugin2.zip，后打开plugin1.zip，就会报错

报错信息如下，这个问题应该如何排查？应该不是PluginManagerThatSupportMultiLoader用的有问题吧？不然流程1应该也会报错的吧
这是不是个BUG @shifujun 

11-30 06:47:29.742 18303 18303 E AndroidRuntime: java.lang.LinkageError: While checking class com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity method android.content.Context com.tencent.shadow.core.runtime.container.GeneratedHostActivityDelegator.createContext(android.content.ContextParams) signature against interface com.tencent.shadow.core.runtime.container.GeneratedHostActivityDelegator: Failed to resolve arg 0 type android.content.ContextParams with com.tencent.shadow.dynamic.host.MultiDynamicContainer$ContainerClassLoader (declaration of 'com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity' appears in /data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/817abc99b50019e57e0251301dbfdb05/plugin-debug.zip/sample-runtime-debug.apk)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3399)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3643)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2229)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:238)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7798)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/content/ContextParams;
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	... 15 more
**11-30 06:47:29.742 18303 18303 E AndroidRuntime: **Caused by: java.lang.ClassNotFoundException: Didn't find class "android.content.ContextParams"** on path: DexPathList[[zip file** "/data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/af1f71a4ccfdf01abec1c34b9d0784f6/plugin.zip/core-runtime-release.apk"],nativeLibraryDirectories=[/system/lib64, /system/product/lib64]]
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-30 06:47:29.742 18303 18303 E AndroidRuntime: 	... 15 more

**Comment by shifujun** [comment]
先单看找不到`android.content.ContextParams`的异常。这个类是API 31的新增类，正常来说在低版本系统上是不会调用涉及这个类的方法的，所以不应该会去查找它。如果你复现问题的设备是低于API 31的，那就应该先去看是什么代码在查找这个类，它的查找行为是不正常的。

其余情况可能是SDK的bug，但你不能在sample中复现的话，我也没法debug。至于和PluginManagerThatSupportMultiLoader是否相关，如果你看过它的代码，应该也不会判断太大的相关性吧。但没有代码都是乱猜。

**Comment by DiamondProx** [comment]
@shifujun 你好
我fork了工程
https://github.com/DiamondProx/Shadow
把调试代码提交了
https://github.com/DiamondProx/Shadow/commit/a0cf7c6f124fc0d317c472bb5d5f9b70a1db121f

我想大概是plugin1的runtime里面定义了两个插件的ProxyActivity，而plugin2只定义了一个，所以先打开plugin1没问题，但是这样配置应该也是不对的把，正确的配置应该是怎么样子的？

**Comment by DiamondProx** [comment]
谢谢 没问题了
