### ISSUE TITLE
穿山甲SDK作为一个插件时Activity转化异常，SDK有个方法void showSplashCradView(ViewGroup v, Activity a);)  此时我将宿主中的Activity传进去时出现异常

### ISSUE THREAD

**Issue by DaJiang666** [Tencent/Shadow#1129]
目前 业务现状，开屏时需要开屏广告，需要加载有穿山甲，广点通，快手 ，小米 ，华为， VIVO等广告SDK 。
在开屏时广告SDK作为一种插件， 譬如小米手机不需要华为的广告SDK。
由于原有业务逻辑相对复杂， 打开广告SplashADActivity时，回去调用各个广告的SDK。 此时SplashADActivity 存在于宿主中，并且是宿主的进程。  目前涉及的插件的加载也是宿主进程。
在打开一个开屏广告时， CSJSplashAd  的 void showSplashCardView(ViewGroup var1, Activity var2); 方法。
当传递的对象是宿主的Activity 譬如（SplashADActivity  HomeActivity  extends FragmentActivity） 在于接口通信时， 插件中各种接口的的参数包含（Activity activity）时都会默认转化成ShadowActivity  此时出现转化异常。 这个问题，就是把参数（Activity activity）类型的改成FragmentActivity  或者 公司内部的BaseActivity时， 此时可以解决这个问题。

public final static Map<String, Activity> sCsjHomeActivityMap = new HashMap<>();
Activity activity = CsjADHostAndPluginBridge.sCsjHomeActivityMap.get(CsjADHostAndPluginBridge.sBKHomeActivity);
上面代码出现异常， 此时Activity会被转化成ShadowActivity  

public final static Map<String, FragmentActivity> sCsjHomeActivityMap = new HashMap<>();
FragmentActivity activity = CsjADHostAndPluginBridge.sCsjHomeActivityMap.get(CsjADHostAndPluginBridge.sBKHomeActivity);
上面代码正常

观察到编译时
`class ActivityTransform : SimpleRenameTransform(
    mapOf(
        "android.app.Activity"
                to "com.tencent.shadow.core.runtime.ShadowActivity",
        "android.app.NativeActivity"
                to "com.tencent.shadow.core.runtime.ShadowNativeActivity"
    )
)`
插件中自己编写的  目前通过加白名单并且  把Activity改成FragmentActivty的方式得到解决。

重要重要重要：
重要重要重要：
但是目前使用了第三方的SDK中参数出现了（Activity  activity）类型的参数。 由于目前无法改变三方SDK的Activity类型， 遇到这种问题不能解决。 CSJSplashAd  的 void showSplashCardView(ViewGroup var1, Activity var2);

Back traces starts.
2022-12-13 02:47:30.070 16233-16233/com.xxxxxxxxx E/DEBUG: java.lang.VerifyError: Verifier rejected class com.xxxxxxxcsj.CsjSplashCardManager: void com.xxxxxxx.csj.CsjSplashCardManager.notifySplashViewShow(android.view.ViewGroup, androidx.fragment.app.FragmentActivity) failed to verify: void com.xxxxxxx.csj.CsjSplashCardManager.notifySplashViewShow(android.view.ViewGroup, androidx.fragment.app.FragmentActivity): [0xA] register v3 has type Reference: androidx.fragment.app.FragmentActivity but expected Reference: com.tencent.shadow.core.runtime.ShadowActivity (declaration of 'com.xxxxx.csj.CsjSplashCardManager' appears in /data/user/0/xxxxxxx/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/13e9bde70c6341acdb4cd4a8a502f90f/plugin-debug.zip/sample-app-plugin-debug.apk!classes2.dex)
2022-12-13 02:47:30.070 16233-16233/xxxxxxx E/DEBUG:     at com.xxxxxxx.csj.CsjSplashCardManager.getInstance(CsjSplashCardManager.java:51)
2022-12-13 02:47:30.070 16233-16233/xxxxxxx E/DEBUG:     at com.xxxxxxx.plugin.CsjBKDialogManager.showSplashCardDialogPlugin(CsjBKDialogManager.java:26)
2022-12-13 02:47:30.070 16233-16233xxxxxxx E/DEBUG:     at com.xxxxxxx.common.external.BKDialogManager.showSplashCardDialog(BKDialogManager.java:904)
2022-12-13 02:47:30.070 16233-16233/com.bikann.dzsk E/DEBUG:     at com.xxxxxxx.common.external.BKDialogManager.processEvent(BKDialogManager.java:424)

这种问题，作者有什么好的解决方案么， 或者建议

**Comment by jay-lan** [comment]
可以在插件中创建一个用于展示广告的Activity
