### ISSUE TITLE
Android4.4系统兼容性问题

### ISSUE THREAD

**Issue by zhuqichao** [Tencent/Shadow#1138]
经测试发现：
如果宿主activity继承自AppCompatActivity，插件activity也继承自AppCompatActivity
则：从宿主跳转至插件时会有如下异常：
Caused by: java.lang.ClassCastException: androidx.lifecycle.ReportFragment cannot be cast to androidx.lifecycle.ReportFragment
                                                                                                    	at androidx.lifecycle.ReportFragment.get(ReportFragment.java:74)
                                                                                                    	at androidx.lifecycle.ProcessLifecycleOwner$3.onActivityCreated(ProcessLifecycleOwner.java:193)
                                                                                                    	at com.tencent.shadow.core.runtime.ShadowActivityLifecycleCallbacks$Wrapper.onActivityCreated(ShadowActivityLifecycleCallbacks.java:120)
                                                                                                    	at android.app.Application.dispatchActivityCreated(Application.java:189)
                                                                                                    	at android.app.Activity.onCreate(Activity.java:905)
                                                                                                    	at com.tencent.shadow.core.runtime.container.GeneratedPluginContainerActivity.superOnCreate(GeneratedPluginContainerActivity.java:1463)
使用官方sample也可复现此问题，问题比较紧急，还请大佬帮忙分析下
将AppCompatTestActivity改为继承自AppCompatActivity，然后测试插件test-plugin-androidx-cases即可复现问题

**Comment by shifujun** [comment]
同#732
