### ISSUE TITLE
demo的sample-host强退

### ISSUE THREAD

**Issue by guohaichang** [Tencent/Shadow#114]
直接运行sample-host项目强退，，，红米note3 MIUI 10.2稳定版启动插件直接闪，锤子坚果pro启动插件闪回到宿主页面。

09-07 14:50:37.442 4081-4165/com.tencent.shadow.sample.host E/com.tencent.shadow.dynamic.manager.PluginManagerThatUseDynamicLoader: getPlugin exception:
    java.lang.NullPointerException: Attempt to read from field 'java.io.File com.tencent.shadow.core.manager.installplugin.InstalledPlugin$Part.pluginFile' on a null object reference
        at com.tencent.shadow.dynamic.manager.PluginManagerThatUseDynamicLoader.getPlugin(PluginManagerThatUseDynamicLoader.java:276)
        at com.tencent.shadow.dynamic.manager.UuidManagerBinder.onTransact(UuidManagerBinder.java:50)
        at android.os.Binder.execTransact(Binder.java:457)
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:510)
        at com.tencent.shadow.dynamic.manager.BinderPluginLoader.loadPlugin(BinderPluginLoader.java:46)
        at com.tencent.shadow.sample.manager.FastPluginManager.loadPlugin(FastPluginManager.java:141)
        at com.tencent.shadow.sample.manager.FastPluginManager.convertActivityIntent(FastPluginManager.java:119)
        at com.tencent.shadow.sample.manager.FastPluginManager.startPluginActivity(FastPluginManager.java:111)
        at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:116)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
09-07 14:50:37.461 4081-4165/com.tencent.shadow.sample.host E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.tencent.shadow.sample.host, PID: 4081
    java.lang.RuntimeException: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.app.lib.gallery.splash.SplashActivity}; have you declared this activity in your AndroidManifest.xml?
        at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:118)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.app.lib.gallery.splash.SplashActivity}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1801)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
        at android.app.Activity.startActivityForResult(Activity.java:4028)
        at android.app.Activity.startActivityForResult(Activity.java:3989)
        at android.app.Activity.startActivity(Activity.java:4312)
        at android.app.Activity.startActivity(Activity.java:4280)
        at com.tencent.shadow.sample.manager.FastPluginManager.startPluginActivity(FastPluginManager.java:115)
        at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:116)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818)

**Comment by chenjinguang** [comment]
我也遇到这个问题了，还记得怎么解决的吗
