### ISSUE TITLE
集成最新的shadow版本宿主加载插件找不so问题， java.lang.UnsatisfiedLinkError 。 有提供demo，求帮忙看下。

### ISSUE THREAD

**Issue by lilidejing** [Tencent/Shadow#1146]
复现demo：[shadow_plugin_so_test](https://github.com/lilidejing/shadow_plugin_so_test/tree/master)

背景：
       公司项目网络请求需要接入微信网关相关sdk，该sdk都是so文件。插件项目接入该so，用宿主去加载插件，会出现加载so失败的报错。
现象：
     1，用集成老shadow版本的宿主，manager也是老的（2.1.0版本），加载集成微信网关so的插件，加载启动插件是正常的。
     2，用集成新shadow版本的宿主,  manager是当前最新的（当前GitHub上该项目的master分支），加载集成微信网关so的插件，加载启动插件会报错。
      3，插件代码 plugin-project  编译成独立运行的apk，运行加载so没问题。 打包成插件，然后通过宿主APP去加载启动，加载so会有问题，报错如下：
` Process: com.tencent.shadow.sample.host:plugin, PID: 32149
    java.lang.UnsatisfiedLinkError: com.tencent.shadow.core.loader.classloaders.PluginClassLoader[DexPathList[[zip file "/data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/sample-manager/271d12440351a09d7f997b4f8462a29c/plugin-debug.zip/plugin-app-plugin-iwirst-debug.apk"],nativeLibraryDirectories=[/system/lib64]]] couldn't find "libtquic.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.tencent.protocol.PrivateLink.<clinit>(PrivateLink.java:15)
        at com.tencent.protocol.PrivateLink.getPrivateLink(PrivateLink.java:70)
        at com.tencent.shadow.sample.plugin.MainActivity.onCreate(MainActivity.java:30)
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(ShadowActivityDelegate.kt:156)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2928)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3083)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6713)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
`
demo中就是插件项目基础微信网关sdk，然后宿主去启动插件，会出现找不到so问题。麻烦帮忙看下什么原因，非常感谢！

**Comment by lilidejing** [comment]
但是看com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/sample-manager/lib/880A875A-F0FC-4011-8F8A-39507F9D4B75_lib 目录下是有so文件。

![IMG20230301162240](https://user-images.githubusercontent.com/9944119/222083936-d244a25a-bb30-4256-aac3-32d130381f9e.png)

**Comment by shifujun** [comment]
你最好fork一下项目，给sample加上so。这样我能比较快的看到你改了什么。我手边没电脑，要跑你的demo要等有电脑的时候了。即便有电脑，跑起来你的demo也要花很多时间看你的demo是怎么写的。这不如基于我对项目自身sample的了解，能对你的修改快速理解。

**Comment by lilidejing** [comment]
> 你最好fork一下项目，给sample加上so。这样我能比较快的看到你改了什么。我手边没电脑，要跑你的demo要等有电脑的时候了。即便有电脑，跑起来你的demo也要花很多时间看你的demo是怎么写的。这不如基于我对项目自身sample的了解，能对你的修改快速理解。

非常感谢！已fork。这个是我fork项目后更改的版本：[shadow_fork](https://github.com/lilidejing/Shadow/tree/liguojing_so_test)
麻烦再帮忙看下

**Comment by shifujun** [comment]
这个是我fork项目后更改的版本：[shadow_fork](https://github.com/lilidejing/Shadow/tree/liguojing_so_test)
> 
> 麻烦再帮忙看下

你这不是fork的呀，就一个commit。

**Comment by lilidejing** [comment]
> 这个是我fork项目后更改的版本：[shadow_fork](https://github.com/lilidejing/Shadow/tree/liguojing_so_test)
> 
> > 麻烦再帮忙看下
> 
> 你这不是fork的呀，就一个commit。

不好意思，以下是fork pull request地址：[1147](https://github.com/Tencent/Shadow/pull/1147)

**Comment by shifujun** [comment]
[`onInstallCompleted(pluginConfig,null);`](https://github.com/Tencent/Shadow/compare/master...lilidejing:Shadow:liguojing_so_test#diff-71b27340b33482e7027b5c6c26d59d469264c6b5b9431f4bb80e68dc13579984R92)

这个diff一看不就很明显吗？你给`soDirMap`传了个`null`，所以肯定没有任何so被写到数据库了。

你完全不能理解为什么两个sample中都演示了怎么传这个参数，你还能随意传个`null`。不能正常工作的时候，也不会回来看看这里随意填写的参数是否有问题？

这个你blame一下就能看到：
https://github.com/Tencent/Shadow/commit/b4dc172792a2608fbcc3446ff3e1e6b14b010ddb#diff-df4de663ef243b5642a0caa7732819ccdc594e1e3f56107acc6fe9862356ab0cR111

**Comment by lilidejing** [comment]
> 这个你blame一下就能看到： [b4dc172#diff-df4de663ef243b5642a0caa7732819ccdc594e1e3f56107acc6fe9862356ab0cR111](https://github.com/Tencent/Shadow/commit/b4dc172792a2608fbcc3446ff3e1e6b14b010ddb#diff-df4de663ef243b5642a0caa7732819ccdc594e1e3f56107acc6fe9862356ab0cR111)
知道了，谢谢！
