### ISSUE TITLE
一些第三方库将自己的核心类隐藏起来后shadow无法进行transform导致运行异常

### ISSUE THREAD

**Issue by richardwrq** [Tencent/Shadow#1148]
背景：
在APP接入AppsFlyer 6.3.2版本后，启动发现有运行异常，关键堆栈如下：

```
No field valueOf of type Landroid/app/Application; in class Lcom/appsflyer/internal/g; or its superclasses (declaration of 'com.appsflyer.internal.g' appears in /data/user/0/com.xrshBbGbJ1.QzDNJhvZG/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/e64dde644d24c93af9fa690cfda98537/xxxxx/shell-plugin-plugin-release.apk)
                                                                                                   
 java.lang.NoSuchFieldError: No field valueOf of type Landroid/app/Application; in class Lcom/appsflyer/internal/g; or its superclasses (declaration of 'com.appsflyer.internal.g' appears in /data/user/0/com.xrshBbGbJ1.QzDNJhvZG/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/e64dde644d24c93af9fa690cfda98537/xxxxx/shell-plugin-plugin-release.apk)

at com.appsflyer.internal.o.values(:2058)
at java.lang.reflect.Method.invoke(Native Method)
at com.appsflyer.internal.ae$d.run(:3175)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at com.appsflyer.internal.k$1$5.run(:31)
at java.lang.Thread.run(Thread.java:761)
```

反编译插件apk确认类com/appsflyer/internal/g里面的valueOf类型已经被替换成ShadowApplication，而这里com.appsflyer.internal.o.values仍然认为他的类型是Application，所以这个类应该没有被transform，而反编译这个库的源码没有找到com.appsflyer.internal.o这个类，应该是动态加载出来的，看上一句堆栈java.lang.reflect.Method.invoke(Native Method)是反射去加载的com.appsflyer.internal.o。
所以针对这种第三方库有什么好的解决方案么。

**Comment by richardwrq** [comment]
您的来信已收到。谢谢

**Comment by richardwrq** [comment]
> 这个显然不会有通用的解决方案，否则我们就没必要在编译期transform了。
> 
> 本着“计算机科学领域的任何问题都可以通过增加一个间接的中间层来解决”的原则，可以考虑将被反射调用的类改为一个中间层，使它可以和被transform的其他插件类交互。不过这不一定真的可行，特别是在非公开API不可用的限制下。
> 
> 也可以考虑捕获那个动态加载的包，本地提前transform它。当然也需要修改加载它的代码，转而加载我们改造的。

了解，动态加载的包应该不太好获取，大概率被加密了，我想到一个方案是在这个类里面增加一个同名不同类型的变量，他的类型是application的子类，实际上内部就是代理模式将方法交给shadowapplication去执行

**Comment by richardwrq** [comment]
或者有没有可能设计成shadowApplication是application的子类？

**Comment by shifujun** [comment]
> 或者有没有可能设计成shadowApplication是application的子类？

ShadowApplication、ShadowXXX这些都是变继承为组合的设计。如果是继承的话，就会有一些非公开API接口不让调用。而我们又没有向上转型的需求，所以应该变继承为组合。

**Comment by richardwrq** [comment]
> 

了解了，感谢回复。我这边想想怎么解决
