### ISSUE TITLE
使用 DialogFragment 报错，找不到 setOwnerActivity

### ISSUE THREAD

**Issue by donglua** [Tencent/Shadow#115]
```
    java.lang.NoSuchMethodError: No virtual method setOwnerActivity(Lcom/tencent/shadow/core/runtime/ShadowActivity;)V in class Lcom/tencent/shadow/core/runtime/ShadowDialog; or its super classes (declaration of 'com.tencent.shadow.core.runtime.ShadowDialog' appears in /data/user/0/cn.jingzhuan.shell.stock/files/ShadowPluginManager/UnpackedPlugin/jz-dynamic-manager/45ecbea61f2a28f91780079c1bc90b78/plugin-debug.zip/jz_runtime-debug.apk)
        at androidx.fragment.app.DialogFragment.onActivityCreated(DialogFragment.java:417)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2460)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1483)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2466)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1483)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2646)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2416)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2372)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
```

报错的代码指向```DialogFragment```这一句：

![image](https://user-images.githubusercontent.com/3875265/64472470-9b735200-d191-11e9-8e92-a91afe2448ac.png)

**Comment by donglua** [comment]
发现问题是因为经过```DialogTransform```之后，```Dialog``` 有 ```setOwnerActivity(Activity)``` 和```setOwnerPluginActivity(ShadowActivity)```，没有 ```setOwnerActivity(ShadowActivity)``` 方法。

**Comment by shifujun** [comment]
#145 #147 修复了这个问题。

原本的错误不是缺少setOwnerActivity方法，而是转换成setOwnerPluginActivity方法失败了。

抱歉一直忙，现在才处理这个问题。
