### ISSUE TITLE
加载插件报错：Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory

### ISSUE THREAD

**Issue by EmptyPages** [Tencent/Shadow#1213]
Caused by: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory
                                                                                                    	at android.os.Parcel.createException(Parcel.java:1958)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:1918)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:1868)
                                                                                                    	at com.tencent.shadow.dynamic.manager.BinderPluginLoader.loadPlugin(BinderPluginLoader.java:50)
                                                                                                    	at com.casic.titan.shadow.manager.FastPluginManager.loadPlugin(FastPluginManager.java:138)
                                                                                                    	at com.casic.titan.shadow.manager.SamplePluginManager

**Comment by EmptyPages** [comment]
我继承的是AppCompatActivity，是这个问题吗？

**Comment by luoxiong94** [comment]
遇到同样的错误，请问是如何解决的？

**Comment by EmptyPages** [comment]
> 遇到同样的错误，请问是如何解决的？

你可以看下我的github，上面附有博客地址，怎么解决的我忘了，但是我怕后面我忘所以写了个博客记一下，你可以参考一下，https://github.com/fzkf9225/shadow-plugin-master

**Comment by aprz512** [comment]
我也遇到了，打印了一下，发现是 loader manager runtime 里面自动生成的 application 导致的，因为没有应用插件，所以没有做变换，去掉就行了。
