### ISSUE TITLE
从assets中复制apk出错

### ISSUE THREAD

**Issue by EmptyPages** [Tencent/Shadow#1215]
`Process: com.casic.titan.shadow, PID: 15583
                                                                                                    java.lang.RuntimeException: 从assets中复制apk出错
                                                                                                    	at com.casic.titan.shadow.plugin_manager.PluginHelper.preparePlugin(PluginHelper.java:56)
                                                                                                    	at com.casic.titan.shadow.plugin_manager.PluginHelper.lambda$init$0$com-casic-titan-shadow-plugin_manager-PluginHelper(PluginHelper.java:46)
                                                                                                    	at com.casic.titan.shadow.plugin_manager.PluginHelper$$ExternalSyntheticLambda0.run(Unknown Source:2)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
                                                                                                    Caused by: java.io.FileNotFoundException: plugin-debug.zip
                                                                                                    	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
                                                                                                    	at android.content.res.AssetManager.open(AssetManager.java:744)
                                                                                                    	at android.content.res.AssetManager.open(AssetManager.java:721)
                                                                                                    	at com.casic.titan.shadow.plugin_manager.PluginHelper.preparePlugin(PluginHelper.java:53)
                                                                                                    	at com.casic.titan.shadow.plugin_manager.PluginHelper.lambda$init$0$com-casic-titan-shadow-plugin_manager-PluginHelper(PluginHelper.java:46) 
                                                                                                    	at com.casic.titan.shadow.plugin_manager.PluginHelper$$ExternalSyntheticLambda0.run(Unknown Source:2) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:764) `

**Comment by hahajing9** [comment]
因为复制的路径与你本地 编译的 type不一致导致的
