### ISSUE TITLE
找不到目录，有大佬遇到过这个问题吗？

### ISSUE THREAD

**Issue by qczgwxg** [Tencent/Shadow#1225]
FATAL EXCEPTION: pool-5-thread-1
                                                                                                    Process: com.tencent.shadow.sample.host, PID: 11274
                                                                                                    java.lang.RuntimeException: java.io.FileNotFoundException: /data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/sample-manager/29ce01223adfb00c558966f2263472cc/plugin-debug.zip/plugin-debug/config.json: open failed: ENOENT (No such file or directory)
                                                                                                    	at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:93)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
                                                                                                    Caused by: java.io.FileNotFoundException: /data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/sample-manager/29ce01223adfb00c558966f2263472cc/plugin-debug.zip/plugin-debug/config.json: open failed: ENOENT (No such file or directory)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:575)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
                                                                                                    	at com.tencent.shadow.core.manager.installplugin.MinFileUtils.writeOutInputStream(MinFileUtils.java:176)
                                                                                                    	at com.tencent.shadow.core.manager.installplugin.MinFileUtils.writeOutZipEntry(MinFileUtils.java:163)
                                                                                                    	at com.tencent.shadow.core.manager.installplugin.UnpackManager.unpackPlugin(UnpackManager.java:131)
                                                                                                    	at com.tencent.shadow.core.manager.BasePluginManager.installPluginFromZip(BasePluginManager.java:98)
                                                                                                    	at com.tencent.shadow.sample.manager.FastPluginManager.installPlugin(FastPluginManager.java:43)
                                                                                                    	at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:81)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:920) 
                                                                                                    Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                                    	at libcore.io.Linux.open(Native Method)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
                                                                                                    	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
                                                                                                    	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
                                                                                                    	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8611)
                                                                                                    	at libcore.io.IoBridge.open(IoBridge.java:561)
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:236) 
                                                                                                    	at java.io.FileOutputStream.<init>(FileOutputStream.java:186) 
                                                                                                    	at com.tencent.shadow.core.manager.installplugin.MinFileUtils.writeOutInputStream(MinFileUtils.java:176) 
                                                                                                    	at com.tencent.shadow.core.manager.installplugin.MinFileUtils.writeOutZipEntry(MinFileUtils.java:163) 
                                                                                                    	at com.tencent.shadow.core.manager.installplugin.UnpackManager.unpackPlugin(UnpackManager.java:131) 
                                                                                                    	at com.tencent.shadow.core.manager.BasePluginManager.installPluginFromZip(BasePluginManager.java:98) 
                                                                                                    	at com.tencent.shadow.sample.manager.FastPluginManager.installPlugin(FastPluginManager.java:43) 
                                                                                                    	at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:81) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
                                                                                                    	at java.lang.Thread.run(Thread.java:920)

**Comment by qczgwxg** [comment]
插件管理器代码走到这一步就走不下去了
installPluginFromZip
