### ISSUE TITLE
无法实例化壳子

### ISSUE THREAD

**Issue by qczgwxg** [Tencent/Shadow#1228]
Process: com.tencent.shadow.sample.host, PID: 12981
                                                                                                    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.tencent.shadow.sample.host/com.tencent.shadow.sample.runtime.PluginDefaultProxyActivity}: java.lang.ClassNotFoundException: Didn't find class "com.tencent.shadow.sample.runtime.PluginDefaultProxyActivity" on path: DexPathList[[zip file "/data/app/com.tencent.shadow.sample.host-2/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.shadow.sample.host-2/lib/x86, /system/lib, /vendor/lib]]
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2581)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2759)
                                                                                                    	at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:154)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6190)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.shadow.sample.runtime.PluginDefaultProxyActivity" on path: DexPathList[[zip file "/data/app/com.tencent.shadow.sample.host-2/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.shadow.sample.host-2/lib/x86, /system/lib, /vendor/lib]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2571)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2759) 
                                                                                                    	at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                    	at android.os.Looper.loop(Looper.java:154) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6190) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782) 
```[tasklist]
### Tasks
```

**Comment by jayyuz** [comment]
展示下你启动插件的代码，是不是因为没有同步，导致classloader异常了呢？

**Comment by wh963572516** [comment]
我也遇到了，怎麽解決

**Comment by wh963572516** [comment]
> Process: com.tencent.shadow.sample.host, PID: 12981 java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.tencent.shadow.sample.host/com.tencent.shadow.sample.runtime.PluginDefaultProxyActivity}: java.lang.ClassNotFoundException: Didn't find class "com.tencent.shadow.sample.runtime.PluginDefaultProxyActivity" on path: DexPathList[[zip file "/data/app/com.tencent.shadow.sample.host-2/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.shadow.sample.host-2/lib/x86, /system/lib, /vendor/lib]] at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2581) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2759) at android.app.ActivityThread.-wrap12(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6190) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782) Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.shadow.sample.runtime.PluginDefaultProxyActivity" on path: DexPathList[[zip file "/data/app/com.tencent.shadow.sample.host-2/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.shadow.sample.host-2/lib/x86, /system/lib, /vendor/lib]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) at java.lang.ClassLoader.loadClass(ClassLoader.java:380) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at android.app.Instrumentation.newActivity(Instrumentation.java:1078) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2571) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2759)  at android.app.ActivityThread.-wrap12(ActivityThread.java)  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482)  at android.os.Handler.dispatchMessage(Handler.java:102)  at android.os.Looper.loop(Looper.java:154)  at android.app.ActivityThread.main(ActivityThread.java:6190)  at java.lang.reflect.Method.invoke(Native Method)  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782) 
> 
> ### Tasks
> Beta
> [Give feedback](https://github.com/community/community/discussions/39106)
> No tasks being tracked yet.
> 1. [ ] 
>                  
>                
>    
>                
>                  
>                    
>    
>                  
>                    
>                
>              
>              
>                
>      
>          
>        
>    
>    Options
>    
>    
>    
>      
>        
>                    
>      
>          * Convert to issue
>          * Toggle completion
>          * Rename
>          * Remove
> 2.

请参考这个，然后就可以了，在插件启动的时候，换一种start方式
https://github.com/Tencent/Shadow/issues/505
