### ISSUE TITLE
Android 15 Beta版本 Sample Demo 启动插件稳定崩溃: java.lang.RuntimeException: AssetManager has been closed

### ISSUE THREAD

**Issue by yangxy112683** [Tencent/Shadow#1335]
在 Google Pixel 6 的机器, 对应系统为 Android 15 , 运行 Sample 中的 Demo 示例稳定崩溃, 
其崩溃堆栈如下: 
```
2024-06-26 13:51:51.968 12950-12950 WebViewFactory com.tencent.shadow.sample.host E error instantiating provider
        java.lang.RuntimeException: AssetManager has been closed
        at android.content.res.AssetManager.ensureOpenLocked(AssetManager.java:548)
        at android.content.res.AssetManager.addAssetPathInternal(AssetManager.java:487)
        at android.content.res.AssetManager.addSharedLibraryPaths(AssetManager.java:480)
        at android.content.res.ResourcesImpl.<init>(ResourcesImpl.java:212)
        at android.app.ResourcesManager.redirectAllResourcesToNewImplLocked(ResourcesManager.java:1750)
        at android.app.ResourcesManager.appendLibAssetsLocked(ResourcesManager.java:1582)
        at android.app.ResourcesManager.registerResourcePaths(ResourcesManager.java:158)
        at android.content.res.Resources.registerResourcePaths(Resources.java:2862)
        at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:553)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:362)
        at android.webkit.WebView.getFactory(WebView.java:2606)
        at android.webkit.WebView.ensureProviderCreated(WebView.java:2600)
        at android.webkit.WebView.setOverScrollMode(WebView.java:2668)
        at android.view.View.<init>(View.java:5821)
        at android.view.View.<init>(View.java:5962)
        at android.view.ViewGroup.<init>(ViewGroup.java:705)
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
        at android.webkit.WebView.<init>(WebView.java:422)
        at android.webkit.WebView.<init>(WebView.java:364)
        at android.webkit.WebView.<init>(WebView.java:346)
        at android.webkit.WebView.<init>(WebView.java:333)
        at android.webkit.WebView.<init>(WebView.java:323)
        at com.tencent.shadow.core.loader.blocs.CreateResourceBloc$create$1.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:959)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loopOnce(Looper.java:232)
        at android.os.Looper.loop(Looper.java:317)
        at android.app.ActivityThread.main(ActivityThread.java:8674)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```
![企业微信截图_97bff8e8-d8ef-435a-b962-4537f0333d9a](https://github.com/Tencent/Shadow/assets/5040181/73e461bd-baa8-4d46-88b0-000b0ef42e8f)

请麻烦看下是否是构造插件Resources的方案在高版本上已失效, 是否有新方案?

**Comment by shifujun** [comment]
> AP31.240426.023.B4

https://developer.android.com/about/versions/15/release-notes

你至少先装个最新的Beta 3再测吧？其实你改标题就能看出来你根本不在意是什么版本。

这些Beta版本系统没什么测试意义，bug会非常多。

你这个堆栈可能也没仔细看，那不就是new一个WebView就挂了么？如果你仔细看了应该在issue中指出来这一点，并且给出你测试new Webview的结果。

**Comment by yangxy112683** [comment]
> > AP31.240426.023.B4
> 
> https://developer.android.com/about/versions/15/release-notes
> 
> 你至少先装个最新的Beta 3再测吧？其实你改标题就能看出来你根本不在意是什么版本。
> 
> 这些Beta版本系统没什么测试意义，bug会非常多。
> 
> 你这个堆栈可能也没仔细看，那不就是new一个WebView就挂了么？如果你仔细看了应该在issue中指出来这一点，并且给出你测试new Webview的结果。

<img width="325" alt="image" src="https://github.com/Tencent/Shadow/assets/5040181/f2cb7fc2-0cad-456f-b49c-2357c790af5a">


1. 受教了, 在安装最新版本的 Beta 3 上验证了 new WebView, 在宿主进程中可以正常创建 WebView 对象, 在Shadow 示例中的CreateResourceBloc中, 尝试使用hostAppContext 来new 一个 WebView, 会有以下堆栈的报错

```
com.tencent.shadow.sample.host       E  error instantiating provider
            java.lang.RuntimeException: AssetManager has been closed
            at android.content.res.AssetManager.ensureOpenLocked(AssetManager.java:548)
            at android.content.res.AssetManager.addAssetPathInternal(AssetManager.java:487)
            at android.content.res.AssetManager.addSharedLibraryPaths(AssetManager.java:480)
            at android.content.res.ResourcesImpl.<init>(ResourcesImpl.java:212)
            at android.app.ResourcesManager.redirectAllResourcesToNewImplLocked(ResourcesManager.java:1750)
            at android.app.ResourcesManager.appendLibAssetsLocked(ResourcesManager.java:1582)
            at android.app.ResourcesManager.registerResourcePaths(ResourcesManager.java:158)
            at android.content.res.Resources.registerResourcePaths(Resources.java:2862)
            at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:553)
            at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:362)
            at android.webkit.WebView.getFactory(WebView.java:2606)
            at android.webkit.WebView.ensureProviderCreated(WebView.java:2600)
            at android.webkit.WebView.setOverScrollMode(WebView.java:2668)
            at android.view.View.<init>(View.java:5820)
            at android.view.View.<init>(View.java:5961)
            at android.view.ViewGroup.<init>(ViewGroup.java:705)
            at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
            at android.webkit.WebView.<init>(WebView.java:422)
            at android.webkit.WebView.<init>(WebView.java:364)
            at android.webkit.WebView.<init>(WebView.java:346)
            at android.webkit.WebView.<init>(WebView.java:333)
            at android.webkit.WebView.<init>(WebView.java:323)
            at com.tencent.shadow.core.loader.blocs.CreateResourceBloc$create$1.run(Unknown Source:4)
            at android.os.Handler.handleCallback(Handler.java:959)
            at android.os.Handler.dispatchMessage(Handler.java:100)
            at android.os.Looper.loopOnce(Looper.java:232)
            at android.os.Looper.loop(Looper.java:317)
            at android.app.ActivityThread.main(ActivityThread.java:8699)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

2. 查阅 Android 源码, 发现是在```frameworks/base/core/java/android/webkit/WebViewFactory.java```中抛出的异常

<img width="987" alt="image" src="https://github.com/Tencent/Shadow/assets/5040181/01d33f9b-0c65-4a99-8460-379395b18e34">

请问该问题是否需要在 Android 15 最终的 Release 版本上验证才有意义?

**Comment by yaochaoyang** [comment]
how to fix it？

**Comment by quibbler01** [comment]
damn, google should fix it

**Comment by zslsyx** [comment]
遇到同样的问题

**Comment by alwaysdh** [comment]
楼主解决了吗

**Comment by budaowengd** [comment]
遇到同样的问题，请问如何解决

**Comment by oceanghy** [comment]
这个是Android 15特性导致的吗，遇到同样加载插件crash的问题

**Comment by yangxy112683** [comment]
目前暂未解决, 预计需要等 Android 15 正式版本再验证下

**Comment by JT-360** [comment]
正式版本也有问题，怎么解决~

**Comment by lbwstco** [comment]
楼主解决了吗

**Comment by yangxy112683** [comment]
<img width="424" alt="企业微信截图_4e361da8-2320-4ec0-ba85-857e3c318934" src="https://github.com/user-attachments/assets/282a3d1e-f109-4f82-b20d-874b1fe0110e">
<img width="421" alt="企业微信截图_b0479300-bc30-411a-8212-58dfdd496f0b" src="https://github.com/user-attachments/assets/532fc5c8-71bb-4b73-8de7-78b8735082d3">

**Comment by yangxy112683** [comment]
<img width="421" alt="企业微信截图_b0479300-bc30-411a-8212-58dfdd496f0b" src="https://github.com/user-attachments/assets/9e46f6e7-2e76-4c9b-8399-f1cd149a1ab3">

**Comment by yangxy112683** [comment]
使用 Pixel 6 Pro, 升级至 Android 15 beta 最新版本, 该问题已修复; 具体可参考: https://issuetracker.google.com/issues/357131361

<img width="424" alt="企业微信截图_4e361da8-2320-4ec0-ba85-857e3c318934" src="https://github.com/user-attachments/assets/48c23ebd-1c23-4b3f-9091-48053c29daca">
<img width="421" alt="企业微信截图_b0479300-bc30-411a-8212-58dfdd496f0b" src="https://github.com/user-attachments/assets/f7d11b55-23ff-4549-92f6-854daaea3c2c">
