### ISSUE TITLE
迁移到Androidx 好像有一些兼容的问题

### ISSUE THREAD

**Issue by LanJD** [Tencent/Shadow#152]
java.lang.IncompatibleClassChangeError: Class 'com.tencent.shadow.sample.plugin.app.lib.home.HomeActivity' does not implement interface 'android.view.KeyEvent$Callback' in call to 'boolean android.view.KeyEvent$Callback.onKeyDown(int, android.view.KeyEvent)' (declaration of 'android.view.KeyEvent' appears in /system/framework/framework.jar!classes2.dex)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2693)
        at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:137)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:133)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2533)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:357)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4819)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4691)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4231)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4284)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4250)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4377)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4258)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4434)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4231)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4284)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4250)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4258)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4231)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4284)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4250)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4410)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4573)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2430)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1993)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1984)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2407)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:331)
        at android.os.Looper.loop(Looper.java:149)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
迁移的过程没有做太大的改动，只把Demo里的插件App做了androidx改动，normal没什么问题，放到host里finish的时候crash了，https://github.com/Tencent/Shadow/pull/107  ,里插件实现android.view.KeyEvent.Callback确实可以，又发现源码里有类似实现，解决办法com.tencent.shadow.core.runtime.PluginActivity实现android.view.KeyEvent.Callback，并复写两个回调。就不会crash了

**Comment by shifujun** [comment]
额，我没太看明白。问题是说PluginActivity没实现`android.view.KeyEvent.Callback`接口导致Crash吗？但是最近的#107 不是实现了吗？你最后说的实现并复写两个回调就不会Crash了。dev分支上的代码应该已经是这样了吧？

**Comment by LanJD** [comment]
> 额，我没太看明白。问题是说PluginActivity没实现`android.view.KeyEvent.Callback`接口导致Crash吗？但是最近的#107 不是实现了吗？你最后说的实现并复写两个回调就不会Crash了。dev分支上的代码应该已经是这样了吧？

是的，必须要实现android.view.KeyEvent.Callback，我这边的场景是在插件里用了JetPack的Navigation，插件继承的是AppCompatActivity，虽然Shadow里通过委托接口实现回调，但问题应该不再这里，源码里androidx.core.app.AppCompatActivity#dispatchKeyEvent有一个这样的返回代码KeyEventDispatcher.dispatchKeyEvent(this, decor, this, event);在KeyEventDispatcher的方法activitySuperDispatchKeyEventPre28(Activity activity, KeyEvent event)中返回值是调用Event.dispatch(Callback receiver, DispatcherState state,Object target) ,问题就在这里，传入的类型不正确，正常情况下，这里的receiver传入的是activity，看了下字节码，传入的是ShadowActivity，这也符合预期，
    check-cast v0, Lcom/tencent/shadow/core/runtime/ShadowActivity;
    invoke-static {v0, p3}, Landroidx/core/view/KeyEventDispatcher;->activitySuperDispatchKeyEventPre28(Lcom/tencent/shadow/core/runtime/ShadowActivity;Landroid/view/KeyEvent;)Z
所以ShadowActivity必须实现android.view.KeyEvent.Callback，要不然后续也不会与宿主产生回调，不知道理解的对不对

**Comment by shifujun** [comment]
你能否fork一下，在shadow的sample上做一下能复现问题的改动。这样我就能比较快的理解问题了。

**Comment by LanJD** [comment]
> 你能否fork一下，在shadow的sample上做一下能复现问题的改动。这样我就能比较快的理解问题了。

你只要把插件的工程迁移到androidx 就行，然后用AppCompatActivity，另外还有一个坑，最新的版本androidx.appcompat:appcompat为1.1.0的版本setHostContextAsBase的时候会出现空指针，查看源码发现Google增加了什么暗模式，提前会需要调用application的上下文获取资源，所以在initPluginActivity的时候把setHostContextAsBase放在setShadowApplication后面避免空掉

啊西巴，虽然原理看起来原来简单，但是工程代码看起来好复杂，绕来绕去，另外，不知道支持多插件的Demo什么是出来，或者可以讲讲实现思路！

**Comment by shifujun** [comment]
我近期工作安排和Shadow没什么关系，所以能花在这上面的精力就比较有限。虽然说我去写用例也能写，但是毕竟要花时间。关键是我写的很大概率上跟你想的不一样，因为每个人的想法都不同，文字表达出来的准确性也是问题。所以有著名的"talk is cheap, show me the code."的说法。

所以，你不给我代码的话，我就不一定什么时候有时间处理这个问题了。

多插件的Demo确实写起来也挺麻烦的，因为多插件的场景特别多。`test-dynamic-host`那个测试工程里就有多个插件，你可以先看看。
