### ISSUE TITLE
二进制Maven依赖SDK的Sample Crash

### ISSUE THREAD

**Issue by mayi203** [Tencent/Shadow#177]
按照 Sample 说明分别编译并 push 到本地后运行 host-project 点击启动插件 Crash:
    Process: com.tencent.shadow.sample.host, PID: 25301
    java.lang.RuntimeException: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.MainActivity}; have you declared this activity in your AndroidManifest.xml?

**Comment by shifujun** [comment]
修好了，再试试。另外下次可以注意下实际的异常堆栈在插件进程。主进程这里的异常不准确。

**Comment by mayi203** [comment]
还是会 crash ,这是插件进程异常堆栈：
2019-11-21 20:17:48.657 28661-28752/com.tencent.shadow.sample.host:plugin E/GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
2019-11-21 20:17:48.742 28661-28673/com.tencent.shadow.sample.host:plugin E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.tencent.shadow.core.loader.exceptions.CreateApplicationException: java.lang.InstantiationException: java.lang.Class<com.tencent.shadow.core.runtime.ShadowApplication> cannot be instantiated
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:82)
        at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:42)
        at android.os.Binder.execTransact(Binder.java:674)
     Caused by: java.util.concurrent.ExecutionException: com.tencent.shadow.core.loader.exceptions.CreateApplicationException: java.lang.InstantiationException: java.lang.Class<com.tencent.shadow.core.runtime.ShadowApplication> cannot be instantiated
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildRunningPlugin$1.run(Unknown Source:50)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.tencent.shadow.core.loader.exceptions.CreateApplicationException: java.lang.InstantiationException: java.lang.Class<com.tencent.shadow.core.runtime.ShadowApplication> cannot be instantiated

**Comment by shifujun** [comment]
```
java.lang.Class<com.tencent.shadow.core.runtime.ShadowApplication> cannot be instantiated
```
这个异常是因为之前ShadowApplication被定义成了抽象类，所以不能new出来。

你确认一下你本地的代码是否包含了06684e1的修改。

或者把之前的安装包删掉。或者是不是忘了更新maven依赖的版本，或者忘了adb push了？

**Comment by mayi203** [comment]
我更新代码，并且重新编译 push 了

**Comment by shifujun** [comment]
那我再重头试一次。

**Comment by shifujun** [comment]
我又重头试了一次还是没问题。

建议你反编译一下
plugin-debug.zip中的sample-runtime-debug.apk，看看ShadowApplication是不是abstract的。

**Comment by mayi203** [comment]
抱歉，是我错了，我忘了修改 ext.shadow_version

**Comment by shifujun** [comment]
没事，那关闭啦
