### ISSUE TITLE
projects/sample/maven sample crash

### ISSUE THREAD

**Issue by mayi203** [Tencent/Shadow#180]
按照说明编译执行 projects/sample/maven 下的示例程序 crash:
java.lang.RuntimeException: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.MainActivity}; have you declared this activity in your AndroidManifest.xml?
        at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:100)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by shifujun** [comment]
跟 #177 不是一个问题吗？我刚才试过了，可以正常跑了啊。
