### ISSUE TITLE
Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory

### ISSUE THREAD

**Issue by donglua** [Tencent/Shadow#187]
```
     Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildRunningPlugin$1.run(Unknown Source:50)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.util.concurrent.ExecutionException: java.lang.ClassCastException: Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildApplication$1.call(Unknown Source:37)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildApplication$1.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.ClassCastException: Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory
        at java.lang.Class.cast(Class.java:2442)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildAppComponentFactory$1.call(Unknown Source:36)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildAppComponentFactory$1.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

https://github.com/donglua/ShadowX/commit/a7c5d8face2a8e58cd09cd02d1b4c8ce9b87c447
我把将 appcompat 包加到宿主，然后把 ```android.**```加入白名单，运行出现以上崩溃 

代码：
https://github.com/donglua/ShadowX/tree/pr20191125

**Comment by shifujun** [comment]
这确实不能直接让插件复用宿主的。

这和插件想继承宿主的Activity基类是一样的。

`androidx.core.app.CoreComponentFactory`的基类在Transform时需要改成`ShadowAppComponentFactory`，而宿主里的`androidx.core.app.CoreComponentFactory`显然没有经过Transform。所以插件里的AndroidX和宿主里的，实际上代码是不一样的。

如果确实想复用，需要保留一部分被Shadow编辑过的类，使用插件里的实现。而Shadow没有处理的类，比如Fragment，就可以使用宿主里的类。

Shadow处理了AndroidX里的类，涉及到全部引用了Activity、Service类型的类。
