### ISSUE TITLE
使用感觉有点复杂

### ISSUE THREAD

**Issue by mayi203** [Tencent/Shadow#191]
相比其他插件框架，如 VirtualAPK。使用起来感觉复杂了一些，尤其是 plugin 要分 loader ，runtime 等许多部分

**Comment by shifujun** [comment]
这个主要是因为Shadow把插件框架也给动态化起来了。如果这部分不需要动态化，用法跟其他插件框架也差不多。

像这个test工程就是非动态化的，把loader，runtime那些都打包在host里了。
https://github.com/Tencent/Shadow/tree/dev/projects/test/none-dynamic/host/test-none-dynamic-host

**Comment by mayi203** [comment]
test-none-dynamic-host 会 crash
Caused by: java.lang.RuntimeException: 加载失败
        at com.tencent.shadow.test.none_dynamic.host.HostApplication.loadPlugin(HostApplication.java:85)
        at com.tencent.shadow.test.none_dynamic.host.MainActivity.startPlugin(MainActivity.java:61)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.view.View$DeclaredOnClickListener.onClick(View.java:5331) 
        at android.view.View.performClick(View.java:6256) 
        at android.view.View$PerformClick.run(View.java:24697) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164)

**Comment by shifujun** [comment]
暂时没时间维护这个用例了。能编译过就说明接口使用方式还是适用的。跑起来的效果跟动态的是一样的。

**Comment by cylee0909** [comment]
> HostApplication

我这个pull request 修复了相关问题，你可以合并试一下
