### ISSUE TITLE
Demo直接Crash了

### ISSUE THREAD

**Issue by vimerzhao** [Tencent/Shadow#198]
点击启动插件，直接Crash了，信息如下

```
2019-12-03 19:17:39.877 24400-24584/com.tencent.shadow.sample.host E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.tencent.shadow.sample.host, PID: 24400
    java.lang.RuntimeException: android.os.DeadObjectException
        at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:118)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1147)
        at com.tencent.shadow.dynamic.manager.BinderPluginLoader.loadPlugin(BinderPluginLoader.java:46)
        at com.tencent.shadow.sample.manager.FastPluginManager.loadPlugin(FastPluginManager.java:141)
        at com.tencent.shadow.sample.manager.FastPluginManager.convertActivityIntent(FastPluginManager.java:119)
        at com.tencent.shadow.sample.manager.FastPluginManager.startPluginActivity(FastPluginManager.java:111)
        at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:116)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 

```

**Comment by shifujun** [comment]
可能是私有api检测触发的。你用的是9.0系统吧？dev分支加webview测试用例时引入的。

**Comment by shifujun** [comment]
这行注释掉试试
https://github.com/Tencent/Shadow/blob/dev/projects/sample/source/sample-host/src/main/java/com/tencent/shadow/sample/host/HostApplication.java#L47

**Comment by vimerzhao** [comment]
确实这个原因，感谢

**Comment by JohnLie** [comment]
> api

是的呢。我是9.0的系统

**Comment by shifujun** [comment]
最近抽时间修复这个问题。
