### ISSUE TITLE
java.lang.RuntimeException: java.lang.IllegalArgumentException: 无法绑定PPS:com.tencent.shadow.sample.host.PluginProcessPPS

### ISSUE THREAD

**Issue by fso918** [Tencent/Shadow#20]
2019-06-26 16:43:35.011 30138-30179/com.baiwan.pk:plugin E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.baiwan.pk:plugin, PID: 30138
    java.lang.RuntimeException: java.lang.IllegalArgumentException: 无法绑定PPS:com.tencent.shadow.sample.host.PluginProcessPPS
        at com.tencent.shadow.a.a.b$1.run(Unknown Source:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalArgumentException: 无法绑定PPS:com.tencent.shadow.sample.host.PluginProcessPPS
        at com.tencent.shadow.dynamic.a.b.a(Unknown Source:119)
        at com.tencent.shadow.a.a.a.f(Unknown Source:8)
        at com.tencent.shadow.a.a.a.e(Unknown Source:0)
        at com.tencent.shadow.a.a.a.a(Unknown Source:2)

**Comment by fso918** [comment]
集成到自己项目中报这个异常，麻烦帮忙看下

**Comment by fso918** [comment]
在SamplePluginManager写死了service的名字：
@Override
    protected String getPluginProcessServiceName() {
        return "com.tencent.shadow.sample.host.PluginProcessPPS";
    }
而集成的时候宿主的service为
package com.xgame.shadow;

import com.tencent.shadow.dynamic.host.PluginProcessService;

public class PluginProcessPPS extends PluginProcessService {
}
导致找不到service了
