### ISSUE TITLE
sample-host 闪退

### ISSUE THREAD

**Issue by JohnLie** [Tencent/Shadow#206]
大佬，sample-host 运行闪退呀。没有改任何代码、

2019-12-07 18:21:41.317 9920-9970/com.tencent.shadow.sample.host E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.tencent.shadow.sample.host, PID: 9920
    java.lang.RuntimeException: android.os.DeadObjectException
        at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:118)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1136)
        at com.tencent.shadow.dynamic.manager.BinderPluginLoader.loadPlugin(BinderPluginLoader.java:46)
        at com.tencent.shadow.sample.manager.FastPluginManager.loadPlugin(FastPluginManager.java:141)
        at com.tencent.shadow.sample.manager.FastPluginManager.convertActivityIntent(FastPluginManager.java:119)
        at com.tencent.shadow.sample.manager.FastPluginManager.startPluginActivity(FastPluginManager.java:111)
        at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:116)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/issues/198#issuecomment-561153525
