### ISSUE TITLE
NoClassDefFoundError:Failed resolution of: Lcom/tencent/shadow/dynamic/loader/PluginLoader

### ISSUE THREAD

**Issue by donglua** [Tencent/Shadow#236]
```
1 java.lang.NoClassDefFoundError:Failed resolution of: Lcom/tencent/shadow/dynamic/loader/PluginLoader;
--
2 cn.jingzhuan.stock.manager.FastPluginManager.loadPlugin(FastPluginManager.java:138)
3 ......
4 Caused by:
5 java.lang.NoClassDefFoundError:Class not found using the boot class loader; no stack trace available
```

![SmartSelect_20191229-080527_Chrome](https://user-images.githubusercontent.com/3875265/71550748-688bed00-2a12-11ea-936f-8381cfac5bfb.jpg)

线上统计到有 android 10 不兼容的问题，本地还没有重现，没有头绪，请问有遇到类似问题或者解决的思路吗？

**Comment by shifujun** [comment]
我们还没注意到有类似的上报，我们也观察一下。

你的堆栈应该被你省略过吧？要不贴个完整的看看？

找不到类定义除了因为类本身找不到到，还可能是类以来的其他类找不到。现在找不到的类是个接口，它依赖的类也不多。

就类找不到这种类型的异常来说，shadow的实现原理上只有container的动态化会有可能出问题。但可能性微乎其微。

你有测试过其他android 10的手机吗？

**Comment by donglua** [comment]
![SmartSelect_20191229-131327_Chrome](https://user-images.githubusercontent.com/3875265/71552820-b28ac800-2a3e-11ea-9071-60e271c7900b.jpg)

手上测试机不多，还没有重现出来。完整的堆栈只有这些，晚点我把前后的日志也导出来

**Comment by donglua** [comment]
```

812-28 07:49:34.810 13502 13998 D HiTouch_PressGestureDetector: onAttached, package=cn.jingzhuan.stock, windowType=1, mHiTouchRestricted=false
--
8912-28 07:49:34.814 13502 13580 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
9012-28 07:49:34.872 13502 13580 D OpenGLRenderer: disableOutlineDraw is true
9112-28 07:49:35.217 13502 13580 W libEGL : EGLNativeWindowType 0x7059a8d2d0 disconnect failed
9212-28 07:49:35.224 13502 13502 D HMSAgent: Activity(1374)->Application(503)->ProGuard(218)->onActivityStopped
9312-28 07:49:35.224 13502 13502 D HMSAgent: onStopped:cn.jingzhuan.stock.ui.activity.MainActivity@fa93fe
9412-28 07:49:35.289 13502 13649 I UtilsSDK: Thread Pool is close
9512-28 07:49:36.334 13502 13502 W Settings: Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
9612-28 07:49:36.334 13502 13502 V HiTouch_HiTouchSensor: User setup is finished.
9712-28 07:49:36.410 13502 13502 V AudioManager: querySoundEffectsEnabled...
9812-28 07:49:36.427 13502 13562 D cn.jingzhuan.stock.host.JZPluginInitializer: loadPluginManager
9912-28 07:49:36.427 13502 13562 D cn.jingzhuan.stock.host.JZPluginInitializer: enter partKey = plugin_topic_hunter
10012-28 07:49:36.427 13502 13562 I com.tencent.shadow.dynamic.host.DynamicPluginManager: enter fromId:1002 callback:cn.jingzhuan.stock.biz.home.shortcut.ShortcutManager$pool$2$5$1@d2d9859
10112-28 07:49:36.427 13502 13562 I com.tencent.shadow.dynamic.host.DynamicPluginManager: mLastModified != lastModified : true
10212-28 07:49:36.430 13502 13562 W jingzhuan.stoc: ClassLoaderContext classpath element mismatch. expected=/data/app/cn.jingzhuan.stock-YG4J3fG4I6aoohJglmm0lw==/base.apk, found=/data/app/cn.jingzhuan.stock-H7B-hCf_7HTJp0IhvA1Nuw==/base.apk (PCL[];PCL[/data/app/cn.jingzhuan.stock-YG4J3fG4I6aoohJglmm0lw==/base.apk*2490343812:/data/app/cn.jingzhuan.stock-YG4J3fG4I6aoohJglmm0lw==/base.apk!classes2.dex*261566842:/data/app/cn.jingzhuan.stock-YG4J3fG4I6aoohJglmm0lw==/base.apk!classes3.dex*269634713:/data/app/cn.jingzhuan.stock-YG4J3fG4I6aoohJglmm0lw==/base.apk!classes4.dex*671904655:/data/app/cn.jingzhuan.stock-YG4J3fG4I6aoohJglmm0lw==/base.apk!classes5.dex*3074597683:/data/app/cn.jingzhuan.stock-YG4J3fG4I6aoohJglmm0lw==/base.apk!classes6.dex*753268980:/data/app/cn.jingzhuan.stock-YG4J3fG4I6aoohJglmm0lw==/base.apk!classes7.dex*2480103786:/data/app/cn.jingzhuan.stock-YG4J3fG4I6aoohJglmm0lw==/base.apk!classes8.dex*2425118686:/data/app/cn.jingzhuan.stock-YG4J3fG4I6aoohJglmm0lw==/base.apk!classes9.dex*2563076474] \| PCL[];PCL[/data/app/cn.jingzhuan.stock-H7B-hCf_7HTJp0I
10312-28 07:49:36.432 13502 13562 W jingzhuan.stoc: Found duplicate classes, falling back to extracting from APK : /data/user/0/cn.jingzhuan.stock/files/plugin_manager.apk
10412-28 07:49:36.432 13502 13562 W jingzhuan.stoc: NOTE: This wastes RAM and hurts startup performance.
10512-28 07:49:36.432 13502 13562 W jingzhuan.stoc: Found duplicated class when checking oat files: 'Lcn/jingzhuan/plugins/R;' in /data/app/cn.jingzhuan.stock-H7B-hCf_7HTJp0IhvA1Nuw==/base.apk and /data/user/0/cn.jingzhuan.stock/files/plugin_manager.apk
10612-28 07:49:36.432 13502 13562 W jingzhuan.stoc:
10712-28 07:49:36.434 13502 13562 W jingzhuan.stoc: Unsupported class loader
10812-28 07:49:36.435 13502 13562 W jingzhuan.stoc: Skipping duplicate class check due to unsupported classloader
10912-28 07:49:36.440 13502 13562 I com.tencent.shadow.dynamic.manager.BaseDynamicPluginManager: onCreate bundle:null
11012-28 07:49:36.450 13502 13580 D OpenGLRenderer: disableOutlineDraw is true
11112-28 07:49:36.461 13502 13580 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
11212-28 07:49:36.462 13502 14004 D HiTouch_PressGestureDetector: onAttached, package=cn.jingzhuan.stock, windowType=2, mHiTouchRestricted=false
11312-28 07:49:36.557 13502 14003 I com.tencent.shadow.dynamic.manager.BaseDynamicPluginManager: bindPluginProcessService cn.jingzhuan.stock.host.PluginProcessPPS
11412-28 07:49:36.563 13502 14003 I com.tencent.shadow.dynamic.manager.BaseDynamicPluginManager: waiting service connect connectCountDownLatch:java.util.concurrent.CountDownLatch@6c4eefc[Count = 1]
11512-28 07:49:36.564 13502 13502 I cn.jingzhuan.stock.host.PluginProcessPPS: onCreate:cn.jingzhuan.stock.host.PluginProcessPPS@592b985
11612-28 07:49:36.564 13502 13502 I cn.jingzhuan.stock.host.PluginProcessPPS: onBind:cn.jingzhuan.stock.host.PluginProcessPPS@592b985
11712-28 07:49:36.565 13502 13502 I com.tencent.shadow.dynamic.manager.BaseDynamicPluginManager: onServiceConnected connectCountDownLatch:java.util.concurrent.CountDownLatch@6c4eefc[Count = 1]
11812-28 07:49:36.566 13502 13502 I cn.jingzhuan.stock.host.PluginProcessPPS: setUuidManager uuidManager==com.tencent.shadow.dynamic.host.BinderUuidManager@5ddb3da
11912-28 07:49:36.566 13502 13502 I com.tencent.shadow.dynamic.manager.BaseDynamicPluginManager: onServiceConnected countDown:java.util.concurrent.CountDownLatch@6c4eefc[Count = 0]
12012-28 07:49:36.566 13502 14003 I com.tencent.shadow.dynamic.manager.BaseDynamicPluginManager: service connected 3
12112-28 07:49:36.566 13502 14003 I com.tencent.shadow.dynamic.manager.PluginManagerThatUseDynamicLoader: loadRunTime mPpsController:com.tencent.shadow.dynamic.host.PpsController@ce300b
12212-28 07:49:36.566 13502 14003 I cn.jingzhuan.stock.host.PluginProcessPPS: loadRuntime uuid:CF5BE975-50F2-4F1A-87C2-E858B0809A95
12312-28 07:49:36.568 13502 14003 W jingzhuan.stoc: Unsupported class loader
12412-28 07:49:36.572 13502 14003 I com.tencent.shadow.dynamic.manager.PluginManagerThatUseDynamicLoader: loadPluginLoader mPluginLoader:null
12512-28 07:49:36.573 13502 14003 I cn.jingzhuan.stock.host.PluginProcessPPS: loadPluginLoader uuid:CF5BE975-50F2-4F1A-87C2-E858B0809A95 mPluginLoader:null
12612-28 07:49:36.574 13502 14003 I cn.jingzhuan.stock.host.PluginProcessPPS: 取出uuid==CF5BE975-50F2-4F1A-87C2-E858B0809A95的Loader apk:/data/user/0/cn.jingzhuan.stock/files/ShadowPluginManager/UnpackedPlugin/jz-dynamic-manager/a8c9f8bf50645b8d3d2ee3b2f9aaeed5/plugin-release.zip/jz_loader-release.apk
12712-28 07:49:36.574 13502 14003 W jingzhuan.stoc: Unsupported class loader
12812-28 07:49:36.595 13502 14003 W jingzhuan.stoc: Unsupported class loader
12912-28 07:49:36.627 13502 14003 I QarthLog: [PatchStore] createDisableExceptionQarthFile
13012-28 07:49:36.627 13502 14003 I QarthLog: [PatchStore] create disable file for cn.jingzhuan.stock uid is 10163
131--------- beginning of crash
13212-28 07:49:36.628 13502 14003 E AndroidRuntime: FATAL EXCEPTION: pool-40-thread-1
13312-28 07:49:36.628 13502 14003 E AndroidRuntime: Process: cn.jingzhuan.stock, PID: 13502
13412-28 07:49:36.628 13502 14003 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/shadow/dynamic/loader/PluginLoader;
13512-28 07:49:36.628 13502 14003 E AndroidRuntime: at cn.jingzhuan.stock.manager.FastPluginManager.loadPlugin(FastPluginManager.java:138)
13612-28 07:49:36.628 13502 14003 E AndroidRuntime: at cn.jingzhuan.stock.manager.FastPluginManager.convertActivityIntent(FastPluginManager.java:118)
13712-28 07:49:36.628 13502 14003 E AndroidRuntime: at cn.jingzhuan.stock.manager.FastPluginManager.startPluginActivity(FastPluginManager.java:109)
13812-28 07:49:36.628 13502 14003 E AndroidRuntime: at cn.jingzhuan.stock.manager.JZPluginManager$1.run(JZPluginManager.java:87)
13912-28 07:49:36.628 13502 14003 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
14012-28 07:49:36.628 13502 14003 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
14112-28 07:49:36.628 13502 14003 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
14212-28 07:49:36.628 13502 14003 E AndroidRuntime: at java.lang.Thread.run(Thread.java:929)
14312-28 07:49:36.628 13502 14003 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.tencent.shadow.dynamic.loader.PluginLoader
14412-28 07:49:36.628 13502 14003 E AndroidRuntime: at java.lang.Class.classForName(Native Method)
14512-28 07:49:36.628 13502 14003 E AndroidRuntime: at java.lang.BootClassLoader.findClass(ClassLoader.java:1358)
14612-28 07:49:36.628 13502 14003 E AndroidRuntime: at java.lang.BootClassLoader.loadClass(ClassLoader.java:1418)
14712-28 07:49:36.628 13502 14003 E AndroidRuntime: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
14812-28 07:49:36.628 13502 14003 E AndroidRuntime: at com.tencent.shadow.dynamic.host.ApkClassLoader.loadClass(ApkClassLoader.java:86)
14912-28 07:49:36.628 13502 14003 E AndroidRuntime: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
15012-28 07:49:36.628 13502 14003 E AndroidRuntime: ... 8 more
15112-28 07:49:36.628 13502 14003 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available


```

**Comment by donglua** [comment]
sample 有没有把```loader```和```runtime```直接集成在宿主的例子，我想把这两个模块从插件里移出来。

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/tree/dev/projects/test/none-dynamic/host/test-none-dynamic-host

这个是没有全动态的例子。不过没有manager和pps。

**Comment by donglua** [comment]
请问这个方式的白名单是否不生效

**Comment by shifujun** [comment]
PluginClassLoader的白名单在设计上是考虑到这种非动态使用时的场景的。实现上有bug还是有可能的，毕竟我们没有业务这样用。
