### ISSUE TITLE
gradlew build Failed，请求帮助

### ISSUE THREAD

**Issue by xuyunyu** [Tencent/Shadow#267]
小白想下工程研究研究，没成想卡在第一步，再windows cmd line 执行命令，报错。
尝试了升级工程的的gradle版本到6.0，就问题更多了 ==||，求大神助我一臂之力。

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample-runtime:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':sample-runtime:transformClassesAndResourcesWithProguardForRelease'.       
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:96)

Caused by: java.lang.RuntimeException: Job failed, see logs for details
        at com.android.build.gradle.internal.transforms.ProGuardTransform.transform(ProGuardTransform.java:207)

Caused by: java.io.IOException: Please correct the above warnings first.
        at proguard.Initializer.execute(Initializer.java:485)

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.0/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by xuyunyu** [comment]
切到master分支build成功，Dev分支编译失败。先关闭了。

**Comment by shifujun** [comment]
dev分支一直没时间做整体的构建修复。dev分支可以正常编译debub版，应该是有些warnning没有修复。
