### ISSUE TITLE
自己创建了一个插件项目，生成的插件包在宿主中导入出现InstallPluginException: 解压so 失败 apkFile:/da

### ISSUE THREAD

**Issue by lenomon** [Tencent/Shadow#270]
1、复制了sample中的host/manager.  复制了sample中的插件loader/runtime构建的新工程，生成plugin.zip包，在host中导入出现了下面的问题：
`3-12 18:06:05.678 8998-9028/com.huke.my.shadow.host E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.huke.my.shadow.host, PID: 8998
    java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.tencent.shadow.core.manager.installplugin.InstallPluginException: 解压so 失败 apkFile:/data/user/0/com.huke.my.shadow.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/acf5e9b5b5231cb83f71e2bdbc80586b/plugin-debug.zip/app-debug.apk abi:lib/armeabi/
        at com.huke.my.shadow.manager.SamplePluginManager$1.run(SamplePluginManager.java:118)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.util.concurrent.ExecutionException: com.tencent.shadow.core.manager.installplugin.InstallPluginException: 解压so 失败 apkFile:/data/user/0/com.huke.my.shadow.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/acf5e9b5b5231cb83f71e2bdbc80586b/plugin-debug.zip/app-debug.apk abi:lib/armeabi/
        at java.util.concurrent.FutureTask.report(FutureTask.java:94)
        at java.util.concurrent.FutureTask.get(FutureTask.java:164)
        at com.huke.my.shadow.manager.FastPluginManager.installPlugin(FastPluginManager.java:108)
        at com.huke.my.shadow.manager.SamplePluginManager$1.run(SamplePluginManager.java:105)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: com.tencent.shadow.core.manager.installplugin.InstallPluginException: 解压so 失败 apkFile:/data/user/0/com.huke.my.shadow.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/acf5e9b5b5231cb83f71e2bdbc80586b/plugin-debug.zip/app-debug.apk abi:lib/armeabi/
        at com.tencent.shadow.core.manager.installplugin.CopySoBloc.copySo(CopySoBloc.java:100)
        at com.tencent.shadow.core.manager.BasePluginManager.extractSo(BasePluginManager.java:198)
        at com.huke.my.shadow.manager.FastPluginManager$3.call(FastPluginManager.java:90)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.util.zip.ZipException: Entry is not named
        at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:268)
        at com.tencent.shadow.core.manager.installplugin.SafeZipInputStream.getNextEntry(SafeZipInputStream.java:32)
        at com.tencent.shadow.core.manager.installplugin.CopySoBloc.copySo(CopySoBloc.java:69)`

lib下的so文件，为空不为空都是这个错误。 
用shadow项目中的sample-host运行没有问题，可以导入插件。

**Comment by lenomon** [comment]
mumu模拟器上运行。

**Comment by shifujun** [comment]
在`Caused by: java.util.zip.ZipException: Entry is not named`处打个断点看看Entry结构到底是什么样的吧。你这只说有这种错误，也没有代码，其他人也只能随便猜原因的。

**Comment by lenomon** [comment]
> 在`Caused by: java.util.zip.ZipException: Entry is not named`处打个断点看看Entry结构到底是什么样的吧。你这只说有这种错误，也没有代码，其他人也只能随便猜原因的。

可能是代码有问题，项目demo已经跑通，这个就弃用了。

**Comment by MmingY** [comment]
我也出现这个问题了，不过我调试之后发现是因为文件找不到异常导致的。原因是我自己重新写了一个项目，然后再sample-app项目中的build.gradle中apkName名字写的不一样，修改名字之后就可以了。
