### ISSUE TITLE
拷貝插件so出錯

### ISSUE THREAD

**Issue by lp821020589** [Tencent/Shadow#276]
2020-03-24 18:32:27.829 12226-12597/com.tencent.shadow.sample.host E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.tencent.shadow.sample.host, PID: 12226
    java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.tencent.shadow.core.manager.installplugin.InstallPluginException: 解压so 失败 apkFile:/data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/16e8b8563bc77371f17e0be4004f7c59/plugin-debug.zip/weier-plugin-app.apk abi:lib//
        at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:118)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.util.concurrent.ExecutionException: com.tencent.shadow.core.manager.installplugin.InstallPluginException: 解压so 失败 apkFile:/data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/16e8b8563bc77371f17e0be4004f7c59/plugin-debug.zip/weier-plugin-app.apk abi:lib//
        at java.util.concurrent.FutureTask.report(FutureTask.java:94)
        at java.util.concurrent.FutureTask.get(FutureTask.java:164)
        at com.tencent.shadow.sample.manager.FastPluginManager.installPlugin(FastPluginManager.java:108)
        at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: com.tencent.shadow.core.manager.installplugin.InstallPluginException: 解压so 失败 apkFile:/data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/16e8b8563bc77371f17e0be4004f7c59/plugin-debug.zip/weier-plugin-app.apk abi:lib//
        at com.tencent.shadow.core.manager.installplugin.CopySoBloc.copySo(CopySoBloc.java:100)
        at com.tencent.shadow.core.manager.BasePluginManager.extractSo(BasePluginManager.java:198)
        at com.tencent.shadow.sample.manager.FastPluginManager$3.call(FastPluginManager.java:90)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: java.io.FileNotFoundException: /data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/16e8b8563bc77371f17e0be4004f7c59/plugin-debug.zip/weier-plugin-app.apk (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at com.tencent.shadow.core.manager.installplugin.CopySoBloc.copySo(CopySoBloc.java:68)
        at com.tencent.shadow.core.manager.BasePluginManager.extractSo(BasePluginManager.java:198) 
        at com.tencent.shadow.sample.manager.FastPluginManager$3.call(FastPluginManager.java:90) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761)

**Comment by shifujun** [comment]
>Caused by: java.io.FileNotFoundException: /data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/16e8b8563bc77371f17e0be4004f7c59/plugin-debug.zip/weier-plugin-app.apk (No such file or directory)

看起来只是一般的文件找不到的错误。建议你在安装的过程中debug一下文件为什么不存在。

**Comment by lenomon** [comment]
![image](https://user-images.githubusercontent.com/4558207/77506429-d07e9200-6ea0-11ea-91d1-ca24d0a7ef72.png)
我也碰到这个问题。遍历到META-INF/MANIFEST.MF文件时，就报了错java.util.zip.ZipException: Entry is not named。很诡异。

**Comment by lenomon** [comment]
@shifujun

**Comment by shifujun** [comment]
我写了一个单元测试，简单地添加一个`META-INF/MANIFEST.MF`并没有问题。@lenomon 建议你尝试修改这个单元测试复现问题。或者你有能上传上来的zip包能复现问题也行。

**Comment by lenomon** [comment]
[plugin-debug.zip](https://github.com/Tencent/Shadow/files/4379412/plugin-debug.zip)
我把这个有问题的包上传了。
问题场景：
在插件中用module导入了腾讯短视频的aar库，打包就出这个问题了。
不导入这个的时候是没问题的。感觉是否跟打包有问题。
 @shifujun

**Comment by lenomon** [comment]
[plugin-debug.zip](https://github.com/Tencent/Shadow/files/4379563/plugin-debug.zip)
这个是从maven中打的正常的包。 

大佬，帮忙看看。我是真没找到问题在哪儿。 @shifujun 
下面的是在maven插件工程上，加了短视频sdk的工程代码。
[video-plugin.zip](https://github.com/Tencent/Shadow/files/4379583/video-plugin.zip)

**Comment by shifujun** [comment]
@lenomon 我测试了直接用CopySoBloc.copySo方法解压你上传的插件，没有复现问题。测试的机器是API 28的官方虚拟机。你可以用我刚添加的测试类自己试试能不能复现。如果异常时copySo方法里面抛出的，那这个测试用例应该完全能复现问题才对。

**Comment by lenomon** [comment]
我这边重新弄了个工程，发现没这个问题了。 
比较诡异。可能是工程版本导致打出的包有问题。 @shifujun

**Comment by shifujun** [comment]
如果还有问题，请参考
https://github.com/Tencent/Shadow/blob/dev/CONTRIBUTING.md#issue
再重新打开Issue。
