### ISSUE TITLE
插件内引用第三方对话框，宿主正常打开插件，但插件对话框功能报错

### ISSUE THREAD

**Issue by weiwenqiang** [Tencent/Shadow#277]
插件内引用第三方对话框无法打开，原生对话框可以使用，直接运行plugin，第三方对话框可以正常使用，打包成插件，在宿主中运行，就报这个错误，一开始我以为是androidX对话框不兼容，改写为本地androidX重写第三方全部代码，结果也无效
![图片](https://user-images.githubusercontent.com/16027666/77494686-4ecb3c00-6e81-11ea-8bec-75306936e132.png

2020-03-25 10:04:27.597 27342-27342/com.bdjw.armscore.hostapp D/StrictMode: StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V
        at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
        at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
        at java.lang.Class.getDeclaredMethodInternal(Native Method)
        at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
        at java.lang.Class.getMethod(Class.java:2063)
        at java.lang.Class.getMethod(Class.java:1690)
        at androidx.appcompat.widget.ViewUtils.makeOptionalFitsSystemWindows(ViewUtils.java:84)
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:827)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
        at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
        at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
        at android.app.Dialog.show(Dialog.java:302)
        at com.bdjw.armscore.dialogui.utils.ToolUtils.showDialog(ToolUtils.java:35)
        at com.bdjw.armscore.dialogui.bean.BuildBean.show(BuildBean.java:244)
        at com.bdjw.armscore.helpfeedback.activity.HelpFeedbackActivity.addImg(HelpFeedbackActivity.java:92)
        at com.bdjw.armscore.databinding.ActivityHelpFeedbackBindingImpl$OnClickListenerImpl.onClick(ActivityHelpFeedbackBindingImpl.java:140)
        at android.view.View.performClick(View.java:6615)
        at android.view.View.performClickInternal(View.java:6592)
        at android.view.View.access$3100(View.java:786)
        at android.view.View$PerformClick.run(View.java:25951)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6815)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
![微信截图_20200325101124](https://user-images.githubusercontent.com/16027666/77494835-d2852880-6e81-11ea-865f-67183350ad38.png)

**Comment by shifujun** [comment]
你的堆栈第一行不就写的很清楚了吗？严格模式检查到非法调用了。所以搜一下在哪开启的就好了啊。

https://github.com/Tencent/Shadow/blob/54b1bb3876620a91ac31eca1bc77177053ced913/projects/sample/source/sample-host/src/main/java/com/tencent/shadow/sample/host/HostApplication.java#L47
