### ISSUE TITLE
插件打包报错javassist.NotFoundException: android.preference.PreferenceFragment_

### ISSUE THREAD

**Issue by lenomon** [Tencent/Shadow#286]
插件打包报错了。看问题好像是替换时报错。找不到android.preference.PreferenceFragment_
请教下，这个要怎么处理。
`Caused by: java.lang.RuntimeException: javassist.NotFoundException: android.preference.PreferenceFragment_
        at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:117)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:106)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:85)

Caused by: javassist.NotFoundException: android.preference.PreferenceFragment_
        at javassist.ClassPool.get(ClassPool.java:445)
        at com.tencent.shadow.core.transform_kit.ReplaceClassName.checkAll(ReplaceClassName.kt:49)
        at com.tencent.shadow.core.transform_kit.AbstractTransform.checkReplacedClassHaveRightMethods(AbstractTransform.kt:135)
        at com.tencent.shadow.core.transform_kit.AbstractTransform.onCheckTransformedClasses(AbstractTransform.kt:101)
        at com.tencent.shadow.core.transform_kit.AbstractTransform.afterTransform(AbstractTransform.kt:75)
        at com.tencent.shadow.core.transform_kit.ClassTransform.transform(ClassTransform.kt:175)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)`

**Comment by shifujun** [comment]
没代码没法说是什么问题。你可以把代码push上来看看。

**Comment by shifujun** [comment]
#208 也是一样的错误没有代码。

**Comment by lenomon** [comment]
这个是我同事搞出来的问题，不知道他加了哪些库导致的。
 我自己的项目暂时还没复现。后期跟踪到我详细记录下。

**Comment by shifujun** [comment]
这个问题之前回复过了，我给忘了。其实提问前搜一下Issue应该能搜到的。

见#243
