### ISSUE TITLE
插件中的融云sdk初始化需要在主进程当中执行，请教下这个要怎么处理？

### ISSUE THREAD

**Issue by lenomon** [Tencent/Shadow#316]
下面是融云的加载代码，有判断进程名称。
private void initSDK(Context context, String appKey, boolean enablePush) {
        String current = SystemUtils.getCurrentProcessName(context);
        String mainProcessName = context.getPackageName();
        if (!mainProcessName.equals(current)) {
            RLog.w(TAG, "Init. Current process : " + current);
        } else {
            RLog.i(TAG, "init : " + current);
            mContext = context;
            RongContext.init(context);

![image](https://user-images.githubusercontent.com/4558207/80330370-945f9800-8877-11ea-9ee5-3fc421724657.png)

**Comment by shifujun** [comment]
把包含这个SDK的插件配置在主进程。如果这个SDK可以跨进程提供服务，那插件的其他部分可以另外配置在其他进程。插件的Service通过
https://github.com/Tencent/Shadow/blob/a0ea9d59443f538631e445a96dc9d51babbe9497/projects/sdk/dynamic/dynamic-loader/src/main/java/com/tencent/shadow/dynamic/loader/PluginLoader.java#L57
`bindPluginService`接口获得。

**Comment by lenomon** [comment]
您的意思是把pps配置到主进程吗？如下面这样：
<service
            android:name="com.huke.cloud.shadow.service.MainPluginProcessService" />

这个试过了。调用插件直接报错，提示好像跨进程调用不能这么做。

**Comment by shifujun** [comment]
是像你写的那样，把PPS配置到主进程。相应的也要把壳子Activity配置到主进程。不过更推荐使用#255 刚刚合入的Multiprocess支持。

如果还是不行，你也可以参考
https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md#issue
将可以复现问题的代码贴上来。

**Comment by lenomon** [comment]
ok了。PPS 和activity都配置到主进程。

**Comment by lenomon** [comment]
请教下，采用Multiprocess支持这种方式。我这边需要怎么做。

**Comment by lenomon** [comment]
现在碰到一个新问题，加载不同partKey的插件导致后加载的找不到插件，这么个场景：
1、插件A运行在独立进程中，加载成功。
2、运行插件B在主进程中，加载成功。
3、再次加载插件A，提示插件找不到。错误：
`45:56.805 2848-3141/com.huke.cloud.shadow.host E/com.tencent.shadow.dynamic.manager.BaseDynamicPluginManager: getPlugin exception:
    java.lang.NullPointerException: Attempt to read from field 'java.io.File com.tencent.shadow.core.manager.installplugin.InstalledPlugin$Part.pluginFile' on a null object reference
        at com.tencent.shadow.dynamic.manager.BaseDynamicPluginManager.getPlugin(BaseDynamicPluginManager.java:192)
        at com.tencent.shadow.dynamic.manager.UuidManagerBinder.onTransact(UuidManagerBinder.java:50)
        at android.os.Binder.transact(Binder.java:387)
        at com.tencent.shadow.dynamic.host.BinderUuidManager.getPlugin(BinderUuidManager.java:53)
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:80)
        at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:42)
        at android.os.Binder.transact(Binder.java:387)
        at com.tencent.shadow.dynamic.manager.BinderPluginLoader.loadPlugin(BinderPluginLoader.java:46)
        at com.huke.cloud.shadow.manager.FastPluginManager.loadPlugin(FastPluginManager.java:159)
        at com.huke.cloud.shadow.manager.FastPluginManager.convertActivityIntent(FastPluginManager.java:137)
        at com.huke.cloud.shadow.manager.FastPluginManager.startPluginActivity(FastPluginManager.java:129)
        at com.huke.cloud.shadow.manager.SamplePluginManager$1.run(SamplePluginManager.java:111)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)`

**Comment by shifujun** [comment]
> 3、再次加载插件A，提示插件找不到。
在哪个进程再次加载插件A？

你看我还得问这样的问题，这样交流效率很低，不如你把代码贴上来。

**Comment by lenomon** [comment]
插件A始终在独立进程加载，插件B始终主进程加载。 流程是：加载插件A退出，加载插件B退出，再加载插件A就失败，出现上面的错误。

主要代码没在sample上开发。

**Comment by lenomon** [comment]
大佬，我调试了下，摸清楚了一些情况。
场景：
1、两个插件都配置在主进程，使用同样的pps和壳子activity。
问题：
先加载插件A后，在尝试加载插件B，然后插件B就加载失败。
调试的一些信息：
1、在manager中尝试加载runtime和loader的时候，这里逻辑可能有些问题。
`private void loadPluginLoaderAndRuntime(String uuid, String partKey) throws RemoteException, TimeoutException, FailedException {
        if (mPpsController == null) {
            bindPluginProcessService(getPluginProcessServiceName(partKey));
            waitServiceConnected(10, TimeUnit.SECONDS);
        }
        loadRunTime(uuid);
        loadPluginLoader(uuid);
    }`

看上面的代码，mPpsController 在加载插件A后就不为空了。会调用父类的loadRunTime()方法。
看下面的图片，**可以发现mPpsController.getPpsStatus()中的状态还是插件A的状态，所以这里不会去加载插件B的runtime了**：
![image](https://user-images.githubusercontent.com/4558207/80455000-8a17c980-895d-11ea-8e57-1fc975455fbb.png)
 @shifujun

**Comment by shifujun** [comment]
UUID是需要保证一致，才能协同工作的。表示它们是同一个版本。

可以参考#265 的讨论。

**Comment by lenomon** [comment]
是所有插件的UUID都必须一致吗？

请教下，能否加载完插件A后，把插件A的信息再抹掉后，再来加载插件B。也就是说，每次只加载一个插件。

**Comment by shifujun** [comment]
设计如此。uuid是用来保证各部分是同一个版本，可以编译依赖的。将uuid设置成一样的就解决问题了。我们的业务也是这样实现的多插件加载。

**Comment by lenomon** [comment]
好的。感谢。
