### ISSUE TITLE
关于ShadowContext里对getResources的处理

### ISSUE THREAD

**Issue by Dovar66** [Tencent/Shadow#323]
我看ShadowContext重写了getResources方法，然后返回了自定义的MixResources对象。但是像vivo这种派生了VivoResources的，直接这样重写应该会遇到下面这个问题吧，你们线上没有遇到相关的崩溃吗？
下面是从其他文章里截取的一段错误信息：
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sdu.didi.psnger/com.didi.virtualapk.core.A$1}: java.lang.ClassCastException: android.content.res.Resources cannot be cast to android.content.res.VivoResources
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2196)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
  at android.app.ActivityThread.access$800(ActivityThread.java:140)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5143)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
  at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassCastException: android.content.res.Resources cannot be cast to android.content.res.VivoResources
  at android.app.ResourcesManager.getTopLevelResources(ResourcesManager.java:236)
  at android.app.ContextImpl.<init>(ContextImpl.java:2057)
  at android.app.ContextImpl.createActivityContext(ContextImpl.java:2008)
  at android.app.ActivityThread.createBaseContextForActivity(ActivityThread.java:2207)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2140)
  ... 11 more

文章地址：https://juejin.im/entry/5860ddd98d6d810065f2f59c

**Comment by shifujun** [comment]
首先我们线上是没有遇到这样的崩溃的。

这也跟Shadow的原理相关，如果实现没错的话，Shadow里面的MixResource应该是不会被ActivityThread等系统管理类直接访问到的。像你贴的这种堆栈，ActivityThread-> ContextImpl-> ResourcesManager，这都是系统类，Shadow不会hack任何系统类。所以它里面该是VivoResources就还是VivoResources。

只有插件中的代码会使用ShadowContext，才会拿到MixResources。

另外MixResources也不是理想的实现，正常应该就是调用系统的`packageManager.getResourcesForApplication`返回的Resources对象。这样它如果返回一个VivoResources，也不会修改它的类型。这里套了一层MixResources，是因为有一个暂时没解决的问题，应该是个bug。系统会拿到插件的Resources对象，问它要宿主Manifest中定义的app icon资源ID。这在插件Resources里肯定是找不到的。然后我们一时解决不了，就套了一层MixResources，在找不到资源时去宿主找一下。

**Comment by Dovar66** [comment]
多谢答疑，回复真快
