### ISSUE TITLE
启动插件时发生了错误。（Caused by: android.os.DeadObjectException）

### ISSUE THREAD

**Issue by DerekYanJ** [Tencent/Shadow#341]
您好 Android P 一加3T
`E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.yqy.test.shadow, PID: 19211
    java.lang.RuntimeException: 启动插件时发生了错误。
        at com.yqy.test.shadow.maneger.SamplePluginManager$startActivity$1.run(SamplePluginManager.kt:55)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1179)
        at com.tencent.shadow.dynamic.manager.BinderPluginLoader.loadPlugin(BinderPluginLoader.java:46)
        at com.yqy.test.shadow.maneger.FastPluginManager.loadPlugin(FastPluginManager.java:145)
        at com.yqy.test.shadow.maneger.FastPluginManager.convertActivityIntent(FastPluginManager.java:123)
        at com.yqy.test.shadow.maneger.FastPluginManager.startPluginActivity(FastPluginManager.java:115)
        at com.yqy.test.shadow.maneger.SamplePluginManager$startActivity$1.run(SamplePluginManager.kt:53)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) `

**Comment by DerekYanJ** [comment]
`    override fun onCreate() {
        super.onCreate()

        self = this
        context = this


//        detectNonSdkApiUsageOnAndroidP()
//        setWebViewDataDirectorySuffix()
        LoggerFactory.setILoggerFactory(AndroidLogLoggerFactory())

        if (isProcess(this, ":plugin")) {
            //在全动态架构中，Activity组件没有打包在宿主而是位于被动态加载的runtime，
            //为了防止插件crash后，系统自动恢复crash前的Activity组件，此时由于没有加载runtime而发生classNotFound异常，导致二次crash
            //因此这里恢复加载上一次的runtime
            DynamicRuntime.recoveryRuntime(this)
        }


        //复制asset插件到file中
        PluginHelper.getInstance().init(this)

        HostUiLayerProvider.init(this)

    }`

**Comment by shifujun** [comment]
DeadObjectException是指binder两侧进程有一侧死了。所以你看log应该看应该看另外一个进程。从你的log来看，你看到的是PM所在的进程抛出DeadObjectException了。那就应该去插件所在的进程，看看是什么Crash。

**Comment by DerekYanJ** [comment]
感谢回复，看着和sample一样，不明白哪一步出了问题
`2020-05-25 18:06:30.838 20816-20834/? E/AndroidRuntime: FATAL EXCEPTION: Binder:20816_3
    Process: com.yqy.test.shadow:plugin, PID: 20816
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/shadow/sample/host/lib/LoadPluginCallback;
        at com.yqy.test.loader.SimplePluginLoader.loadPlugin(SimplePluginLoader.kt:24)
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:81)
        at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:43)
        at android.os.Binder.execTransact(Binder.java:752)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.shadow.sample.host.lib.LoadPluginCallback" on path: DexPathList[[zip file "/data/user/0/com.yqy.test.shadow/files/ShadowPluginManager/UnpackedPlugin/plugin-maneger/29a45e2ce89fbbdff4b17e7535851d70/plugin-debug.zip/runtime-plugin-debug.apk", zip file "/system/framework/org.apache.http.legacy.boot.jar"],nativeLibraryDirectories=[/data/user/0/com.yqy.test.shadow/files/ShadowPluginManager/UnpackedPlugin/plugin-maneger/lib/7B4027D4-830D-47C2-B7B9-CB599E751311_lib, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tencent.shadow.dynamic.host.ApkClassLoader.loadClass(ApkClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.yqy.test.loader.SimplePluginLoader.loadPlugin(SimplePluginLoader.kt:24) 
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:81) 
        at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:43) 
        at android.os.Binder.execTransact(Binder.java:752) 
`

**Comment by shifujun** [comment]
可能是白名单没有添加吧。
https://github.com/Tencent/Shadow/blob/a0ea9d59443f538631e445a96dc9d51babbe9497/projects/sample/source/sample-plugin/sample-plugin-app/build.gradle#L49

还可以查apk里有没有这个类。还可以在PluginClassLoader里打断点。

**Comment by SunnyLy** [comment]
@DerekYanJ 你好，请问你这个是怎么解决的，我现在也遇到这个问题，白名单什么都添加了，就是报找不到类
