### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by DerekYanJ** [Tencent/Shadow#348]
插件中调用声网初始化时报错，host中则正常 
引用方式： implementation 'io.agora.rtm:rtm-sdk:1.2.2'和本地libs都试过还是会报同样的错
`dependencies {
    implementation project(':commonlib')
//    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.multidex:multidex:2.0.0'

    //声网语音和视频通话
    implementation 'io.agora.rtc:full-sdk:2.9.4'

    //声网实时消息
    implementation 'io.agora.rtm:rtm-sdk:1.2.2'
}
`

在Android Studio -》 Device FIle Explorer 中没有找到路径 /data/user/0/com.xh.friend/files/ShadowPluginManager/UnpackedPlugin/plugin-maneger/lib/C7660FB0-74CF-488C-A627-6D64685873B9_lib 下对应libagora-rtm-sdk-jni.so文件
 
但是agora-plugin-debug.apk 解压缩之后是可以找到libs 下libagora-rtm-sdk-jni.so文件的

具体报错信息如下：
`
2020-06-01 13:53:54.195 20532-20661/com.xh.friend:plugin E/AndroidRuntime: FATAL EXCEPTION: Thread-42
    Process: com.xh.friend:plugin, PID: 20532
    java.lang.UnsatisfiedLinkError: com.tencent.shadow.core.loader.classloaders.PluginClassLoader[DexPathList[[zip file "/data/user/0/com.xh.friend/files/ShadowPluginManager/UnpackedPlugin/plugin-maneger/30120f9cc52cac2af8ac7db19eb52100/plugin-debug.zip/agora-plugin-debug.apk", zip file "/system/framework/org.apache.http.legacy.boot.jar"],nativeLibraryDirectories=[/data/user/0/com.xh.friend/files/ShadowPluginManager/UnpackedPlugin/plugin-maneger/lib/C7660FB0-74CF-488C-A627-6D64685873B9_lib, /system/lib, /system/vendor/lib]]] couldn't find "libagora-rtm-sdk-jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at io.agora.common.AgoraServiceJNI.ensureNativeInitialized(AgoraServiceJNI.java:26)
        at io.agora.common.AgoraServiceJNI.<clinit>(AgoraServiceJNI.java:21)
        at io.agora.common.AgoraServiceJNI.nativeLog(Native Method)
        at io.agora.common.Logging.log(Logging.java:26)
        at io.agora.common.Logging.i(Logging.java:50)
        at io.agora.rtm.internal.RtmClientImpl.initRtmService(RtmClientImpl.java:115)
        at io.agora.rtm.internal.RtmClientImpl.<init>(RtmClientImpl.java:100)
        at io.agora.rtm.internal.RtmManager.createRtmInstance(RtmManager.java:20)
        at io.agora.rtm.RtmClient.createInstance(RtmClient.java:63)
        at com.xh.friend.agora.lib.message.agora.WorkerThread.ensureRtmClientReady(WorkerThread.kt:173)
        at com.xh.friend.agora.lib.message.agora.WorkerThread.run(WorkerThread.kt:159)
`

**Comment by shifujun** [comment]
https://github.com/Tencent/Shadow/blob/master/projects/sample/source/sample-manager/src/main/java/com/tencent/shadow/sample/manager/SamplePluginManager.java#L54-L60

有修改这里指定ABI吗？

**Comment by DerekYanJ** [comment]
您好 没有重写 getAbi() 方法
`package com.xh.friend.shadow.manager

import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.view.LayoutInflater
import com.tencent.shadow.dynamic.host.EnterCallback
import com.xh.friend.constant.Constant1.*
import java.util.concurrent.ExecutorService
import java.util.concurrent.Executors

class SamplePluginManager(val mCurrentContext: Context) : FastPluginManager(mCurrentContext) {

    private val executorService: ExecutorService = Executors.newSingleThreadExecutor()

    override fun getName(): String {
        return "plugin-maneger"
    }

    override fun getPluginProcessServiceName(partKey: String): String {
        return "com.tencent.shadow.sample.host.PluginProcessPPS"
    }

    override fun enter(context: Context, fromId: Long, bundle: Bundle, enterCallback: EnterCallback?) {
        if (fromId > 1000) {
            startActivity(context, bundle, enterCallback)
        } else {
            throw IllegalArgumentException("不认识的fromId:$fromId")
        }
    }

    private fun startActivity(context: Context, bundle: Bundle, callback: EnterCallback?) {
        val pluginZipPath = bundle.getString(KEY_PLUGIN_ZIP_PATH)
        val pluginPartKey = bundle.getString(KEY_PLUGIN_PART_KEY)
        val activityClass = bundle.getString(KEY_ACTIVITY_CLASSNAME)
        val extraBundle = bundle.getBundle(KEY_EXTRA_KEY)

        requireNotNull(pluginZipPath)
        requireNotNull(pluginPartKey)
        requireNotNull(activityClass)

        if (callback != null) {
            val view = LayoutInflater.from(mCurrentContext).inflate(R.layout.view_plugin_manager_loading, null)
            callback.onShowLoadingView(view)
        }

        executorService.execute {
            try {
                val installPlugin = installPlugin(pluginZipPath, null, true)
                val intent = Intent().setComponent(ComponentName(context, activityClass))
                extraBundle?.let(intent::putExtras)
                startPluginActivity(context, installPlugin, pluginPartKey, intent)
            } catch (e: Exception) {
                throw RuntimeException("启动插件时发生了错误。", e)
            } finally {
                callback?.onCloseLoadingView()
                callback?.onEnterComplete()
            }
        }

    }

}`

**Comment by shifujun** [comment]
这里Shadow目前是需要在这里手工指定所需解压的so的ABI是哪个的。而Android系统是自动判断当前平台ABI和apk中最适合的ABI解压的。

**Comment by DerekYanJ** [comment]
重写后解决了 谢谢

**Comment by hpuhsp** [comment]
```
    /**
     * @return 宿主so的ABI。插件必须和宿主使用相同的ABI。
     */
    @Override
    public String getAbi() {
        return "armeabi-v7a";
    }
```
重写后在一些手机上依然报：java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.plugin.test/files/ShadowPluginManager/UnpackedPlugin/multi-process-manager/lib/class java.util.UUID_lib/libsoundtouch.so" is 32-bit instead of 64-bit

**Comment by Afaquejaya** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.astroprotips, PID: 23909
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.android.astroprotips-Fp6bmSHDGiwFCYhPCFJe6w==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.astroprotips-Fp6bmSHDGiwFCYhPCFJe6w==/lib/arm64, /data/app/com.android.astroprotips-Fp6bmSHDGiwFCYhPCFJe6w==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libagora-rtm-sdk-jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at io.agora.common.AgoraServiceJNI.ensureNativeInitialized(AgoraServiceJNI.java:26)
        at io.agora.common.AgoraServiceJNI.<clinit>(AgoraServiceJNI.java:21)
        at io.agora.common.AgoraServiceJNI.nativeLog(Native Method)
        at io.agora.common.Logging.log(Logging.java:26)
        at io.agora.common.Logging.i(Logging.java:50)
        at io.agora.rtm.internal.CommonUtility.<init>(CommonUtility.java:99)
        at io.agora.rtm.internal.RtmManager.createRtmInstance(RtmManager.java:23)
        at io.agora.rtm.RtmClient.createInstance(RtmClient.java:67)
        at com.android.astroprotips.ui.Chat.rtmtutorial.ChatManager.init(ChatManager.java:38)
        at com.android.astroprotips.ui.Chat.rtmtutorial.AGApplication.onCreate(AGApplication.java:20)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6582)
        at android.app.ActivityThread.access$1400(ActivityThread.java:224)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/Process: Sending signal. PID: 23909 SIG: 9

```

getting this error please help me to fix this.
