### ISSUE TITLE
主进程使用插件问题

### ISSUE THREAD

**Issue by MonchChen** [Tencent/Shadow#358]
因业务需要，将插件设置为主进程使用，但插件加载完成后，因ClassLoader被替换，导致后续Host查找一些Class会异常，例如：
`
java.lang.IllegalAccessError: Illegal class access: 'androidx.core.widget.NestedScrollView$SavedState' attempting to access 'androidx.core.widget.NestedScrollView$SavedState$1' (declaration of 'androidx.core.widget.NestedScrollView$SavedState' appears in /data/app/package-6U9u3bMvmQ-QaWV6AmQAKA==/base.apk)
        at androidx.core.widget.NestedScrollView$SavedState.<clinit>(NestedScrollView.java:2087)
        at androidx.core.widget.NestedScrollView.onSaveInstanceState(NestedScrollView.java:2056)
        at android.view.View.dispatchSaveInstanceState(View.java:19088)
        at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:3859)
        at android.view.View.saveHierarchyState(View.java:19071)
        at androidx.fragment.app.FragmentManagerImpl.saveFragmentViewState(FragmentManager.java:2897)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1530)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
`

大佬能想到什么解决办法吗？感谢！！

**Comment by shifujun** [comment]
首先DynamicRuntime修改ClassLoader的parent这个操作并不是Shadow所必须的。runtime可以打包在宿主内，只是方法数增量会有点大。

然后DynamicRuntime也不应该引起这个异常，特别是跟`androidx`这个包相关。所以我认为这里跟“ClassLoader替换”应该不相关。

看起来像是插件设置了`hostWhiteList`白名单放过了`androidx`这个包导致的相关问题。

总之，只是看看这些堆栈很难定位问题。你最好还是基于source/sample做最简单的修改复现这个问题，然后push上来给我试试。参考：https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md#issue

**Comment by MonchChen** [comment]
好的，我写个例子尝试复现一下这个问题
