### ISSUE TITLE
java.lang.VerifyError: Rejecting class that attempts to sub-type erroneous class

### ISSUE THREAD

**Issue by shifujun** [Tencent/Shadow#380]
业务中遇到一例这样情况：
```
java.lang.VerifyError: Rejecting class xxxxx that attempts to sub-type erroneous class yyyyy (declaration of 'xxxxx' appears in /data/user/0/asdfasfd/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/asdfasdf/plugin-debug.zip/asdfasdf-plugin-app-debug.apk) 
```

从这个堆栈中难以发现问题的直接原因。

这是因为实际上yyyyy这个父类本身加载时就会出错，而虚拟机在这种子类继承父类的场景时遇到这个错误没有打印出详细的根异常。

定位问题时，只需修改yyyyy这个父类，尝试直接new这个父类即可看到具体的问题。一般是一些类型运行时和编译时预期的不一致造成的，比如Application类型变成了ShadowApplication类型，而一部分代码在宿主中没有进行Transform。

**Comment by zdy793410600** [comment]
你好，我这里也遇到这个问题了，说一下场景吧，这个 yyyy 类是个基类Activity，宿主和插件的Activity都是继承这个基类的，在宿主中运行是没问题的，但是打包到插件里，启动插件Activity就会报这个错。

**Comment by shifujun** [comment]
> 你好，我这里也遇到这个问题了，说一下场景吧，这个 yyyy 类是个基类Activity，宿主和插件的Activity都是继承这个基类的，在宿主中运行是没问题的，但是打包到插件里，启动插件Activity就会报这个错。

那你没有new yyyy看看吗？

**Comment by zdy793410600** [comment]
> > 你好，我这里也遇到这个问题了，说一下场景吧，这个 yyyy 类是个基类Activity，宿主和插件的Activity都是继承这个基类的，在宿主中运行是没问题的，但是打包到插件里，启动插件Activity就会报这个错。
> 
> 那你没有new yyyy看看吗？

在宿主中new了，是没问题的，不会崩溃。

**Comment by zdy793410600** [comment]
> > 但是打包到插件里，启动插件Activity就会报这个错。
> 
> 是插件里报错，为什么在宿主中new呢？

嗯，我先去插件里写个空的Activity尝试去new这个yyyy试试，请问您方便加一下微信么？我从腾讯内部微信里没找到你。

**Comment by zdy793410600** [comment]
> > 但是打包到插件里，启动插件Activity就会报这个错。
> 
> 是插件里报错，为什么在宿主中new呢？

直接new yyyy报错也是一样的：
 java.lang.VerifyError: Rejecting class XXXXActivity that attempts to sub-type erroneous class androidx.fragment.app.FragmentActivity (declaration of 'XXXXActivity' appears in /data/data/***/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/79b88705e00654bdd69b24f45c7c3472/****.apk)  
     trace : java.lang.VerifyError: Rejecting class XXXXActivity that attempts to sub-type erroneous class androidx.fragment.app.FragmentActivity (declaration of 'XXXXActivity' appears in /data/data/***/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/79b88705e00654bdd69b24f45c7c3472/****.apk)
        at TestActivity.onCreate(TestActivity.java:19)
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(ShadowActivityDelegate.kt:144)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.VerifyError: Verifier rejected class androidx.fragment.app.FragmentActivity: android.view.View androidx.fragment.app.FragmentActivity.onCreateView(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) failed to verify: android.view.View androidx.fragment.app.FragmentActivity.onCreateView(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet): [0xA] returning 'Reference: android.view.View', but expected from declaration 'Reference: android.view.View'
     android.view.View androidx.fragment.app.FragmentActivity.onCreateView(java.lang.String, android.content.Context, android.util.AttributeSet) failed to verify: android.view.View androidx.fragment.app.FragmentActivity.onCreateView(java.lang.String, android.content.Context, android.util.AttributeSet): [0xB] returning 'Reference: android.view.View', but expected from declaration 'Reference: android.view.View' (declaration of 'androidx.fragment.app.FragmentActivity' appears in /data/data/***/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/79b88705e00654bdd69b24f45c7c3472/****.apk)
    	... 15 more
    java.lang.VerifyError: Verifier rejected class androidx.fragment.app.FragmentActivity: android.view.View androidx.fragment.app.FragmentActivity.onCreateView(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) failed to verify: android.view.View androidx.fragment.app.FragmentActivity.onCreateView(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet): [0xA] returning 'Reference: android.view.View', but expected from declaration 'Reference: android.view.View'

**Comment by zdy793410600** [comment]
> 前面说的yyyyy 对应你的错误信息中的是`androidx.fragment.app.FragmentActivity`，你应该尝试`new androidx.fragment.app.FragmentActivity`。

这个报错需要怎么处理？
 java.lang.VerifyError: Verifier rejected class androidx.fragment.app.FragmentActivity: android.view.View androidx.fragment.app.FragmentActivity.onCreateView(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) failed to verify: android.view.View androidx.fragment.app.FragmentActivity.onCreateView(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet): [0xA] returning 'Reference: android.view.View', but expected from declaration 'Reference: android.view.View'
     android.view.View androidx.fragment.app.FragmentActivity.onCreateView(java.lang.String, android.content.Context, android.util.AttributeSet) failed to verify: android.view.View androidx.fragment.app.FragmentActivity.onCreateView(java.lang.String, android.content.Context, android.util.AttributeSet): [0xB] returning 'Reference: android.view.View', but expected from declaration 'Reference: android.view.View' (declaration of 'androidx.fragment.app.FragmentActivity' appears in /data/data/***/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/e08fa19a123dff1501df84517a67fa73/***.apk)
        at TestActivity.onCreate(TestActivity.java:20)
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(ShadowActivityDelegate.kt:144)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by shifujun** [comment]
你这个堆栈只有一个exception吗？这是root cause？  

另外我猜这可能是因为宿主中也打包了androidx，并且你的测试环境是Android P以上的。这种情况下系统的JVM有优化，不会去加载插件的实现。

**Comment by shifujun** [comment]
就是DexClassLoader加载不了和宿主中同名的类。这种情况下，最好不要重复打包，或者配置好Proguard。

**Comment by zdy793410600** [comment]
这就存在一个问题，比如插件和宿主使用的封装好的公共库，插件也将它打包进去了，类名相同的，只会去加载宿主的，如果宿主对于公共库改动了，插件其实是不知道的，有可能引发崩溃吧。

**Comment by shifujun** [comment]
所以要用proguard配置好不会重复的包名。

**Comment by zdy793410600** [comment]
我感觉不是你说的这个问题，我写了个demo，插件和宿主的Activity都是继承了一个TestActivity，并且TestActivity打包到插件里了，启动也是没问题的。

**Comment by shifujun** [comment]
所以没代码只能猜。最好还是在sample上复现问题，把代码传上来。

**Comment by zdy793410600** [comment]
> 所以没代码只能猜。最好还是在sample上复现问题，把代码传上来。

继承普通Activity的可以启动，继承FragmentActivity的启动不了，很奇怪，有可能会和分包有关系么？我们这个插件方法数超了，我给做了分包。

**Comment by shifujun** [comment]
从前面的报错信息来看，只能怀疑"android.view.View"由不同的ClassLoader加载的。但我也想不到怎么构造出来这种情况。因为这个类应该在BootClassLoader里，怎么都不应该有第二个。

你可以尝试把你项目中的其他代码都分批删除，直到只保留androidx依赖，如果还能复现问题，代码就应该可以传上来了。

**Comment by gdannyliao** [comment]
遇到同样的崩溃，new 对应的类后出现如下信息：
java.lang.VerifyError: Verifier rejected class yyyy.Activity: void yyyy.Activity.onCreate(android.os.Bundle) failed to verify: void yyyy.Activity.onCreate(android.os.Bundle): [0xC] 'this' argument 'Precise Reference: java.lang.reflect.Field' not instance of 'Unresolved Reference: java.lang.reflect.AccessibleObject' (declaration of 'yyyy.Activity' appears in path!classes2.dex)
经查询是安卓12初期的一个bug

**Comment by mowenGithub** [comment]
> 

所以你解决了么，是android12里面有个bug会导致这样

**Comment by doyer3112** [comment]
android 12里面部分机型遇到这个问题
