### ISSUE TITLE
处理androidx.core.graphics.TypefaceCompatApi29Impl时出错

### ISSUE THREAD

**Issue by yiwanganjing** [Tencent/Shadow#411]
处理androidx.core.graphics.TypefaceCompatApi29Impl时出错:javassist.CannotCompileException: createFromFontFamilyFilesResourceEntry (Landroid/content/ConLandroidx/core/content/res/FontResourcesParserCompat$FontFamilyFilesResourceEntry;Landroid/content/res/Resources;I)Landroid/graphics/Typeface; in androidx.core.graphics.TypefaceCompatApi29Impl: failed to resolve types
Task :app:transformClassesWithShadowTransformForDebug in app Finished

Caused by: javassist.CannotCompileException: createFromFontFamilyFilesResourceEntry (Landroid/content/Context;Landroidx/core/content/res/FontResourcesParserCompat$FontFamilyFilesResourceEntry;Landroid/content/res/Resources;I)Landroid/graphics/Typeface; in androidx.core.graphics.TypefaceCompatApi29Impl: failed to resolve types
        at javassist.CodeConverter.doit(CodeConverter.java:542)
        at javassist.CtClassType.instrument(CtClassType.java:1481)
        at com.tencent.shadow.core.transform.specific.InstrumentationTransform$setup$2.transform(InstrumentationTransform.kt:57)
        at com.tencent.shadow.core.transform_kit.AbstractTransformManager.fireAll(AbstractTransformManager.kt:41)
        at com.tencent.shadow.core.transform_kit.AbstractTransform.onTransform(AbstractTransform.kt:61)
        at com.tencent.shadow.core.transform_kit.ClassTransform.transform(ClassTransform.kt:173)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:284)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:247)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:106)
        ... 92 more

**Comment by shifujun** [comment]
你用的这个`androidx`的版本需要compileSDK的版本至少29才行。

你要么降低点androidx的版本，要么把compileSDK升到29。

第三方库里存在一些设计上就不需要使用的类，没法重新编译，我需要考虑下怎么在Transform里自动兼容这种情况。

**Comment by shifujun** [comment]
#412 合入的话，你的业务构建应该就不用任何修改了。我测试在28版本sdk下编译androidx的1.3.1版本能复现问题。修复后不会复现问题了。

**Comment by shifujun** [comment]
额，修复失败了。单元测试是真好用，测出来了我的修复问题。。。我再想想吧。

需要一个高效的办法确定一个类是否能重新编译。

失败的case是调用了Fragment.startActivity的类，可能根本没引用Fragment类型，而是引用了Fragment的子类。

**Comment by yiwanganjing** [comment]
我现在确实改了版本就没问题了，等你改好了我更新下试试

**Comment by shifujun** [comment]
已经合入了。再试试吧。我认为我这次是修复了一个一直存在的兼容性问题。
