### ISSUE TITLE
编写的插件，通过框架启动，启动不起来，报错误Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by weeeeeeeeeeeei** [Tencent/Shadow#415]
2020-09-23 14:48:50.543 17194-17194/com.sample.host E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sample.host:plugin, PID: 17194
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sample.host/com.tencent.shadow.runtime.PluginDefaultProxyActivity}: java.lang.RuntimeException: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3312)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3461)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2048)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
     Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(Unknown Source:406)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3287)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3461) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2048) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:227) 
        at android.app.ActivityThread.main(ActivityThread.java:7582) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953) 
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at com.example.demo_mt.MainActivity.onCreate(MainActivity.java:52)
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(Unknown Source:397)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84) 
        at android.app.Activity.performCreate(Activity.java:7893) 
        at android.app.Activity.performCreate(Activity.java:7880) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3287) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3461) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2048) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:227) 
        at android.app.ActivityThread.main(ActivityThread.java:7582) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

**Comment by VirgCode** [comment]
换成主题也是还是这个错误，不知道啥情况

**Comment by shifujun** [comment]
这应该是系统检查的行为。原理上插件Activity不是一个真的Activity，它只是宿主中注册的壳子Activity代码的一部分。所以如果插件想用AppCompat的话，需要在宿主中注册的壳子也设置AppCompat的主题才行。

**Comment by VirgCode** [comment]
找了一下午问题，发现是插件项目中依赖'androidx.appcompat:appcompat:1.2.0'导致的，依赖'androidx.appcompat:appcompat:1.1.0'不报错，应该是AndroidX下不同的appcompatActivity的导致的问题，具体的报错机制，之后再确认一下问题

**Comment by noproxy** [comment]
在 androidx.appcompat:appcompat:1.2.0中有这样一处代码

https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/appcompat/appcompat/src/main/java/androidx/appcompat/app/AppCompatDelegateImpl.java#465
```
if (needsThemeRebase) {
    // Attempt to rebase the old theme within the new configuration. This will only
    // work on SDK 23 and up, but it's unlikely that we're keeping the base theme
    // anyway so maybe nobody will notice. Note that calling getTheme() will clone
    // the base context's theme into the wrapped context's theme.
    ResourcesCompat.ThemeCompat.rebase(wrappedContext.getTheme());
}
```

这个rebase操作导致了这个错误

**Comment by Shinyshine90** [comment]
> 在 androidx.appcompat:appcompat:1.2.0中有这样一处代码
> 
> https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/appcompat/appcompat/src/main/java/androidx/appcompat/app/AppCompatDelegateImpl.java#465
> 
> ```
> if (needsThemeRebase) {
>     // Attempt to rebase the old theme within the new configuration. This will only
>     // work on SDK 23 and up, but it's unlikely that we're keeping the base theme
>     // anyway so maybe nobody will notice. Note that calling getTheme() will clone
>     // the base context's theme into the wrapped context's theme.
>     ResourcesCompat.ThemeCompat.rebase(wrappedContext.getTheme());
> }
> ```
> 
> 这个rebase操作导致了这个错误

怎么分析的呢？ 求解

**Comment by sxhgit** [comment]
可以在自己的 Activity 中重写attachBaseContext方法，在这个方法里设置baseContext的 Theme
override fun attachBaseContext(newBase: Context?) {
        newBase?.setTheme(R.style.Theme_AppCompat_Light_NoActionBar)
        super.attachBaseContext(newBase)
    }
