### ISSUE TITLE
通过c++层反射java层，找不到构造函数

### ISSUE THREAD

**Issue by o0starshine0o** [Tencent/Shadow#441]
# 前提
今天在集成广点通时（把广点通作为插件）遇到一个报错，完整的log如下
```bash
java.lang.NoSuchMethodError: no non-static method "Lcom/qq/e/comm/plugin/b/n;.<init>(Landroid/app/Service;)V"
11-16 16:15:52.212 28904-28904/*** W/System.err:     at yaq.gdtadv.getobjresult(Native Method)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.qq.e.comm.plugin.POFactoryImpl.getAPKDownloadServiceDelegate(Unknown Source)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.qq.e.comm.DownloadService.a(Unknown Source)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.qq.e.comm.DownloadService.onStartCommand(Unknown Source)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.tencent.shadow.core.loader.managers.PluginServiceManager.startPluginService()
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.tencent.shadow.core.loader.managers.ComponentManager.startService()
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.tencent.shadow.core.runtime.ShadowContext.startService(ShadowContext.java:224)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.qq.e.comm.plugin.b.m.b(Unknown Source)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at yaq.gdtadv.getVresult(Native Method)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.qq.e.comm.plugin.s.e.a(Unknown Source)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at yaq.gdtadv.getVresult(Native Method)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.qq.e.comm.plugin.s.e.a(Unknown Source)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at yaq.gdtadv.getVresult(Native Method)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.qq.e.comm.plugin.rewardvideo.i.l(Unknown Source)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.qq.e.comm.plugin.rewardvideo.i.loadAD(Unknown Source)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.qq.e.comm.plugin.rewardvideo.h.loadAD(Unknown Source)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.qq.e.ads.rewardvideo.RewardVideoAD.loadAD(Unknown Source)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.qq.e.ads.rewardvideo.RewardVideoAD$1$1.run(Unknown Source)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at android.os.Handler.handleCallback(Handler.java:815)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at android.os.Looper.loop(Looper.java:207)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5981)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
```

简单说就是找不到方法(构造方法)：
```kotlin
com.qq.e.plugin.b.n(service : android.app.Service)
```

原因是`Shadow`在做字节码转换的时候，把所有的`android.app.Service`换成了`com.tencent.shadow.core.runtime.ShadowService`
所以新的方法是
```kotlin
com.qq.e.plugin.b.n(service: com.tencent.shadow.core.runtime.ShadowService)
```

----

# 重点来了
注意堆栈的倒数第二步是`yaq.gdtadv.getobjresult(Native Method)`这是个native的方法，估计是直接根据方法签名来找的，他直接反射`android.app.Service`作为参数的构造方法，这肯定是找不到的，毕竟方法签名错了

关键是java层传递给native层的是`ShadowService`，而native层反射的是`android.app.Service`，估计native层反射完成后是需要调用这个构造方法的，会把`ShadowService`给传递给java层；

----

# 补充
因为这是在`DownloadService`中的，目测激励视频会调用到这里，进而下载apk，如果通过黑科技不让`DownloadService`启动，apk的下载估计就是问题了，同样也会影响到广告效果，跟不用提绕过native层会不会导致被判定为广告欺诈了；

----

# 请教，求助

请教各位大神，有什么办法可以解决这样的问题？

**Comment by shifujun** [comment]
解决思路上，我觉得要适配这种反射Service的行为，就只能不对这个Service进行插件化修改了。如果可以的话，最好宿主里放一个正常的Service，去跟反射的逻辑适配。如果能够修改这个正常的Service逻辑，可以让这个逻辑再去跟另外的插件Service互动完成动态的行为。

**Comment by o0starshine0o** [comment]
大神思路果然给力！我理解的是在宿主做一个能让native反射的类，通过这个类走aidl的方式和插件的Service进行交互。
应该是个很给力的思路，我去试一下，有结果了在这里反馈。

感谢

**Comment by o0starshine0o** [comment]
大神，之前的方案可行，但是又遇到另外一个问题：
```bash
E/art: JNI ERROR (app bug): attempt to pass an instance of com.qq.e.comm.DownloadService as argument 1 to void com.qq.e.comm.plugin.b.n.<init>(android.app.Service)
```

native层拿到构造函数后就开始把`DownloadService`（这里的`DownloadService`其实已经是被转化为`ShadowService`了）作为参数传递给了java层（也就是宿主）

我尝试把构造函数改成`class n(service:Any)`但是方法签名不对，native层还是找不到；
也尝试构造函数重载，但是明显不可以，毕竟native层指定了构造函数；

难道这又到了山穷水尽的时候？实在是没有思路了，求大神帮忙。

**Comment by shifujun** [comment]
不是说让Native层（反射的代码）不要跟插件交互吗？它怎么会拿到DownloadService（ShadowService）呢？

**Comment by o0starshine0o** [comment]
是插件里面广点通的SDK调用了自己的so文件，自己写的代码木有调用native层。
```bash
11-16 16:15:52.212 28904-28904/*** W/System.err:     at yaq.gdtadv.getobjresult(Native Method)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.qq.e.comm.plugin.POFactoryImpl.getAPKDownloadServiceDelegate(Unknown Source)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.qq.e.comm.DownloadService.a(Unknown Source)
11-16 16:15:52.212 28904-28904/*** W/System.err:     at com.qq.e.comm.DownloadService.onStartCommand(Unknown Source)
```

如果不让native层和插件交互，那就需要改动广点通的SDK了，如果改动了广点通的SDK，不让他和native层交互，可能会触发广告作弊的规则了。

**Comment by shifujun** [comment]
噢，是广点通SDK带了一个DownloadService是吧？这种情况确实是不能直接兼容，根本问题是Shadow不兼容反射Activity、Service等代码。

那就是要改动这个SDK。我是想可以先尝试把这个Service从SDK里分离出来，单独打包到宿主里。如果它内部的耦合太严重了，就不好修改了。可能只能把它整个打包到宿主里了，考虑到安装包大小的关系，你可以把它的so单独提出来，动态下载之后再初始化它。这些就不用Shadow参与了。

**Comment by o0starshine0o** [comment]
谢谢大神，如果广点通SDK不能包含在插件中，就只能先暂时搁置了。
如果以后这边有其他方法再来更新。

**Comment by o0starshine0o** [comment]
可以考虑修改so文件，也就是修改C++代码。

让C++代码反射时调用的函数签名从之前的`Landroid/app/Service;`，变成`Lcom.tencent.shadow.core.runtime.ShadowService;`

这一步我还没时间是尝试，如果有结果了，可以告诉我一下，谢谢。
