### ISSUE TITLE
OPPO Android 10上插件运行不起来，启动就crash

### ISSUE THREAD

**Issue by milesx6** [Tencent/Shadow#442]
OPPO RENO3、RENO2必现，sample-host启动后，点击启动插件出现loading，然后进程就crash了。
下面是warn级别以上log：

2020-11-19 16:13:07.741 29949-30650/? E/RegService_OppoDmykTelephonyManager: getPrimarySlotId: no SIM.
2020-11-19 16:13:07.837 29949-30660/? W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
2020-11-19 16:13:07.864 651-30664/? E/ResolverController: No valid NAT64 prefix (112, <unspecified>/0)
2020-11-19 16:13:07.869 29949-30660/? W/System: ClassLoader referenced unknown path: system/framework/mediatek-cta.jar
2020-11-19 16:13:08.726 720-764/? E/SurfaceFlinger: this:0x75339035b0 produecer:0x7548022340 MonitoredProducer dtor ptr 0x7533fe8000
2020-11-19 16:13:08.727 720-764/? E/SurfaceFlinger: this:0x75339035b0 producer:0x7548022340 MonitoredProducer dtor refs 0x7533fec1e0
2020-11-19 16:13:08.727 720-764/? W/BufferQueueProducer: [com.tencent.shadow.sample.host/com.tencent.shadow.sample.host.PluginLoadActivity#0](core:0x7533efb800,this:0x7548022340,id:3456,api:1,p:-1,c:-1) Producer:0x7548022340 core:0x7533efb800 ~BufferQueueProducer dtor
2020-11-19 16:13:08.727 720-764/? W/BufferQueueCore: [com.tencent.shadow.sample.host/com.tencent.shadow.sample.host.PluginLoadActivity#0](this:0x7533efb800,id:3456,api:1,p:-1,c:-1) this:0x7533efb800 ~BufferQueueCore dtor called
2020-11-19 16:13:08.766 27523-27523/? W/adbd: timeout expired while flushing socket, closing
2020-11-19 16:13:08.769 1305-9205/? W/ColorAccessControlManagerService: notifyZoomWindowExit: stack=ActivityStack{88e1496 stackId=287 type=standard mode=fullscreen visible=true translucent=false, 1 tasks}  windowMode=1  topActivity=ActivityRecord{296dc29 u0 com.tencent.shadow.sample.host/.PluginLoadActivity t7826}  toFullScreen = true
2020-11-19 16:13:08.776 3813-29209/? E/hypnusd: same package name, skip
2020-11-19 16:13:08.776 1305-9205/? W/ColorAccessControlManagerService: notifyZoomWindowExit: stack=ActivityStack{88e1496 stackId=287 type=standard mode=fullscreen visible=true translucent=false, 1 tasks}  windowMode=1  topActivity=ActivityRecord{296dc29 u0 com.tencent.shadow.sample.host/.PluginLoadActivity t7826}  toFullScreen = true
2020-11-19 16:13:08.778 3813-3857/? E/horae: setForegroundPackage, mChargingStateMachine is null!
2020-11-19 16:13:08.785 29634-29634/com.tencent.shadow.sample.host W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@34f0e93
2020-11-19 16:13:08.863 30363-30363/com.tencent.shadow.sample.host E/ple.host:plugi: Unknown bits set in runtime_flags: 0x8000
2020-11-19 16:13:08.898 30363-30363/com.tencent.shadow.sample.host E/---wyf---: ConstraintLayout:dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.tencent.shadow.sample.host-t0gW0PHpJMNtVJh6wF8uUA==/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.shadow.sample.host-t0gW0PHpJMNtVJh6wF8uUA==/lib/arm64, /system/lib64, /system/product/lib64]]]
2020-11-19 16:13:08.910 30363-30695/com.tencent.shadow.sample.host E/plugin_time: buildClassLoader sample-plugin-app start
2020-11-19 16:13:08.911 30363-30695/com.tencent.shadow.sample.host W/ple.host:plugi: Unsupported class loader
2020-11-19 16:13:08.912 30363-30697/com.tencent.shadow.sample.host E/plugin_time: buildPluginInfo sample-plugin-app start and wait
2020-11-19 16:13:08.913 30363-30696/com.tencent.shadow.sample.host E/plugin_time: getPackageInfo sample-plugin-app start
2020-11-19 16:13:08.913 30363-30698/com.tencent.shadow.sample.host E/plugin_time: buildPackageManager sample-plugin-app start and wait
2020-11-19 16:13:08.913 30363-30699/com.tencent.shadow.sample.host E/plugin_time: buildResources sample-plugin-app start and wait
2020-11-19 16:13:08.913 30363-30700/com.tencent.shadow.sample.host E/plugin_time: buildApplication sample-plugin-app start and wait
2020-11-19 16:13:08.913 30363-30702/com.tencent.shadow.sample.host E/plugin_time: buildRunningPlugin sample-plugin-app start and wait
2020-11-19 16:13:08.913 30363-30695/com.tencent.shadow.sample.host W/ple.host:plugi: Skipping duplicate class check due to unsupported classloader
2020-11-19 16:13:08.915 30363-30695/com.tencent.shadow.sample.host E/plugin_time: buildClassLoader sample-plugin-app end:5
2020-11-19 16:13:09.008 1305-1334/? W/Watchdog: !@WatchDog_5149
2020-11-19 16:13:09.021 30363-30696/com.tencent.shadow.sample.host W/SystemConfig: No directory /product_services/etc/sysconfig, skipping
2020-11-19 16:13:09.021 30363-30696/com.tencent.shadow.sample.host W/SystemConfig: No directory /product_services/etc/permissions, skipping
2020-11-19 16:13:09.021 30363-30696/com.tencent.shadow.sample.host W/SystemConfig: No directory /system/etc/oppoOperatorGroupFeatures, skipping
2020-11-19 16:13:09.021 30363-30696/com.tencent.shadow.sample.host W/SystemConfig: No directory /system/etc/oppoOperatorFeatures, skipping
2020-11-19 16:13:09.021 30363-30696/com.tencent.shadow.sample.host W/SystemConfig: No directory /system/etc/oppoRegionMarkFeatures, skipping
2020-11-19 16:13:09.021 30363-30696/com.tencent.shadow.sample.host W/SystemConfig: No directory /system/etc/oppoEuexCountryFeatures, skipping
2020-11-19 16:13:09.022 30363-30696/com.tencent.shadow.sample.host W/System: ClassLoader referenced unknown path: /system/framework/mediatek-cta.jar
2020-11-19 16:13:09.022 30363-30696/com.tencent.shadow.sample.host W/CtaManagerFactory: CtaManagerFactoryImpl not found
2020-11-19 16:13:09.032 30363-30696/com.tencent.shadow.sample.host E/plugin_time: getPackageInfo sample-plugin-app lock
2020-11-19 16:13:09.032 30363-30696/com.tencent.shadow.sample.host E/plugin_time: getPackageInfo sample-plugin-app :119
2020-11-19 16:13:09.032 30363-30699/com.tencent.shadow.sample.host E/plugin_time: buildResources sample-plugin-app start
2020-11-19 16:13:09.032 30363-30698/com.tencent.shadow.sample.host E/plugin_time: buildPackageManager sample-plugin-app start
2020-11-19 16:13:09.032 30363-30698/com.tencent.shadow.sample.host E/plugin_time: buildPackageManager sample-plugin-app :0
2020-11-19 16:13:09.033 30363-30697/com.tencent.shadow.sample.host E/plugin_time: buildPluginInfo sample-plugin-app start
2020-11-19 16:13:09.034 30363-30697/com.tencent.shadow.sample.host E/plugin_time: buildPluginInfo sample-plugin-app :1
2020-11-19 16:13:09.034 30363-30699/com.tencent.shadow.sample.host E/plugin_time: buildResources sample-plugin-app :2
2020-11-19 16:13:09.034 30363-30700/com.tencent.shadow.sample.host E/plugin_time: buildApplication sample-plugin-app start
2020-11-19 16:13:09.035 30363-30700/com.tencent.shadow.sample.host E/plugin_time: buildApplication sample-plugin-app :1
2020-11-19 16:13:09.035 30363-30702/com.tencent.shadow.sample.host E/plugin_time: buildRunningPlugin sample-plugin-app start
2020-11-19 16:13:09.036 30363-30702/com.tencent.shadow.sample.host E/plugin_time: buildRunningPlugin sample-plugin-app :1
2020-11-19 16:13:09.036 30363-30702/com.tencent.shadow.sample.host E/plugin_time: buildRunningPlugin all sample-plugin-app :123
2020-11-19 16:13:09.047 1305-9198/? W/ColorAccessControlManagerService: notifyZoomWindowExit: stack=ActivityStack{88e1496 stackId=287 type=standard mode=fullscreen visible=true translucent=false, 1 tasks}  windowMode=1  topActivity=ActivityRecord{8877be6 u0 com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity t7826}  toFullScreen = true
2020-11-19 16:13:09.054 30363-30363/com.tencent.shadow.sample.host W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@6cbc85d
2020-11-19 16:13:09.055 1305-9198/? W/ColorAccessControlManagerService: notifyZoomWindowExit: stack=ActivityStack{88e1496 stackId=287 type=standard mode=fullscreen visible=true translucent=false, 1 tasks}  windowMode=1  topActivity=ActivityRecord{8877be6 u0 com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity t7826}  toFullScreen = true
2020-11-19 16:13:09.058 3813-3857/? E/horae: setForegroundPackage, mChargingStateMachine is null!
2020-11-19 16:13:09.061 1305-1330/? E/OppoThermalStats: Error getting package info: com.tencent.shadow.sample.host:plugin
    android.content.pm.PackageManager$NameNotFoundException: com.tencent.shadow.sample.host:plugin
        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:210)
        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:174)
        at com.android.internal.os.OppoThermalStatsHelper.addThermalForeProc(OppoThermalStatsHelper.java:2358)
        at com.android.internal.os.BatteryStatsImpl.noteEventLocked(BatteryStatsImpl.java:4098)
        at com.android.server.am.BatteryStatsService.noteEvent(BatteryStatsService.java:465)
        at com.android.server.am.OppoBatteryStatsService.noteEvent(OppoBatteryStatsService.java:266)
        at com.android.server.am.ActivityManagerService.getTopAppLocked(ActivityManagerService.java:18205)
        at com.android.server.am.OomAdjuster.updateOomAdjLocked(OomAdjuster.java:267)
        at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:18438)
        at com.android.server.am.ProcessRecord.updateProcessInfo(ProcessRecord.java:1392)
        at com.android.server.am.ProcessRecord.onStartActivity(ProcessRecord.java:1424)
        at com.android.server.wm.-$$Lambda$VY87MmFWaCLMkNa2qHGaPrThyrI.accept(Unknown Source:27)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:317)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:195)
        at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:86)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:238)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
2020-11-19 16:13:09.088 30363-30363/com.tencent.shadow.sample.host W/ple.host:plugi: Accessing hidden method Lcom/color/internal/widget/ColorToastLayout;-><init>(Landroid/content/Context;Landroid/util/AttributeSet;)V (blacklist, reflection, denied)
2020-11-19 16:13:09.088 30363-30363/com.tencent.shadow.sample.host W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
2020-11-19 16:13:09.096 1305-9205/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1072 com.android.server.am.OppoExtraActivityManagerService.setKeyLockModeNormal:56 com.android.server.am.ActivityManagerService.appDiedLocked:4213 com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied:1656 android.os.BinderProxy.sendDeathNotice:633 
2020-11-19 16:13:09.097 1305-9205/? W/ActivityManager: Scheduling restart of crashed service com.tencent.shadow.sample.host/.PluginProcessPPS in 1000ms
2020-11-19 16:13:09.097 2660-20112/? E/SafeCenter.DWB.ActivityMonitor: onProcessDied com.tencent.shadow.sample.host
2020-11-19 16:13:09.117 30364-30364/? E/ple.host:plugi: Unknown bits set in runtime_flags: 0x8000
2020-11-19 16:13:09.131 1305-3127/? W/ColorAccessControlManagerService: notifyZoomWindowExit: stack=ActivityStack{88e1496 stackId=287 type=standard mode=fullscreen visible=true translucent=false, 1 tasks}  windowMode=1  topActivity=ActivityRecord{8877be6 u0 com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity t7826}  toFullScreen = true
2020-11-19 16:13:09.133 3813-3857/? E/horae: setForegroundPackage, mChargingStateMachine is null!
2020-11-19 16:13:09.158 30364-30364/com.tencent.shadow.sample.host E/---wyf---: ConstraintLayout:dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.tencent.shadow.sample.host-t0gW0PHpJMNtVJh6wF8uUA==/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.shadow.sample.host-t0gW0PHpJMNtVJh6wF8uUA==/lib/arm64, /system/lib64, /system/product/lib64]]]
2020-11-19 16:13:09.178 30364-30364/? E/PluginContainerActivity: PluginContainerActivity: DelegateProviderHolder没有初始化
2020-11-19 16:13:09.181 30364-30364/? E/PluginContainerActivity: illegalIntent savedInstanceState==null getIntent().getExtras()==Bundle[mParcelledData.dataSize=2532]
2020-11-19 16:13:09.181 30364-30364/? E/PluginContainerActivity: onCreate: hostActivityDelegate==null finish activity
2020-11-19 16:13:09.182 1305-9205/? W/ColorAccessControlManagerService: notifyZoomWindowExit: stack=ActivityStack{88e1496 stackId=287 type=standard mode=fullscreen visible=true translucent=false, 1 tasks}  windowMode=1  topActivity=ActivityRecord{816133b u0 com.tencent.shadow.sample.host/.MainActivity t7826}  toFullScreen = true
2020-11-19 16:13:09.194 1305-3127/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1072 com.android.server.am.OppoExtraActivityManagerService.setKeyLockModeNormal:56 com.android.server.am.ActivityManagerService.appDiedLocked:4213 com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied:1656 android.os.BinderProxy.sendDeathNotice:633 
2020-11-19 16:13:09.194 1305-3127/? W/ActivityManager: Scheduling restart of crashed service com.tencent.shadow.sample.host/.PluginProcessPPS in 4000ms
2020-11-19 16:13:09.195 2660-20112/? E/SafeCenter.DWB.ActivityMonitor: onProcessDied com.tencent.shadow.sample.host
2020-11-19 16:13:09.198 3813-29209/? E/hypnusd: same package name, skip
2020-11-19 16:13:09.201 3813-3857/? E/horae: setForegroundPackage, mChargingStateMachine is null!
2020-11-19 16:13:09.418 27458-30620/? W/System.err: java.net.SocketException: Socket is closed
2020-11-19 16:13:09.418 27458-30620/? W/System.err:     at java.net.Socket.getSoTimeout(Socket.java:1206)
2020-11-19 16:13:09.418 27458-30620/? W/System.err:     at com.tencent.qphone.base.util.MsfSocketInputBuffer.isDataAvailable(P:71)
2020-11-19 16:13:09.418 27458-30620/? W/System.err:     at com.tencent.mobileqq.msf.core.net.m$b.run(P:476)
2020-11-19 16:13:09.659 720-720/? W/BufferQueueLayer: [com.tencent.shadow.sample.host/com.tencent.shadow.sample.host.PluginLoadActivity#0] producer:0x7533e22540 BufferQueueLayer dtor 0x7533839000
2020-11-19 16:13:09.659 720-720/? E/SurfaceFlinger: this:0x7533e22540 producer:0x7547041000 MonitoredProducer dtor dumpLayerPtr ptr 0x7533839000
2020-11-19 16:13:09.659 720-720/? E/SurfaceFlinger: this:0x7533e22540 producer:0x7547041000 MonitoredProducer dtor dumpLayerPtr refs 0x7563e17880
2020-11-19 16:13:09.681 1305-1330/? W/ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{8877be6 u0 com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity t-1 f}
2020-11-19 16:13:09.682 1305-1330/? W/ColorAccessControlManagerService: notifyZoomWindowExit: stack=ActivityStack{88e1496 stackId=287 type=standard mode=fullscreen visible=true translucent=false, 1 tasks}  windowMode=1  topActivity=ActivityRecord{816133b u0 com.tencent.shadow.sample.host/.MainActivity t7826}  toFullScreen = true
2020-11-19 16:13:10.323 1305-3127/? E/WifiService: Permission violation - getConfiguredNetworks not allowed for uid=99910211, packageName=com.tencent.mm, reason=java.lang.SecurityException: UID 99910211 has no location permission

**Comment by milesx6** [comment]
注释掉com.tencent.shadow.sample.plugin.app.lib.gallery.splash.SplashAnimation::onStart()方法里面的ToastUtil.showToast(mContext,"animation start");这一行，问题解决。

原因是OPPO对系统toast做了定制，使用了自定义的toast布局，这里的context使用了插件的，导致布局加载失败，进程crash了。
