### ISSUE TITLE
插件中依赖其他框架，其他框架中有自定义的ContentProvider，打成插件运行报错崩溃

### ISSUE THREAD

**Issue by weeeeeeeeeeeei** [Tencent/Shadow#449]
2020-11-30 16:27:49.569 20450-20558/com.take.host E/DatabaseUtils: Writing exception to parcel
    java.lang.IllegalArgumentException: 不能识别的uri Authority:com.tencent.shadow.contentprovider.authority.dynamic
        at com.tencent.shadow.core.loader.managers.PluginContentProviderManager.convert2PluginUri(Unknown Source:90)
        at com.tencent.shadow.core.loader.delegates.ShadowContentProviderDelegate.update(Unknown Source:7)
        at com.tencent.shadow.core.runtime.container.PluginContainerContentProvider.update(PluginContainerContentProvider.java:102)
        at android.content.ContentProvider$Transport.update(ContentProvider.java:424)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:215)
        at android.os.Binder.execTransactInternal(Binder.java:1037)
        at android.os.Binder.execTransact(Binder.java:1006)
2020-11-30 16:27:49.570 20604-20678/com.take.host E/AndroidRuntime: FATAL EXCEPTION: track_thread_2
    Process: com.take.host:plugin1, PID: 20604
    java.lang.IllegalArgumentException: 不能识别的uri Authority:com.tencent.shadow.contentprovider.authority.dynamic
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.update(ContentProviderNative.java:578)
        at android.content.ContentResolver.update(ContentResolver.java:2134)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by shifujun** [comment]
在sample里搜索一下`com.tencent.shadow.contentprovider.authority.dynamic`。ContentProvider的支持也是依赖于在宿主中注册了一个代理的ContentProvider。

**Comment by VirgCode** [comment]
大佬，刚搜了，我在host宿主项目manifest中配置注册了
<provider
      android:name="com.tencent.shadow.core.runtime.container.PluginContainerContentProvider"
      android:authorities="com.tencent.shadow.contentprovider.authority.dynamic"
      android:grantUriPermissions="true"
      android:process=":plugin" />

loader中复写了
 /**
   * 配置对应宿主中预注册的壳子contentProvider的信息
   */
@NotNull
@Override
public ContainerProviderInfo onBindContainerContentProvider(@NotNull ComponentName componentName) {
   return new ContainerProviderInfo(
           "com.tencent.shadow.core.runtime.container.PluginContainerContentProvider",
           "com.tencent.shadow.contentprovider.authority.dynamic");
}
应该没有配置错误

**Comment by shifujun** [comment]
自己实在没法定位问题，就只能参考 [CONTRIBUTING.md](https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md#issue) 把修改的sample代码push上来看看了。

**Comment by vinaiso** [comment]
> 自己实在没法定位问题，就只能参考 [CONTRIBUTING.md](https://github.com/Tencent/Shadow/blob/master/CONTRIBUTING.md#issue) 把修改的sample代码push上来看看了。

大佬，发现一个问题，不同uuid的插件并且插件运行在不同的进程，每个插件都有自定义的ContentProvider，这种情况下shadow框架注册的代理的ContentProvider，貌似不能解决这种情况

**Comment by shifujun** [comment]
> 不同uuid的插件并且插件运行在不同的进程，每个插件都有自定义的ContentProvider，这种情况下shadow框架注册的代理的ContentProvider，貌似不能解决这种情况

“shadow框架注册的代理的ContentProvider”以及其他代理的Activity等组件，都不是自动去注册的，你说的情况需要在不同的进程中注册对应的代理组件。

如果是说没能自动注册的问题，只是这个能力实现也没太大难度，实现后也不会频繁使用，所以没实现而已。

**Comment by HeLiHuang** [comment]
最后解决了吗？怎么解决的？
