### ISSUE TITLE
android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by listen2code** [Tencent/Shadow#479]
【项目地址】
https://github.com/listen2code/Shadow
提交ID：bug0216
/Shadow/projects/sample/maven目录下有个shadowAssemble.sh的编译工具

【堆栈】：
2021-02-16 14:19:31.135 23281-23317/com.tencent.shadow.sample.host E/cr_VariationsUtils: Failed reading seed file "/data/user/0/com.tencent.shadow.sample.host/app_webview/variations_seed": /data/user/0/com.tencent.shadow.sample.host/app_webview/variations_seed (No such file or directory)
2021-02-16 14:19:36.029 23281-23281/com.tencent.shadow.sample.host E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.shadow.sample.host:plugin, PID: 23281
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.shadow.sample.host/com.tencent.shadow.sample.runtime.PluginDefaultProxyActivity}: java.lang.RuntimeException: android.content.res.Resources$NotFoundException: Drawable com.tencent.shadow.sample.host:id/info with resource ID #0x7f07005b
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: android.content.res.Resources$NotFoundException: Drawable com.tencent.shadow.sample.host:id/info with resource ID #0x7f07005b
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(Unknown Source:380)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: android.content.res.Resources$NotFoundException: Drawable com.tencent.shadow.sample.host:id/info with resource ID #0x7f07005b
     Caused by: android.content.res.Resources$NotFoundException: Resource "com.tencent.shadow.sample.host:id/info" (7f07005b) is not a Drawable (color or path): TypedValue{t=0x12/d=0x0 a=2 r=0x7f07005b}
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:786)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:888)
        at android.content.res.Resources.getDrawable(Resources.java:827)
        at com.tencent.shadow.core.runtime.MixResources.getDrawable(MixResources.java:112)
        at android.content.Context.getDrawable(Context.java:626)
        at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:455)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:144)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
        at androidx.appcompat.widget.ResourceManagerInternal.checkVectorDrawableSetup(ResourceManagerInternal.java:489)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:137)
        at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:411)
        at androidx.appcompat.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:93)
        at androidx.appcompat.app.AppCompatDelegateImpl.attachToWindow(AppCompatDelegateImpl.java:794)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureWindow(AppCompatDelegateImpl.java:770)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreate(AppCompatDelegateImpl.java:498)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:114)
        at com.tencent.shadow.sample.common.BaseActivity.onCreate(BaseActivity.java:13)
        at com.tencent.shadow.sample.plugin2.MainActivity.onCreate(MainActivity.java:10)
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(Unknown Source:371)
2021-02-16 14:19:36.030 23281-23281/com.tencent.shadow.sample.host E/AndroidRuntime:     at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

【场景】
sample-common包含runtime和loader，plugin1和plugin2依赖sample-common，同一个进程，uuid相同，并在gradle.build中设置dependsOn=['sample-common']；sample-common中implementation 'com.google.android.material:material:1.2.1'，plugin1中同样implementation material不报错，plugin2中没有implementation material报错，提示信息如上：

【详情】提示找不到"resource ID #0x7f07005b"，如图，是sample-common.zip中的abc_vector_test.xml，目测是存在的，为什么在打开plugin2的Activity会提示找不到呢（plugin1因为也引入了material，所以apk里也有0x7f07005b资源，plugin2因为是dependsOn common，为什么不会往common去找这个资源呢？）sample-common作为plugin1和plugin2的公共资源，现在希望达到的效果是common已经引入的aar，在plugin1和plugin2是否可以不用再重复引入？
![image](https://user-images.githubusercontent.com/3157341/108026634-aeb36e00-7063-11eb-96b7-0da2193d3165.png)

**Comment by shifujun** [comment]
这是因为`dependsOn`在实现时只负责配置了各个插件的ClassLoader的parent关系，所以只有Java类的依赖关系可以跨插件找到。

如果希望跨apk共享资源，这是一套机制。目前的代码中没有实现。

https://github.com/Tencent/Shadow/blob/2b494707308b28522a73a2355b258c9b70448441/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/CreateResourceBloc.kt#L43

需要在构造插件的Resource时，将其依赖的插件的apk添加到`sharedLibraryFiles`中。而且它们的资源ID还不能冲突，需要用aapt2的选项`--package-id`将这些插件的资源ID分区隔离开才行。

https://developer.android.com/studio/command-line/aapt2#link_options

`CreateResourceBloc`中从宿主的`sharedLibraryFiles`中复制值，是为了将系统注入的`webview.apk`同样注入给插件。使插件中的Webview长按出来的菜单需要的xml资源能够从`webview.apk`中找到。

**Comment by listen2code** [comment]
> 除了以上的方案，我更推荐一种简单的做法，就是让common插件暴露一些Java方法返回View等对象。让common插件内部代码从自己的Resource中获取资源，构造好正常的Java对象，再传递给其他插件。这样的方案风险更低。

如果共享的是我们自己开发UI组件，用这种方式是可以的，不过也是有点违背我们原来的开发模式，至少不能在xml布局里面直接使用。不过我这个demo中只是引入了"com.google.android.material:material"，代码中并没有用到，可是那个"abc_vector_test.xml"我都不知道在哪里依赖到，就报错了；如果是这样的话，我更倾向于common里只存在公有的java类，工具类等，会有资源共享问题的aar，每个plugin各自引入，这样这个common的作用就小了，每个业务plugin中能提取出来的公共部分其实不多，或者单plugin单进程的模式。
