### ISSUE TITLE
插件不能弹出notification

### ISSUE THREAD

**Issue by Linats** [Tencent/Shadow#487]
sample plugin的`MainAcitivty`加上以下代码：
```
        NotificationManager mNotificationManager = (NotificationManager) getSystemService(
                Context.NOTIFICATION_SERVICE);
        mNotificationManager.createNotificationChannel(new NotificationChannel("XXX", "XXX", NotificationManager.IMPORTANCE_DEFAULT));
        Notification notification = new Notification.Builder(this, "XXX")
            .setSmallIcon(R.drawable.expanded)
            .setContentTitle("XXX...")
            .build();
        mNotificationManager.notify(5060, notification);
```

系统不会弹出notification，系统报错如下
```
2021-03-03 15:17:15.352 2234-2234/com.android.systemui E/Icon: Unable to load resource 0x7f060055 from pkg=com.tencent.shadow.sample.host
    android.content.res.Resources$NotFoundException: Resource ID #0x7f060055
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:285)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:964)
        at android.content.res.Resources.getDrawable(Resources.java:880)
        at android.graphics.drawable.Icon.loadDrawableInner(Icon.java:370)
        at android.graphics.drawable.Icon.loadDrawable(Icon.java:323)
        at android.graphics.drawable.Icon.loadDrawableAsUser(Icon.java:434)
        at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:445)
        at com.android.systemui.statusbar.StatusBarIconView.getIcon(StatusBarIconView.java:429)
        at com.android.systemui.statusbar.StatusBarIconView.updateDrawable(StatusBarIconView.java:407)
        at com.android.systemui.statusbar.StatusBarIconView.set(StatusBarIconView.java:367)
        at com.android.systemui.statusbar.notification.collection.NotificationEntry.createIcons(NotificationEntry.java:381)
        at com.android.systemui.statusbar.notification.collection.NotificationRowBinderImpl.inflateViews(NotificationRowBinderImpl.java:143)
        at com.android.systemui.statusbar.notification.NotificationEntryManager.addNotificationInternal(NotificationEntryManager.java:411)
        at com.android.systemui.statusbar.notification.NotificationEntryManager.addNotification(NotificationEntryManager.java:432)
        at com.android.systemui.statusbar.NotificationListener.lambda$onNotificationPosted$1$NotificationListener(NotificationListener.java:135)
        at com.android.systemui.statusbar.-$$Lambda$NotificationListener$NvFmU0XrVPuc5pizHcri9I0apkw.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

插件的icon资源在宿主中不存在。
不放置small icon又会报错：
`java.lang.IllegalArgumentException: Invalid notification (no valid small icon):`

目前没想到很好的解决方法，想请求帮助~

**Comment by shifujun** [comment]
试试这样行不行：
```
.setSmallIcon(
                        Icon.createWithBitmap(
                                BitmapFactory.decodeResource(getResources(), R.drawable.expanded)
                        )
                )
```

setSmallIcon直接传给它资源ID，它是把资源ID直接封装到Icon持久化对象里传给系统了。系统拿到ID返回来去安装的宿主apk中肯定是找不到的。但是这里Icon是允许直接封装bitmap的，所以应该可行。

如果可行的话，这个写法的转换应该可以通过Transform自动编辑插件代码。

**Comment by Linats** [comment]
测试可以，但`public Builder setSmallIcon(Icon icon)`提示是API 23以上的。
所以`NotificationCompat`也没有`setSmallIcon(Icon icon)`的API。
如果直接transform，低于23可能有问题。

**Comment by shifujun** [comment]
好像是的，印象中我似乎也开发过这个需求。低版本的API确实不允许设置任意Bitmap，只接受一个资源ID，由系统到安装的宿主apk中反查。所以我记得我们好像是让插件直接问宿主代码要了一个宿主中的资源ID设置进去的。

**Comment by Linats** [comment]
嗯嗯，我想到的也是这样。毕竟这个通知的icon也是挺固定的。可以直接找宿主拿。
感谢快速回复~

**Comment by chy116449859** [comment]
我们开发也碰到这个问题，如何兼容传入id的方式呢？ 原因是插件改了资源id，把这个修改后的资源id传入系统，系统找不到这个id？

**Comment by chy116449859** [comment]
如果notification需要展示自定义layout，就还会碰到这个id找不到的问题
