### ISSUE TITLE
Dalvik虚拟机，MultiDex异常

### ISSUE THREAD

**Issue by SpenceAcc** [Tencent/Shadow#49]
崩溃异常信息如下：
java.lang.NullPointerException
        at java.io.File.fixSlashes(File.java:185)
        at java.io.File.<init>(File.java:134)
        at android.support.multidex.MultiDex.install(MultiDex.java:113)
        at com.yihuo.goldtiger.GoldTigerApplication.attachBaseContext(GoldTigerApplication.java:78)
        at com.tencent.shadow.core.loader.ShadowPluginLoader$callApplicationOnCreate$1.invoke(Unknown Source)
        at com.tencent.shadow.core.loader.ShadowPluginLoader$callApplicationOnCreate$2.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)

插件代码如下：
public class GoldTigerApplication extends Application {
  @Override
  protected void attachBaseContext(Context base) {
     super.attachBaseContext(base);
     MultiDex.install(this);
  }
}
宿主打开插件在Android4.4的环境下，采用Dalvik运行模式。会出现上述异常。高版本采用ART虚拟机未见该异常。

**Comment by shifujun** [comment]
悲剧啊。是#46 给改坏了。MultiDex之前是有手工测试用例测过的，自动化测试用例没写，所以#46 就没发现有问题。

先补上了自动化测试用例 #50 然后再看是什么原因。

由此可见自动化测试覆盖程度对插件框架真的是非常重要的。

**Comment by shifujun** [comment]
#51 应该修复了问题

**Comment by SpenceAcc** [comment]
拉取了#51的代码后，在4.4系统下的MultiDex报错如下
07-22 17:15:26.696 5163-5163/com.yihuo.goldtiger.shadow:plugin E/MultiDex: Failed to create dir /data/data/com.yihuo.goldtiger.shadow/files/ShadowPlugin_sample-plugin/dataDir/code_cache. parent file is a dir false, a file false, exists false, readable false, writable false
当前文件目录截图如下
![image](https://user-images.githubusercontent.com/12027880/61622505-8442d880-aca7-11e9-9ab9-6c6d64031fa4.png)

Shadow/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/LoadPluginBloc.kt

是不是LoadPluginBloc.kt文件下的文件未能创建成功？导致目录异常了。

**val dataDir = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    tempContext.dataDir
                } else {
                    File(tempContext.filesDir, "dataDir")
                }**

**Comment by shifujun** [comment]
不知道为什么我的4.4虚拟机没能复现。但看起来就是dataDir目录不存在造成的。
你那里能复现的话，能不能试一下加一行`dataDir.mkdirs()`?
