### ISSUE TITLE
关于NoClassDefFoundError: android.app.PictureInPictureParams 问题解决

### ISSUE THREAD

**Issue by hpuhsp** [Tencent/Shadow#502]
`2021-04-08 17:17:11.196 16079-16079/com.xxx.slaughter.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.slaughter.debug:slaughter_plugin, PID: 16079
    java.lang.NoClassDefFoundError: android.app.PictureInPictureParams
        at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
        at java.lang.Class.getDexCacheType(Class.java:2551)
        at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169)
        at java.lang.reflect.Method.getParameterTypes(Method.java:193)
        at java.lang.reflect.Method$1.compare(Method.java:72)
        at java.lang.reflect.Method$1.compare(Method.java:66)
        at libcore.util.CollectionUtils.removeDuplicates(CollectionUtils.java:89)
        at java.lang.Class.getMethods(Class.java:1423)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:157)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:140)
        at com.swallow.fly.base.view.BaseActivity.onCreate(BaseActivity.kt:145)
        at com.xxx.slaughter.page.purchase.activity.Hilt_PigPurchasePlanListActivity.onCreate(Hilt_PigPurchasePlanListActivity.java:31)
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate()
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:6720)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.PictureInPictureParams" on path: DexPathList[[zip file "/data/user/0/com.xxx.slaughter.debug/files/ShadowPluginManager/UnpackedPlugin/multi-process-manager/326151bff2a47e855c0d1bdadffd211e/slaughter-debug.zip/plugin-runtime-debug.apk"],nativeLibraryDirectories=[/data/user/0/com.xxx.slaughter.debug/files/ShadowPluginManager/UnpackedPlugin/multi-process-manager/lib/class java.util.UUID_lib, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tencent.shadow.dynamic.host.ApkClassLoader.loadClass(ApkClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
        at java.lang.Class.getDexCacheType(Class.java:2551) 
        at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169) 
        at java.lang.reflect.Method.getParameterTypes(Method.java:193) 
        at java.lang.reflect.Method$1.compare(Method.java:72) 
        at java.lang.reflect.Method$1.compare(Method.java:66) 
        at libcore.util.CollectionUtils.removeDuplicates(CollectionUtils.java:89) 
        at java.lang.Class.getMethods(Class.java:1423) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:157) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64) 
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:140) 
        at com.swallow.fly.base.view.BaseActivity.onCreate(BaseActivity.kt:145) 
        at com.xxx.slaughter.page.purchase.activity.Hilt_PigPurchasePlanListActivity.onCreate(Hilt_PigPurchasePlanListActivity.java:31) 
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate() 
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84) 
        at android.app.Activity.performCreate(Activity.java:6720) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
    	Suppressed: java.lang.ClassNotFoundException: Didn't find class "android.app.PictureInPictureParams" on path: DexPathList[[zip file "/data/user/0/com.xxx.slaughter.debug/files/ShadowPluginManager/UnpackedPlugin/multi-process-manager/326151bff2a47e855c0d1bdadffd211e/slaughter-debug.zip/plugin-loader-debug.apk"],nativeLibraryDirectories=[/data/user/0/com.xxx.slaughter.debug/files/ShadowPluginManager/UnpackedPlugin/multi-process-manager/lib/class java.util.UUID_lib, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at com.tencent.shadow.dynamic.host.ApkClassLoader.loadClass(ApkClassLoader.java:79)
        		... 29 more
`

**Comment by shifujun** [comment]
请参考https://github.com/Tencent/Shadow/blob/2b494707308b28522a73a2355b258c9b70448441/CONTRIBUTING.md 交流。

**Comment by hpuhsp** [comment]
抱歉，当时Issues提交的比较仓促，没有按照要求进行提交。这个问题已经解决了，主要是因为EventBus 3 内部反射调用引起的问题。当然如果使用添加索引的方式可以避免使用反射，这样是没有这个问题的。这里讲的很清楚https://stackoverflow.com/questions/47754855/noclassdeffounderror-android-app-pictureinpictureparams。
