### ISSUE TITLE
插件Activity继承host_lib里的BaseActivity报错问题

### ISSUE THREAD

**Issue by ychxx** [Tencent/Shadow#525]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yc.shadowdemo/com.yc.plugin.runtime.PluginDefaultProxyActivity}: java.lang.RuntimeException: java.lang.NullPointerException: Missing required view with ID: com.yc.shadowdemo:id/btnTestNet
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2483)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2543)
        at android.app.ActivityThread.access$1000(ActivityThread.java:156)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
     Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Missing required view with ID: com.yc.shadowdemo:id/btnTestNet
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(ShadowActivityDelegate.kt:152)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:6357)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2543) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:156) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636) 
     Caused by: java.lang.NullPointerException: Missing required view with ID: com.yc.shadowdemo:id/btnTestNet
        at com.yc.commontlib.databinding.PluginTestNetActivityTempBinding.bind(PluginTestNetActivityTempBinding.java:87)
        at com.yc.commontlib.databinding.PluginTestNetActivityTempBinding.inflate(PluginTestNetActivityTempBinding.java:56)
        at com.yc.commontlib.databinding.PluginTestNetActivityTempBinding.inflate(PluginTestNetActivityTempBinding.java:46)
        at com.yc.plugin.app.PluginTestViewBindingActivity.onCreate(PluginTestViewBindingActivity.kt:32)
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(ShadowActivityDelegate.kt:149)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84) 
        at android.app.Activity.performCreate(Activity.java:6357) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2543) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:156) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)

**Comment by shifujun** [comment]
可以试着在https://github.com/Tencent/Shadow/tree/master/projects/test/plugin/androidx-cases/ 中尝试复现一下，然后push上来我也试试。DataBinding之前测试过，可能test测试用例里没有，可以帮忙先补充一下，要是能复现，也好修复的。

**Comment by ychxx** [comment]
抱歉这么久才回复
一、
我在shadow项目的sample/source测试了，下面两种情况都可以运行成功
1.在sample-app-lib项目里使用sample-app-lib项目layout里的xx_plugin_activity.xml生成的xxPluginActivityBinding
2.在sample-app-lib项目里使用sample_host_Lib项目layout里的xx_lib_activity.xml生成的xxLibActivityBinding
但是在我自己写demo里，第二种情况会崩溃

二、
在sample-app-lib项目创建一个abstract class YcBaseActivity :Activity(){}，然后将sample-app-lib的SplashActivity改为继承YcBaseActivity
在demo和shadow运行后都会崩溃

[Demo项目地址](https://github.com/ychxx/ShadowDemo.git)
[shadow项目fork地址](https://github.com/ychxx/Shadow-1.git)

**Comment by shifujun** [comment]
你的https://github.com/ychxx/Shadow-1/commit/7e9fdb8752eef1f189b7c37d6b0d5d93fb1d5410 无关的改动也太多了，我看不出来你的关键改动是什么。而且在里面也搜不到你说的`YcBaseActivity`，也没看到你修改了SplashActivity的父类。

请在`androidx-cases-lib`中添加你需要的viewBinding，可以运行`androidx-cases-app`以测试没有Shadow介入的正常app情况，可以在仿照`LiveDataWithActivityTest`测试其在插件环境下的运行情况。

**Comment by ychxx** [comment]
在shadow.general-cases-lib项目里使用shadow.plugin-use-host-code-lib项目的TestUseHostLibBaseActivity报错

仿照BasicTest写了UseHostLibBaseActivityTest[6457c09](https://github.com/ychxx/Shadow/commit/3088f28fbe4ec8cf8a22846c471b41da941dc9cb)

**Comment by shifujun** [comment]
> 在shadow.general-cases-lib项目里使用shadow.plugin-use-host-code-lib项目的TestUseHostLibBaseActivity报错
> 
> 仿照BasicTest写了UseHostLibBaseActivityTest[6457c09](https://github.com/ychxx/Shadow/commit/3088f28fbe4ec8cf8a22846c471b41da941dc9cb)

这个代码说明问题就超级清晰了。按照Shadow目前的实现，插件是不能继承宿主中的Activity的。之前也有人问过#285 。

我后来也想了一下，插件继承宿主的这些类也不是完全不能实现。需要把相同的Transform逻辑应用在宿主上。使插件和宿主中这些和系统交互有限制的类，都被重构成普通类。

如果ViewBinding没问题，可以把issue标题改一下。

**Comment by ychxx** [comment]
添加一个ViewBinding测试[3088f28](https://github.com/ychxx/Shadow/commit/4315779adfc54b23c064a2f556372da935d75c81)
