### ISSUE TITLE
IncompatibleClassChangeError: Class 'android.content.res.XmlBlock$Parser' does not implement interface 'org.xmlpull.v1.XmlPullParser'

### ISSUE THREAD

**Issue by Heart-Beats** [Tencent/Shadow#529]
上次的 #505 问题在 API 30 上解决以后，我按最新的代码在我手机上测试报错堆栈如下：
![image](https://user-images.githubusercontent.com/33248551/121986889-f952b600-cdc9-11eb-9ff7-e1c2dfcec7ae.png)

上次时可以正常启动插件的，只是切换插件时出错，现在启动 sunflower 没问题，启动我自己的插件出错，我这边插件工程的代码见：https://github.com/Heart-Beats/ShadowPlugin/tree/main/plugin/test

**Comment by shifujun** [comment]
这两个类型Shadow都没有处理过，所以应该先确认一下你这个插件不使用Shadow时，能否正常工作。

**Comment by Heart-Beats** [comment]
不使用 Shadow 时这个插件APP是可以正常使用的，这个就是一个 Android 的模板代码，啥都没作处理

**Comment by shifujun** [comment]
我尝试复现这个问题没成功。https://github.com/shifujun/Shadow/tree/issue529

你给的代码库不是fork的代码库，编译它很困难。而且似乎没有host模块，也跑不了。建议你尝试基于我的例子，在测试用例里复现这个问题。

**Comment by Heart-Beats** [comment]
我这边将该分支克隆下来，直接运行这个测试用例出错：
![image](https://user-images.githubusercontent.com/33248551/122006483-77728500-cde9-11eb-826a-1ee928453297.png)
是还需要进行其他操作吗？

**Comment by shifujun** [comment]
你执行的操作应该是对的。只是你那个手机可能状态不太对，测试用例没跑起来。建议先用官方的模拟器。

**Comment by Heart-Beats** [comment]
使用模拟器运行该测试是没问题的，我在 issue529 分支上将 `TestSupportMenuInflaterActivity `改为与我启动的插件页面一致，也是可以正常在模拟器和我手机上启动，但是在模拟器上我的宿主应用启动插件报错是同样的，模拟器 API 30，我的手机为 29， 随后我将我的插件页面去除 `onCreateOptionsMenu(menu: Menu)`方法的重写，是可以正常启动插件的。

我的宿主应用地址：https://github.com/Heart-Beats/AndroidApplicationTest
插件应用地址：https://github.com/Heart-Beats/ShadowPlugin/tree/main/plugin/test
将插件包正常放在 SD 卡根目录即可，点击宿主应用主页的 **测试Shadow插件化** 选择第二个即可产生此问题

**Comment by shifujun** [comment]
你还是先看一下你能复现的场景下，两个涉事接口的ClassLoader是不是BootClassLoader吧。像我这个提交：https://github.com/shifujun/Shadow/commit/d862a657223d2cc0fe3c302d82523ca8c78398ba 

如果都是BootClassLoader的话，确实是非常奇特的问题。否则应该还是你自己写的什么代码干涉了这个内部类的构造。
`android.content.res.XmlBlock$Parser`这个内部类是私有的，Shadow是肯定没有去修改它的任何逻辑。
如果拿到这么一个类，又没实现`org.xmlpull.v1.XmlPullParser`接口，除非`org.xmlpull.v1.XmlPullParser`不是来自BootClassLoader的。而正常它也应该来自BootClassLoader，这个Shadow也没有修改过。

**Comment by Heart-Beats** [comment]
我复现时加了一下日志输出，`org.xmlpull.v1.XmlPullParser ` 确实不是来自 BootClassLoader：
```shell
xmlBlock$ParserFrom: java.lang.BootClassLoader,  XmlPullParserFrom: com.tencent.shadow.core.loader.classloaders.PluginClassLoader
```

在测试用例中他们都是来自 BootClassLoader，我这边除了 **DynamicPluginManager**  的构造不是从 apk 中加载的，而是仿照加载流程中反射直接加载 `com.tencent.shadow.dynamic.impl.ManagerFactoryImpl`得到，PluginManager 的实现与示例代码基本一致，插件 Activity 的启动方式都是调用 `mPluginLoader.startActivityInPluginProcess(intent)`的。

**Comment by Heart-Beats** [comment]
大佬，按您这最新提交版本测试还是有问题：

启动插件调用 DynamicPluginLoader 的 `startActivityInPluginProcess(intent: Intent)`后，EnterCallback 的 `onEnterComplete()` 回调触发，但是页面并未跳转，再次点击请求启动插件时会有报错输出不闪退，错误日志如下：

![image](https://user-images.githubusercontent.com/33248551/122194766-4fa61e80-cec8-11eb-87a1-1ff2c0b461a1.png)

![image](https://user-images.githubusercontent.com/33248551/122194814-5d5ba400-cec8-11eb-9aad-3deeb28e638a.png)

**Comment by shifujun** [comment]
> 输出不闪

这明显不是同一个问题啊。你debug一下你的插件安装过程吧。如果Loader差不到这个插件Activity已经加载过，就会认为它是系统里的其他Activity，就会直接去启动。

**Comment by Heart-Beats** [comment]
> > 输出不闪
> 
> 这明显不是同一个问题啊。你debug一下你的插件安装过程吧。如果Loader差不到这个插件Activity已经加载过，就会认为它是系统里的其他Activity，就会直接去启动。

确实不是用一个问题，但是没合入 #533 时：
``` kotlin
	override fun onCreateOptionsMenu(menu: Menu): Boolean {
		// menuInflater.inflate(R.menu.menu_main, menu)
		return true
	}
```

我注释掉菜单项的填充是可以正常启动插件的，合入后取消注释没错误但是插件启动不起来了，所以应该是和合入的提交有一定的关联的

**Comment by shifujun** [comment]
你应该把那个错误堆栈复制出来的。那不是又出现个cast exception么。我再测一下这个场景吧。应该还是你的插件，宿主有重复的类导致的。

**Comment by shifujun** [comment]
https://github.com/shifujun/Shadow/commit/f6b3fcdc827b8bc2fda47e98be5af7cf23829d28
可以看到我已经加上了ComponentFactory的测试，正常情况下是工作正常的。

你遇到问题的代码在这里：
https://github.com/Tencent/Shadow/blob/4e5a2d683f473e6cb54c4c353d164b8792bfd3ad/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/LoadPluginBloc.kt#L117-L118

这里代码原本的意图是这样的：从PluginClassLoader里加载插件定义的ComponentFactory，加载这个类时，它的最上面的父类`AppComponentFactory`应该已经被transform成了`ShadowAppComponentFactory`。在PluginClassloader中，它认为自己这个类所在的classloader就是loader的classloader，所以它会主动从loader的classloader中加载`ShadowAppComponentFactory`这个有特殊包名的类。而`LoadPluginBloc`中的`ShadowAppComponentFactory::class.java`应该也是从当前类的Classloader加载的，所以设计上它们应该会是同一个类，从而工作正常。

#533 修改了PluginClassLoader优先从自己加载类还是优先从PathClassLoader的parent加载类，如果这个逻辑能影响你的插件。说明至少你的插件运行环境中有两份`ShadowAppComponentFactory`的实现。

在这里debug一下重名的类来自于哪里
```
val clazz = pluginClassLoader.loadClass(pluginInfo.appComponentFactory)
                    val classloader1 = clazz.classLoader.loadClass("com.tencent.shadow.core.runtime.ShadowAppComponentFactory").classLoader
                    val classloader2 = ShadowAppComponentFactory::class.java.classLoader
                    if (classloader1 != classloader2) {
                        throw AssertionError("classloader1==${classloader1.javaClass.name} classloader2==${classloader2.javaClass.name}")
                    }
                    ShadowAppComponentFactory::class.java.cast(clazz.newInstance())
```

我无法帮你debug主要还是因为你的测试app代码太复杂，尤其是其中还有很多编译不过的构建脚本，比如`shadow_repository = 'E:\\repository'`。还是建议你今后交流开源项目，要基于项目自身的代码做最小改动复现问题。

**Comment by Heart-Beats** [comment]
大佬说的话铭记于心，我的测试 app 构建脚本中` shadow_repository = 'E:\\repository'`主要是方便引入本地编译的 Shadow SDK，关于这个路径其实已经在脚本中作了存在与否的判断，应该是不会影响构建的。宿主应用看起来比较复杂是因为这个应用我是用来做一些测试 demo 的，所以集成了较多模块，关于 Shadow 的测试还是一个最基础的功能。

言归正传，我早上按您所说的在改了 Shadow 源码的基础作了测试：
```kotlin
//LoadPluginBloc.kt

            val buildAppComponentFactory = executorService.submit(Callable {
                val pluginClassLoader = buildClassLoader.get()
                val pluginInfo = buildPluginInfo.get()
                if (pluginInfo.appComponentFactory != null) {
                    val clazz = pluginClassLoader.loadClass(pluginInfo.appComponentFactory)

                    val classloader1 =
                        clazz.classLoader.loadClass("com.tencent.shadow.core.runtime.ShadowAppComponentFactory").classLoader
                    val classloader2 = ShadowAppComponentFactory::class.java.classLoader
                    if (classloader1 != classloader2) {
                        throw AssertionError("classloader1==${classloader1.javaClass.name} classloader2==${classloader2.javaClass.name}")
                    }

                    ShadowAppComponentFactory::class.java.cast(clazz.newInstance())
                } else ShadowAppComponentFactory()
            })
```
运行到加入的代码时报如下错误：
![image](https://user-images.githubusercontent.com/33248551/122322942-e0c4d600-cf58-11eb-810b-d91d3c718e7d.png)

按您的说法：pluginClassLoader 的 ClassLoader 应该和加载 loader 的 ClassLoader 一致，从而可以正确加载ShadowAppComponentFactory，从报错上来看他们的确应该是不一致的

**Comment by shifujun** [comment]
额，不对，你仔细看下，还没跑到AssertionError就挂了。应该调整一下代码顺序：
```
//LoadPluginBloc.kt

            val buildAppComponentFactory = executorService.submit(Callable {
                val pluginClassLoader = buildClassLoader.get()
                val pluginInfo = buildPluginInfo.get()
                if (pluginInfo.appComponentFactory != null) {
                   val classloader1 =
                        pluginClassLoader.loadClass("com.tencent.shadow.core.runtime.ShadowAppComponentFactory").classLoader
                    val classloader2 = ShadowAppComponentFactory::class.java.classLoader
                    if (classloader1 != classloader2) {
                        throw AssertionError("classloader1==${classloader1.javaClass.name} classloader2==${classloader2.javaClass.name}")
                    }

                    val clazz = pluginClassLoader.loadClass(pluginInfo.appComponentFactory)
                    ShadowAppComponentFactory::class.java.cast(clazz.newInstance())
                } else ShadowAppComponentFactory()
            })

```

我主要想知道一下classloader1和classloader2都是什么，方便我也构造一个这样的场景复现问题。

**Comment by Heart-Beats** [comment]
加了如下调试代码：
```kotlin
                    val classloader1 =
                        pluginClassLoader.loadClass("com.tencent.shadow.core.runtime.ShadowAppComponentFactory").classLoader
                    val classloader2 = ShadowAppComponentFactory::class.java.classLoader

                    mLogger.debug("classloader1 == $classloader1")
                    mLogger.debug("classloader2 == $classloader2")

                    if (classloader1 != classloader2) {
                        throw AssertionError("classloader1==${classloader1.javaClass.name} classloader2==${classloader2.javaClass.name}")
                    }

                    val clazz = pluginClassLoader.loadClass(pluginInfo.appComponentFactory)
                    ShadowAppComponentFactory::class.java.cast(clazz.newInstance())
```

输出日志如下：
``` shell
2021-06-17 11:51:17.086 11167-11216/com.example.zhanglei.myapplication.test D/com.tencent.shadow.core.loader.blocs.LoadPluginBloc: classloader1 == com.tencent.shadow.dynamic.host.ApkClassLoader[DexPathList[[zip file "/data/user/0/com.example.zhanglei.myapplication.test/files/ShadowPluginManager/UnpackedPlugin/my-plugin-manager/9704ba0fadb2c03000de363821d42d8f/plugin-debug.zip/my-loader-debug.apk"],nativeLibraryDirectories=[/data/user/0/com.example.zhanglei.myapplication.test/files/ShadowPluginManager/UnpackedPlugin/my-plugin-manager/lib/D7EF5579-6842-405C-B582-896ABB2969A2_lib, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]]
2021-06-17 11:51:17.086 11167-11216/com.example.zhanglei.myapplication.test D/com.tencent.shadow.core.loader.blocs.LoadPluginBloc: classloader2 == com.tencent.shadow.dynamic.host.ApkClassLoader[DexPathList[[zip file "/data/user/0/com.example.zhanglei.myapplication.test/files/ShadowPluginManager/UnpackedPlugin/my-plugin-manager/9704ba0fadb2c03000de363821d42d8f/plugin-debug.zip/my-loader-debug.apk"],nativeLibraryDirectories=[/data/user/0/com.example.zhanglei.myapplication.test/files/ShadowPluginManager/UnpackedPlugin/my-plugin-manager/lib/D7EF5579-6842-405C-B582-896ABB2969A2_lib, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]]

2021-06-17 11:51:17.387 11167-11186/com.example.zhanglei.myapplication.test E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:82)
        at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:43)
        at android.os.Binder.execTransactInternal(Binder.java:1028)
        at android.os.Binder.execTransact(Binder.java:1001)
     Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$1.run(Unknown Source:51)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: java.util.concurrent.ExecutionException: java.lang.ClassCastException: Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildApplication$1.call(Unknown Source:37)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildApplication$1.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:929) 
     Caused by: java.lang.ClassCastException: Cannot cast androidx.core.app.CoreComponentFactory to com.tencent.shadow.core.runtime.ShadowAppComponentFactory
        at java.lang.Class.cast(Class.java:2446)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildAppComponentFactory$1.call(Unknown Source:205)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildAppComponentFactory$1.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:929) 
```

**Comment by shifujun** [comment]
https://github.com/Heart-Beats/ShadowPlugin/blob/0fba34c07f0546ff1e00b2776a4e2d244690b639/my-runtime/build.gradle#L37

应该是你的runtime的这个依赖把`androidx.core.app.CoreComponentFactory`打包进去了。这个runtime是为了动态加载`activity-container`的，所以它是PathClassLoader的parent，这里面是不能有其他类的。只需要把这个依赖去掉就可以了。

在Shadow的sample中可以在runtime模块加入`implementation "androidx.core:core:1.1.0"`复现这个问题。

**Comment by Heart-Beats** [comment]
确实是的，runtime 和 loader 按 Android 工程模板创建的，当时删除时对 `androidx.core:core` 这个依赖不确定作为 app 缺少此依赖是否可行就保留了，在没改 PluginClassLoader 加载之前是没问题的，也算是自己给自己挖了个坑，
![image](https://user-images.githubusercontent.com/33248551/122353739-eb946080-cf82-11eb-9804-8319286d37ec.png)
