### ISSUE TITLE
报错：重复添加 ContentProvider

### ISSUE THREAD

**Issue by tianmeng0111** [Tencent/Shadow#532]
Caused by: java.lang.RuntimeException: 重复添加 ContentProvider
2021-06-16 14:47:08.358 26336-26442/com.dlhy.hyhome E/DEBUG:     at com.tencent.shadow.core.loader.managers.PluginContentProviderManager.addContentProviderInfo(Unknown Source:82)
2021-06-16 14:47:08.358 26336-26442/com.dlhy.hyhome E/DEBUG:     at com.tencent.shadow.core.loader.managers.ComponentManager.addPluginApkInfo(Unknown Source:148)
2021-06-16 14:47:08.358 26336-26442/com.dlhy.hyhome E/DEBUG:     at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildRunningPlugin$1.run(Unknown Source:78)
2021-06-16 14:47:08.358 26336-26442/com.dlhy.hyhome E/DEBUG:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2021-06-16 14:47:08.358 26336-26442/com.dlhy.hyhome E/DEBUG:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)

用改同一uuid的方式打开多插件的，打开第一个插件再打开第二个发现报这个错误，请问如何解决

**Comment by shifujun** [comment]
这里就是在模仿系统安装apk的逻辑，不能运行有相同的`authority`的Provider被一同安装。应该是你的多个插件有相同的Provider吧。

可以debug一下addContentProviderInfo的添加过程，看看哪个插件添加过同名的Provider。

**Comment by tianmeng0111** [comment]
找了一遍插件中的第三方包，里面确实有provider，是用了相同的authority，问题解决！！
感谢解惑！！
看了下demo可以debug，插件好像debug走不到，在插件的项目中如何debug走到源码那呢？

**Comment by shifujun** [comment]
Debug不受影响的，正常attach debugger到插件进程就行。如果在Sample中的哪个代码debug不了，可以说明一下怎么运行的，attach到什么进程了，debug的哪行。另外提issue讨论吧。

**Comment by tianmeng0111** [comment]
好的我再看看 感谢！
