### ISSUE TITLE
不支持JobService

### ISSUE THREAD

**Issue by weithink** [Tencent/Shadow#566]
麻烦帮忙看下这个问题，插件中的第三方sdk的service找不到，难道说这个service需要在宿主中再次注册么？

Process: com.tencent.shadow.sample.host:plugin, PID: 9510
    java.lang.IllegalArgumentException: No such service ComponentInfo{com.tencent.shadow.sample.host/easypay.utils.EasypayLoaderService}
        at android.os.Parcel.readException(Parcel.java:2020)
        at android.os.Parcel.readException(Parcel.java:1962)
        at android.app.job.IJobScheduler$Stub$Proxy.enqueue(IJobScheduler.java:211)
        at android.app.JobSchedulerImpl.enqueue(JobSchedulerImpl.java:53)
        at androidx.core.app.JobIntentService$JobWorkEnqueuer.enqueueWork(JobIntentService.java:342)
        at androidx.core.app.JobIntentService.enqueueWork(JobIntentService.java:522)
        at androidx.core.app.JobIntentService.enqueueWork(JobIntentService.java:500)
        at easypay.utils.EasypayLoaderService.enqueueWork(EasypayLoaderService.java:38)
        at easypay.manager.PaytmAssist.downloadPaymentConfig(PaytmAssist.java:551)
        at easypay.manager.PaytmAssist.initAssist(PaytmAssist.java:510)
        at easypay.manager.PaytmAssist.access$400(PaytmAssist.java:83)
        at easypay.manager.PaytmAssist$2$1.run(PaytmAssist.java:458)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by shifujun** [comment]
应该不用。可能是`JobIntentService`有什么特别的用法没支持。我查查看。

**Comment by weithink** [comment]
> 应该不用。可能是`JobIntentService`有什么特别的用法没支持。我查查看。

有解决方案了么

**Comment by shifujun** [comment]
这个JobIntentService本身还是挺复杂的。可以有两种方案来支持：
1. 按照它的逻辑，去掉不能支持的后台唤醒等能力，自己实现一个。我花了点时间，试图写一个最简单的实现。https://github.com/shifujun/Shadow/commit/6510fe731da6b1a47e5fc99990d155d81fb9721c 基本的能力还差点。但是也能看出来这种做法还是很复杂。
2. 在宿主中注册一个JobIntentService，将插件的JobIntentService都委托给它调度。这种做法最可靠。只是旧版本的宿主没法动态添加这个壳子JobIntentService。这个方案明天看看实现一个应该会容易许多。

**Comment by shifujun** [comment]
这个JobService支持起来真有些麻烦呢。它的工作方式是这样的：App要声明一个Service，这个Service的Binder是由系统提供的`JobServiceEngine`实现的。这个Binder的接口还是个非公开的API。

最重要的是这个Service的使用方是系统，而不是App里的其他代码。这与Shadow目前支持的App内的Service有很大区别。

所以，这里关键是要支持插件Service直接给系统使用。也就是说Shadow要提供另一种Service的支持方式。在宿主里注册1对1的Service代理，把插件的Service完全委托给壳子。然后再把`new JobInfo.Builder(jobId, jobService)`调用的`jobService`换成宿主中的Service名字。在这种方案下，Service的生命周期才能由系统的bind操作正确触发。Service的binder也是正常的`JobServiceEngine`实现。

这个如果我们自己的业务遇到这种第三方SDK，我可能要考虑针对这个SDK做一些替换修改了。因为它不太可能用到JobService的全部能力。

暂时恐怕结论就是这个Service是提供给系统调用的，Shadow目前无法支持。:(

**Comment by shifujun** [comment]
要么就基于https://github.com/shifujun/Shadow/commit/6510fe731da6b1a47e5fc99990d155d81fb9721c 的做法慢慢适配。这个结构反正是拿到了提交的job和分发job的逻辑。是可以在当前进程中自己调度的。只是我不知道你这个Easypay的sdk需要什么样的调度逻辑。

**Comment by weithink** [comment]
好的，谢谢大佬
