### ISSUE TITLE
由于第三方sdk中写死的调用，有没有什么办法可以解决？

### ISSUE THREAD

**Issue by weithink** [Tencent/Shadow#569]
### 这种情况还是会报错， unable find activity

```
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.shadow.sample.host/com.razorpay.CheckoutActivity}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1948)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1760)
        at android.app.Activity.startActivityForResult(Activity.java:5236)
        at android.app.Activity.startActivityFromFragment(Activity.java:5212)
        at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:7769)
        at android.app.Fragment.startActivityForResult(Fragment.java:1095)
        at android.app.Fragment.startActivityForResult(Fragment.java:1084)
        at com.razorpay.Checkout.onCreate(:304)
        at android.app.Fragment.performCreate(Fragment.java:2489)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1237)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2412)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2191)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2147)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2048)
        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:719)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

```

### 三方sdk中的调用代码部分

```


 public void onCreate(Bundle var1) {
        super.onCreate(var1);
        if (this.D$_X_ != null) {
            Intent var2;
            (var2 = new Intent()).setComponent(new ComponentName(this.getActivity().getPackageName(), "com.razorpay.CheckoutActivity"));
            if (R$$r_ > 0L) {
                var2.putExtra("PRELOAD_COMPLETE_DURATION", R$$r_);
            } else if (Q_$2$ > 0L) {
                var2.putExtra("PRELOAD_ABORT_DURATION", Q_$2$);
            }
            var2.putExtra("OPTIONS", this.D$_X_.toString());
            var2.putExtra("IMAGE", this.E$_j$);
            var2.putExtra("DISABLE_FULL_SCREEN", this.B$$W$);
            this.D$_X_ = null;
            this.startActivityForResult(var2, 62442);
        }

    }

```

**Comment by shifujun** [comment]
这个可以利用Transform把`setComponent`的调用改成：`MyClass.setComponent(intent, compoentName)`这样的形式。然后我们实现`MyClass`，在这里任意修改逻辑就行了。在Shadow的里搜一下`redirectMethodCallToStatic`调用的代码就看到怎么用了。

不过第三方SDK里想要启动这个`com.razorpay.CheckoutActivity`，难道不是第三方SDK自带的Activity吗？如果是的话，正常情况下它应该也是插件Activity，应该是可以正常启动的，不用这么修改。应该有什么别的问题导致的。是不是第三方SDK的aar中没有把它写到Manifest中，你也没有把它写到插件的Manifest中？

**Comment by weithink** [comment]
> 这个可以利用Transform把`setComponent`的调用改成：`MyClass.setComponent(intent, compoentName)`这样的形式。然后我们实现`MyClass`，在这里任意修改逻辑就行了。在Shadow的里搜一下`redirectMethodCallToStatic`调用的代码就看到怎么用了。
> 
> 不过第三方SDK里想要启动这个`com.razorpay.CheckoutActivity`，难道不是第三方SDK自带的Activity吗？如果是的话，正常情况下它应该也是插件Activity，应该是可以正常启动的，不用这么修改。应该有什么别的问题导致的。是不是第三方SDK的aar中没有把它写到Manifest中，你也没有把它写到插件的Manifest中？

我看了下，第三方sdk中是有写这个activity的，奇怪的是，按照你第二种方案的说法，应该是可以正常调起的才对

下面是sdk中的activity

```
 <application>
        <receiver android:name="com.razorpay.RzpTokenReceiver" >
            <intent-filter>
                <action android:name="rzp.device_token.share" />
            </intent-filter>
        </receiver>

        <activity
            android:name="com.razorpay.CheckoutActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:theme="@style/CheckoutTheme" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <data
                    android:host="rzp.io"
                    android:scheme="io.rzp" />
            </intent-filter>
        </activity>
    </application>
```

如果按照第二种说法，那这个原因还要再找找。

**Comment by weithink** [comment]
> 这个可以利用Transform把`setComponent`的调用改成：`MyClass.setComponent(intent, compoentName)`这样的形式。然后我们实现`MyClass`，在这里任意修改逻辑就行了。在Shadow的里搜一下`redirectMethodCallToStatic`调用的代码就看到怎么用了。
> 
> 不过第三方SDK里想要启动这个`com.razorpay.CheckoutActivity`，难道不是第三方SDK自带的Activity吗？如果是的话，正常情况下它应该也是插件Activity，应该是可以正常启动的，不用这么修改。应该有什么别的问题导致的。是不是第三方SDK的aar中没有把它写到Manifest中，你也没有把它写到插件的Manifest中？

我看了下编译出来的包Manifest里面也是有注册这个avtivity的
```
         <activity
            android:theme="@ref/0x7f1300fb"
            android:name="com.razorpay.CheckoutActivity"
            android:configChanges="0x4b0">

            <intent-filter>

                <action
                    android:name="android.intent.action.MAIN" />

                <data
                    android:scheme="io.rzp"
                    android:host="rzp.io" />
            </intent-filter>
        </activity>
```

**Comment by shifujun** [comment]
那需要debug一下插件的加载过程中，是否解析到了这个Activity：
https://github.com/Tencent/Shadow/blob/master/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/ComponentManager.kt#L174-L178

也要看一下`this.startActivityForResult(var2, 62442);`中的`this`在运行时是否是一个`ShadowActivity`，是的话，应该会进一步调用到：
https://github.com/Tencent/Shadow/blob/master/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/ComponentManager.kt#L75

在这里需要debug一下`pluginIntent.isPluginComponent()`的过程。

**Comment by weithink** [comment]
> 那需要debug一下插件的加载过程中，是否解析到了这个Activity：
> https://github.com/Tencent/Shadow/blob/master/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/ComponentManager.kt#L174-L178
> 
> 也要看一下`this.startActivityForResult(var2, 62442);`中的`this`在运行时是否是一个`ShadowActivity`，是的话，应该会进一步调用到：
> https://github.com/Tencent/Shadow/blob/master/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/managers/ComponentManager.kt#L75
> 
> 在这里需要debug一下`pluginIntent.isPluginComponent()`的过程。

1.在onBindContainerActivity 中输出了所有解析的activity 其中是有这个activity的
2. 我在传参的地方打印了传入的参数context.getParent()=com.tencent.shadow.core.runtime.ShadowActivity

:(  调试起来有些麻烦，所以回复得慢了些

接下来我将参数换成了context.getParent()
#### 之后没有报unable find activity 的问题了。

接下来出现了另外的一个问题

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference

at com.razorpay.U$_z$.a_$P$(:38)
at com.razorpay.Checkout.open(:15420)
```

我查了下，是这个sdk中有相关的SharedPreferences 


```
  public static SharedPreferences a_$P$(Context var0) {
        int var10000 = 2 % 2;
        var10000 = d__1_ + 55;
        Q_$2$ = var10000 % 128;
        switch(var10000 % 2 != 0 ? 0 : 1) {
        case 0:
            int var10001 = ((Object[])null).length;
            if (R$$r_ != null) {
                return R$$r_;
            }
            break;
        case 1:
        default:
            switch(R$$r_ == null ? 1 : 0) {
            case 0:
                return R$$r_;
            case 1:
            }
        }

        var10000 = Q_$2$ + 109;
        d__1_ = var10000 % 128;
        if (var10000 % 2 == 0) {
        }

        R$$r_ = var0.getSharedPreferences("rzp_preference_private", 0);
        var10000 = 2 % 2;
        return R$$r_;
    }
```


不知道我这种操作方向上对不对，还请大佬指点下
@shifujun

**Comment by shifujun** [comment]
这里`context.getParent()=com.tencent.shadow.core.runtime.ShadowActivity`，这个`getParent()`不为`null`，说明这里用了子Activity。这是Shadow比较少考虑到的场景，可能是有bug。

我比较想知道这个Child Activity是什么样的调用启动的。你说的”传参“是指你传给`com.razorpay.Checkout`的context吗？我考虑`com.razorpay.Checkout`可能是需要一个context来完成它想start Activity的过程。

我猜测这里可能是`com.razorpay.Checkout`预先通过什么逻辑启动了子Activity，然后可能想让你把子Activity作为context传给它，然后它再通过`getParent()`拿到父Activity，然后去调`getSharedPreferences`。现在你直接传进去了`context.getParent()`，它再getParent()就得到null了。

猜的可能不靠谱。你可以贴一下`com.razorpay.Checkout`的完整的反编译代码看看。

**Comment by weithink** [comment]
### 调用sdk的方式是这样的：

```
checkout.open(Activity var1, JSONObject var2);
```

### 这个是完整反编译代码

```

package com.razorpay;

import android.annotation.SuppressLint;
import android.app.Activity;
import android.app.Fragment;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences.Editor;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.text.TextUtils;
import android.webkit.CookieManager;
import android.webkit.WebChromeClient;
import android.webkit.WebResourceError;
import android.webkit.WebResourceRequest;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.Toast;
import com.razorpay.U._z.;
import com.razorpay.r._Y_.1;
import java.lang.reflect.Method;
import java.util.HashMap;
import org.json.JSONException;
import org.json.JSONObject;

public class Checkout extends Fragment {
    public static final int NETWORK_ERROR = 2;
    public static final int INVALID_OPTIONS = 3;
    public static final int PAYMENT_CANCELED = 0;
    public static final int TLS_ERROR = 6;
    public static final int INCOMPATIBLE_PLUGIN = 7;
    public static final int RZP_REQUEST_CODE = 62442;
    @SuppressLint({"StaticFieldLeak"})
    private static WebView d__1_;
    private static long R$$r_;
    private static long Q_$2$;
    private static boolean G__G_;
    private String a_$P$;
    private JSONObject D$_X_;
    private Activity b__J_;
    private String r$_Y_;
    private boolean B$$W$;
    private int E$_j$;
    private static PaymentData Y$_o$;
    private boolean E$_6$;

    public Checkout() {
    }

    /** @deprecated */
    @Deprecated
    public final void setPublicKey(String var1) {
        this.a_$P$ = var1;
    }

    public final void setImage(int var1) {
        this.E$_j$ = var1;
    }

    public final void setKeyID(String var1) {
        this.setPublicKey(var1);
    }

    public final void setFullScreenDisable(boolean var1) {
        this.B$$W$ = var1;
    }

    public final void open(Activity var1, JSONObject var2) {
        if (TextUtils.isEmpty(this.a_$P$)) {
            this.a_$P$ = BaseUtils.getKeyId(var1);
        }

        if (a_$P$(var1).getString("advertising_id", (String)null) == null) {
            AdvertisingIdUtil.R$$r_(var1, new 1(var1));
        }

        if (TextUtils.isEmpty(this.a_$P$)) {
            throw new RuntimeException("Please set your Razorpay API key in AndroidManifest.xml");
        } else if (var2 != null && var2.length() != 0) {
            try {
                var2.put("key", this.a_$P$);
            } catch (JSONException var10) {
                AnalyticsUtil.reportError(var10, "warning", var10.getMessage());
            }

            long var4 = System.nanoTime();

            try {
                if (d__1_ != null) {
                    long var6 = ((Long)d__1_.getTag()).longValue();
                    BaseUtils.nanoTimeToSecondsString(Q_$2$ = var4 - var6, 2);
                }
            } catch (Exception var9) {
            }

            try {
                d__1_.stopLoading();
            } catch (Exception var8) {
            }

            d__1_ = null;
            this.D$_X_ = var2;
            this.r$_Y_ = var1.getClass().getName();
            this.b__J_ = var1;
            var1.getFragmentManager().beginTransaction().add(this, (String)null).commit();
        } else {
            throw new RuntimeException("Checkout options cannot be null or empty");
        }
    }

    public static void preload(Context var0) {
        R$$r_ = 0L;
        Q_$2$ = 0L;
        G__G_ = false;
        var0 = var0.getApplicationContext();
        d__1_ = new WebView(var0);
        BaseUtils.setWebViewSettings(var0, d__1_, false);
        d__1_.setWebViewClient(new WebViewClient() {
            private long a_$P$;

            public final void onPageStarted(WebView var1, String var2, Bitmap var3) {
                this.a_$P$ = System.nanoTime();
                if (Checkout.d__1_ == null) {
                    HashMap var4;
                    (var4 = new HashMap()).put("error_location", "Checkout->Preload()->onPageStarted");
                    AnalyticsUtil.trackEvent(AnalyticsEvent.WEB_VIEW_UNEXPECTED_NULL, var4);
                } else {
                    Checkout.d__1_.setTag(this.a_$P$);
                }
            }

            public final void onReceivedError(WebView var1, int var2, String var3, String var4) {
                Checkout.d__1_();
            }

            public final void onReceivedError(WebView var1, WebResourceRequest var2, WebResourceError var3) {
                super.onReceivedError(var1, var2, var3);
                Checkout.d__1_();
            }

            public final void onPageFinished(WebView var1, String var2) {
                long var3 = System.nanoTime();
                if (!Checkout.G__G_) {
                    Checkout.R$$r_ = var3 - this.a_$P$;
                    BaseUtils.nanoTimeToSecondsString(Checkout.R$$r_, 2);
                }

                Checkout.Q_$2$();
            }
        });
        d__1_.setWebChromeClient(new WebChromeClient() {
            public final void onProgressChanged(WebView var1, int var2) {
            }
        });
        d__1_.loadUrl("https://api.razorpay.com/v1/checkout/public");
    }

    public void onCreate(Bundle var1) {
        super.onCreate(var1);
        if (this.D$_X_ != null) {
            Intent var2;
            (var2 = new Intent()).setComponent(new ComponentName(this.getActivity().getPackageName(), "com.razorpay.CheckoutActivity"));
            if (R$$r_ > 0L) {
                var2.putExtra("PRELOAD_COMPLETE_DURATION", R$$r_);
            } else if (Q_$2$ > 0L) {
                var2.putExtra("PRELOAD_ABORT_DURATION", Q_$2$);
            }

            var2.putExtra("OPTIONS", this.D$_X_.toString());
            var2.putExtra("IMAGE", this.E$_j$);
            var2.putExtra("DISABLE_FULL_SCREEN", this.B$$W$);
            this.D$_X_ = null;
            this.startActivityForResult(var2, 62442);
        }

    }

    public void onActivityResult(int var1, int var2, Intent var3) {
        if (var1 == 62442) {
            this.b__J_ = this.getActivity();
            this.r$_Y_ = this.b__J_.getClass().getName();
            Bundle var6;
            String var7 = var3 != null && (var6 = var3.getExtras()) != null ? var6.getString("RESULT") : null;
            if (var2 == 0 && (var7 == null || !var7.contains("error"))) {
                var7 = "Payment Cancelled";
            }

            a_$P$(this.b__J_, var7);
            G__G_(var2, var7);
            if (var2 == 1) {
                String var8;
                if ((var8 = Y$_o$.getPaymentId()) != null) {
                    this.E$_6$ = true;
                    this.onSuccess(var8);
                }

                if (this.E$_6$) {
                    R$$r_(1, 1);
                }
            } else if (var2 == 4) {
                Checkout var9 = this;
                if (this.getActivity() instanceof ExternalWalletListener) {
                    try {
                        ExternalWalletListener var10 = (ExternalWalletListener)var9.getActivity();
                        String var11;
                        if (!TextUtils.isEmpty(var11 = Y$_o$.getExternalWallet())) {
                            var10.onExternalWalletSelected(var11, Y$_o$);
                            AnalyticsUtil.trackEvent(AnalyticsEvent.MERCHANT_EXTERNAL_WALLET_SELECTED_CALLED);
                            AnalyticsUtil.postData();
                        }
                    } catch (Exception var5) {
                        G__G_(this.b__J_, 4, "threw_error", var5);
                    }
                } else {
                    G__G_(this.b__J_, 4, "dne", new Exception());
                }
            } else {
                this.E$_6$ = true;
                this.onError(var2, var7);
                if (this.E$_6$) {
                    R$$r_(var2, 1);
                }
            }

            try {
                this.getActivity().getFragmentManager().beginTransaction().remove(this).commit();
            } catch (Exception var4) {
                AnalyticsUtil.reportError(var4, "error", var4.getMessage());
            }
        }
    }

    public void onSuccess(String var1) {
        this.E$_6$ = false;
        if (!this.Q_$2$(var1)) {
            String var2 = var1;
            Checkout var9 = this;
            Method var3 = null;

            try {
                Class[] var6 = new Class[]{String.class};
                String var5 = "onPaymentSuccess";
                var3 = Class.forName(var9.r$_Y_).getMethod(var5, var6);
            } catch (Exception var7) {
                G__G_(this.b__J_, 1, "dne", var7);
            }

            try {
                Object[] var10 = new Object[]{var2};
                if (var3 != null) {
                    var3.invoke(var9.b__J_, var10);
                }

                R$$r_(1, 2);
                return;
            } catch (Exception var8) {
                G__G_(this.b__J_, 1, "threw_error", var8);
            }
        }

    }

    public void onError(int var1, String var2) {
        this.E$_6$ = false;
        if (!this.Q_$2$(var1, var2)) {
            String var3 = var2;
            int var11 = var1;
            Checkout var10 = this;
            Method var4 = null;

            try {
                Class[] var7 = new Class[]{Integer.TYPE, String.class};
                String var6 = "onPaymentError";
                var4 = Class.forName(var10.r$_Y_).getMethod(var6, var7);
            } catch (Exception var8) {
                G__G_(this.b__J_, var11, "dne", var8);
            }

            try {
                Object[] var12 = new Object[]{var11, var3};
                if (var4 != null) {
                    var4.invoke(var10.b__J_, var12);
                }

                R$$r_(var11, 2);
                return;
            } catch (Exception var9) {
                G__G_(this.b__J_, var11, "threw_error", var9);
            }
        }

    }

    private boolean Q_$2$(int var1, String var2) {
        if (this.getActivity() instanceof PaymentResultListener) {
            try {
                ((PaymentResultListener)this.getActivity()).onPaymentError(var1, var2);
                R$$r_(var1, 3);
            } catch (Exception var3) {
                G__G_(this.b__J_, var1, "threw_error", var3);
            }

            return true;
        } else if (this.getActivity() instanceof PaymentResultWithDataListener) {
            try {
                ((PaymentResultWithDataListener)this.getActivity()).onPaymentError(var1, var2, Y$_o$);
                R$$r_(var1, 3);
            } catch (Exception var4) {
                G__G_(this.b__J_, var1, "threw_error", var4);
            }

            return true;
        } else {
            return false;
        }
    }

    private boolean Q_$2$(String var1) {
        if (this.getActivity() instanceof PaymentResultListener) {
            try {
                ((PaymentResultListener)this.getActivity()).onPaymentSuccess(var1);
                R$$r_(1, 3);
            } catch (Exception var2) {
                G__G_(this.b__J_, 1, "threw_error", var2);
            }

            return true;
        } else if (this.getActivity() instanceof PaymentResultWithDataListener) {
            try {
                ((PaymentResultWithDataListener)this.getActivity()).onPaymentSuccess(var1, Y$_o$);
                R$$r_(1, 3);
            } catch (Exception var3) {
                G__G_(this.b__J_, 1, "threw_error", var3);
            }

            return true;
        } else {
            return false;
        }
    }

    private static void R$$r_(int var0, int var1) {
        try {
            HashMap var2;
            (var2 = new HashMap()).put("integration_type", Integer.toString(var1));
            if (var0 == 1) {
                AnalyticsUtil.trackEvent(AnalyticsEvent.MERCHANT_ON_SUCCESS_CALLED, var2);
            } else {
                AnalyticsUtil.trackEvent(AnalyticsEvent.MERCHANT_ON_ERROR_CALLED, var2);
            }

            AnalyticsUtil.postData();
        } catch (Exception var3) {
            AnalyticsUtil.reportError(var3, "warning", var3.getMessage());
        }
    }

    private static void G__G_(int var0, String var1) {
        try {
            AnalyticsUtil.addProperty("onActivityResult result", new AnalyticsProperty(var1, com.razorpay.AnalyticsProperty.Q_.2..R$$r_));
            AnalyticsUtil.addProperty("onActivityResult resultCode", new AnalyticsProperty(String.valueOf(var0), com.razorpay.AnalyticsProperty.Q_.2..R$$r_));
            if (var0 == 1) {
                AnalyticsUtil.trackEvent(AnalyticsEvent.CALLING_ON_SUCCESS);
            } else if (var0 == 4) {
                AnalyticsUtil.trackEvent(AnalyticsEvent.CALLING_EXTERNAL_WALLET_SELECTED);
            } else {
                AnalyticsUtil.trackEvent(AnalyticsEvent.CALLING_ON_ERROR);
            }

            AnalyticsUtil.postData();
        } catch (Exception var2) {
            AnalyticsUtil.reportError(var2, "warning", var2.getMessage());
        }
    }

    private static void G__G_(Activity var0, int var1, String var2, Exception var3) {
        String var4;
        String var5;
        if (var1 == 1) {
            var4 = "onPaymentSuccess";
            var5 = "success";
        } else if (var1 == 4) {
            var4 = "onExternalWalletSelected";
            var5 = "redirected";
        } else {
            var4 = "onPaymentError";
            var5 = "error";
        }

        try {
            HashMap var6;
            (var6 = new HashMap()).put("event_details", var3.getMessage());
            var6.put("event_type", var3.getMessage());
            var6.put("payment_status", var5);
            AnalyticsUtil.trackEvent(AnalyticsEvent.HANDOVER_ERROR, var6);
            AnalyticsUtil.postData();
        } catch (Exception var7) {
            AnalyticsUtil.reportError(var7, "error", var7.getMessage());
        }

        if (var2.equals("dne")) {
            if (var1 == 4) {
                Toast.makeText(var0, "Error: ExternalWalletListener probably not implemented in your activity", 0).show();
            } else {
                Toast.makeText(var0, (new StringBuilder("Error: ")).append(var4).append(" probably not implemented in your activity").toString(), 0).show();
            }
        } else if (var2.equals("threw_error")) {
            Toast.makeText(var0, (new StringBuilder("Your ")).append(var4).append(" method is throwing an error. Wrap the entire code of the method inside a try catch.").toString(), 0).show();
        }

        AnalyticsUtil.reportError(var3, "error", var3.getMessage());
    }

    private static void a_$P$(Activity var0, String var1) {
        (Y$_o$ = new PaymentData()).a_$P$(a_$P$(var0).getString("rzp_user_contact", (String)null));
        Y$_o$.d__1_(a_$P$(var0).getString("rzp_user_email", (String)null));

        try {
            JSONObject var3 = new JSONObject(var1);
            Y$_o$.d__1_(var3);
            if (var3.has("razorpay_payment_id")) {
                Y$_o$.G__G_(var3.getString("razorpay_payment_id"));
            }

            if (var3.has("razorpay_order_id")) {
                Y$_o$.R$$r_(var3.getString("razorpay_order_id"));
            }

            if (var3.has("razorpay_signature")) {
                Y$_o$.Q_$2$(var3.getString("razorpay_signature"));
            }

            if (var3.has("external_wallet")) {
                Y$_o$.r$_Y_(var3.getString("external_wallet"));
            }

        } catch (JSONException var2) {
            AnalyticsUtil.reportError(var2, "error", var2.getMessage());
        }
    }

    public static void handleActivityResult(Activity var0, int var1, int var2, Intent var3, PaymentResultWithDataListener var4, ExternalWalletListener var5) {
        if (var1 == 62442) {
            Bundle var9;
            String var10 = var3 != null && (var9 = var3.getExtras()) != null ? var9.getString("RESULT") : null;
            if (var2 == 0) {
                var10 = "Payment Cancelled";
            }

            a_$P$(var0, var10);
            G__G_(var2, var10);
            if (var2 == 1) {
                try {
                    var10 = Y$_o$.getPaymentId();
                    var4.onPaymentSuccess(var10, Y$_o$);
                } catch (Exception var6) {
                    G__G_(var0, var2, "threw_error", var6);
                }
            } else {
                if (var2 == 4) {
                    if (var5 != null) {
                        try {
                            var5.onExternalWalletSelected(Y$_o$.getExternalWallet(), Y$_o$);
                            return;
                        } catch (Exception var7) {
                            G__G_(var0, var2, "threw_error", var7);
                            return;
                        }
                    }
                } else {
                    try {
                        var4.onPaymentError(var2, var10, Y$_o$);
                        return;
                    } catch (Exception var8) {
                        G__G_(var0, var2, "threw_error", var8);
                    }
                }

            }
        }
    }

    public static void clearUserData(Context var0) {
        Editor var1;
        (var1 = G__G_(var0)).putString("rzp_user_contact", (String)null);
        var1.commit();
        (var1 = G__G_(var0)).putString("rzp_user_email", (String)null);
        var1.commit();
        Q_$2$(var0).putString("rzp_device_token", (String)null).apply();
        CookieManager.getInstance().setCookie("https://api.razorpay.com", "razorpay_api_session=");
    }

    public static class Builder {
        private String a_$P$;
        private int d__1_;
        private boolean R$$r_;

        public Builder() {
        }

        public Checkout.Builder setKeyId(String var1) {
            this.a_$P$ = var1;
            return this;
        }

        public Checkout.Builder setImage(int var1) {
            this.d__1_ = var1;
            return this;
        }

        public Checkout.Builder disableFullscreen(boolean var1) {
            this.R$$r_ = var1;
            return this;
        }

        public Checkout build() {
            Checkout var1;
            (var1 = new Checkout()).setFullScreenDisable(this.R$$r_);
            var1.setImage(this.d__1_);
            if (this.a_$P$ != null) {
                var1.setKeyID(this.a_$P$);
            }

            return var1;
        }
    }
}

```

**Comment by shifujun** [comment]
那看起来`checkout.open(Activity var1, JSONObject var2);`就是这个Fragment的帮助方法，也没有写的很奇怪。而且它就是直接用`var1`去调用`com.razorpay.U$_z$.a_$P$`了。那就是单纯的因为你传给它的`context.getParent()`就是`null`的关系。

你可能搞错了`context.getParent()=com.tencent.shadow.core.runtime.ShadowActivity`的context是哪个对象了。

改传`context.getParent()`后没有报"unable find activity "只是因为还没有执行到原来的代码，也就是` var1.getFragmentManager().beginTransaction().add(this, (String)null).commit();`触发的后来的`onCreate()`。

这里的代码确实没什么太奇怪的，建议还是debug一下`this.startActivityForResult(var2, 62442);`执行后，一直到`pluginIntent.isPluginComponent()`时，isPluginComponent的判断过程，看看Shadow为什么认为这个Intent不是插件的Intent。

**Comment by weithink** [comment]
大佬，不走打的断点，我只能输出log来调试，这个比较麻烦。
请问正确的debug 需要怎样设置么？

**Comment by shifujun** [comment]
只要你插件用的Shadow是没有混淆过的debug版。你就可以直接用Android Studio打开Shadow这个工程，然后
![image](https://user-images.githubusercontent.com/3535204/127473092-310f6c31-34d3-4248-9218-d9a1a6fd960c.png)
到你插件的进程，就可以正常调试Shadow了。这个对于任何库来说都是一样的。

**Comment by weithink** [comment]
我的错，process没选进程。。。

**Comment by weithink** [comment]
debug 没走到这些点就直接crash

![6](https://user-images.githubusercontent.com/10632711/127480815-2f5f36d5-20d8-4774-b695-d3414b2be03d.png)

@shifujun

**Comment by shifujun** [comment]
建议从`this.startActivityForResult(var2, 62442);`调用开始步进。

**Comment by weithink** [comment]
这个是和主项目作为插件打进去的，这可如何打点，要不我加你即时通讯的联系方式，给我来个直接的指点迷津？

**Comment by shifujun** [comment]
应该不用了。我知道问题了，是ShadowFragmentSupport没有支持startActivityForResult。这个很好支持，我等下提个PR。

**Comment by weithink** [comment]
> 应该不用了。我知道问题了，是ShadowFragmentSupport没有支持startActivityForResult。这个很好支持，我等下提个PR。

大佬我加你q了

**Comment by weithink** [comment]
大佬，加上你更新的代码后出现一个问题
@shifujun 

![image](https://user-images.githubusercontent.com/10632711/127617028-d450683c-b4c6-4b5c-a063-df1f9154d5b1.png)


```
2021-07-30 15:26:24.596 31963-31963/com.tencent.shadow.sample.host E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.shadow.sample.host:plugin, PID: 31963
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity}: java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class com.tencent.shadow.core.runtime.ShadowActivity]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class com.tencent.shadow.core.runtime.ShadowActivity]
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(ShadowActivityDelegate.kt:152)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7088)
        at android.app.Activity.performCreate(Activity.java:7079)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6651) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
     Caused by: java.lang.NoSuchMethodException: <init> [class com.tencent.shadow.core.runtime.ShadowActivity]
        at java.lang.Class.getConstructor0(Class.java:2320)
        at java.lang.Class.getDeclaredConstructor(Class.java:2166)
        at com.razorpay.RzpAssist.<init>(:82)
        at com.razorpay.Y_$B$.setUpAddOn(:28)
        at com.razorpay.b__J_.onCreate(:6215)
        at com.razorpay.B$$W$.onCreate(:23)
        at com.razorpay.CheckoutActivity.onCreate(:8)
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(ShadowActivityDelegate.kt:149)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84) 
        at android.app.Activity.performCreate(Activity.java:7088) 
        at android.app.Activity.performCreate(Activity.java:7079) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6651) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
```

**Comment by shifujun** [comment]
> Caused by: java.lang.NoSuchMethodException: <init> [class com.tencent.shadow.core.runtime.ShadowActivity]
        at java.lang.Class.getConstructor0(Class.java:2320)
        at java.lang.Class.getDeclaredConstructor(Class.java:2166)
        at com.razorpay.RzpAssist.<init>(:82)

这不是它在反射出错了么？跟这个issue原本的问题没关系的。

**Comment by weithink** [comment]
> > Caused by: java.lang.NoSuchMethodException:  [class com.tencent.shadow.core.runtime.ShadowActivity]
> > at java.lang.Class.getConstructor0(Class.java:2320)
> > at java.lang.Class.getDeclaredConstructor(Class.java:2166)
> > at com.razorpay.RzpAssist.(:82)
> 
> 这不是它在反射出错了么？跟这个issue原本的问题没关系的。

在打包的时候 transform 会把有实现的接口也带上么？
@shifujun

**Comment by shifujun** [comment]
> 有实现的接口也带上

什么是”有实现的接口“？什么是”带上“？

你可以还是把`com.razorpay.RzpAssist.(:82)`反编译了看一下，它试图反射什么类型的构造器。大概应该是一个原本以`Activity`为参数的构造器，在Transform为`ShadowActivity`后找不到了。另外提一个issue吧。这个应该和startActivityForResult的支持无关的。

**Comment by weithink** [comment]
好
