### ISSUE TITLE
Method Not Found错误

### ISSUE THREAD

**Issue by weithink** [Tencent/Shadow#571]
### 我自己也找了好久问题，但是没有找到。这是报错信息，还请大佬指点下思路

我看了文档说明：
>例如，ShadowActivity没有实现全所有Activity方法，你写的测试代码可能用到了， 就会出现Method Not Found错误，只需要在ShadowActivity中实现对应方法就可以了。 大部分方法的实现都只是需要简单的转调就能工作正常。

应该就是这个问题，但是没找到是哪个方法没有实现。

@shifujun 

```
2021-07-30 15:26:24.596 31963-31963/com.tencent.shadow.sample.host E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.shadow.sample.host:plugin, PID: 31963
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity}: java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class com.tencent.shadow.core.runtime.ShadowActivity]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class com.tencent.shadow.core.runtime.ShadowActivity]
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(ShadowActivityDelegate.kt:152)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7088)
        at android.app.Activity.performCreate(Activity.java:7079)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6651) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
     Caused by: java.lang.NoSuchMethodException: <init> [class com.tencent.shadow.core.runtime.ShadowActivity]
        at java.lang.Class.getConstructor0(Class.java:2320)
        at java.lang.Class.getDeclaredConstructor(Class.java:2166)
        at com.razorpay.RzpAssist.<init>(:82)
        at com.razorpay.Y_$B$.setUpAddOn(:28)
        at com.razorpay.b__J_.onCreate(:6215)
        at com.razorpay.B$$W$.onCreate(:23)
        at com.razorpay.CheckoutActivity.onCreate(:8)
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(ShadowActivityDelegate.kt:149)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84) 
        at android.app.Activity.performCreate(Activity.java:7088) 
        at android.app.Activity.performCreate(Activity.java:7079) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6651) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 

```

### CheckoutActivity 相关代码

```
package com.razorpay;

import android.os.Bundle;
import com.razorpay.B..W.;

public final class CheckoutActivity extends  {
    public CheckoutActivity() {
    }

    public final void onCreate(Bundle var1) {
        super.onCreate(var1);
    }
}

```

### RzpAssist 的代码

```
package com.razorpay;

import android.app.Activity;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.view.inputmethod.InputMethodManager;
import android.webkit.JavascriptInterface;
import android.webkit.WebView;
import android.widget.Toast;
import com.razorpay.I._n_;
import com.razorpay.J._0_;
import com.razorpay.f._G.;
import com.razorpay.t_.J_;
import java.util.HashMap;
import org.json.JSONObject;

public final class RzpAssist implements J_ {
    private WebView a_$P$;
    private boolean G__G_ = false;
    private String R$$r_ = "";
    private String Q_$2$ = "";
    private long d__1_;
    private boolean B$$W$ = false;
    private boolean E$_j$ = false;
    private Activity D$_X_;
    private String r$_Y_;
    private _n_ b__J_;
    private Object E$_6$$5c24f078;
    private JSONObject l_$w$ = new JSONObject();
    private JSONObject c__C_ = new JSONObject();
    private String O_$B_;
    private boolean Y$_o$ = false;
    private boolean g__v_ = false;
    private String J$_0_ = "standalone";
    private int L__R$;
    private String l__d$;
    private boolean f$_G$ = false;

    public RzpAssist(String var1, Activity var2, WebView var3, String var4, int var5, String var6) {
        if (L__R$().D$_X_()) {
            if (var1 != null && !var1.isEmpty()) {
                this.J$_0_ = var4;
                this.L__R$ = var5;
                if (var4.equals("standalone")) {
                    AnalyticsUtil.setup(var2, var1, var4, var5, var6);
                }

                this.a_$P$ = var3;
                this.r$_Y_ = var1;
                this.D$_X_ = var2;
                Activity var10001 = var2;

                Throwable var13;
                Object var14;
                try {
                    var14 = ((Class)O__Y_.d__1_(18, 18, '\u0000')).getDeclaredConstructor(Activity.class).newInstance(var10001);
                } catch (Throwable var11) {
                    var13 = var11.getCause();
                    if (var13 != null) {
                        throw var13;
                    }

                    throw var11;
                }

                this.E$_6$$5c24f078 = var14;
                Object var10000 = this.E$_6$$5c24f078;

                try {
                    ((Class)O__Y_.d__1_(18, 18, '\u0000')).getDeclaredMethod("Q_$2$", (Class[])null).invoke(var10000, (Object[])null);
                } catch (Throwable var12) {
                    var13 = var12.getCause();
                    if (var13 != null) {
                        throw var13;
                    }

                    throw var12;
                }

                if (_n_.d__1_ == null) {
                    _n_.d__1_ = new _n_();
                }

                this.b__J_ = _n_.d__1_;
                this.b__J_.a_$P$.add(this);
                this.b__J_.a_$P$(this.D$_X_);
                this.a_$P$.addJavascriptInterface(this, "OTPElfBridge");
                this.a_$P$.getSettings().setUseWideViewPort(true);
                AnalyticsUtil.addProperty("OTPElf Version", new AnalyticsProperty(BaseUtils.getLocalVersion(var2, (String)((Class)O__Y_.d__1_(18, 18, '\u0000')).getField("R$$r_").get((Object)null)), com.razorpay.AnalyticsProperty.Q_.2..R$$r_));
            } else {
                throw new RuntimeException("merchantKey cannot be null or empty");
            }
        }
    }

    

```

**Comment by weithink** [comment]
@shifujun  大佬帮忙看下
