### ISSUE TITLE
android:sharedUserId="android.uid.system" APP集成shadow会崩溃

### ISSUE THREAD

**Issue by xuwanshu** [Tencent/Shadow#574]
2021-08-03 17:15:03.986 11803-11803/com.tsinglink.android.mpu.p8 E/CrashReport: sys default last handle start!
2021-08-03 17:15:03.987 11803-11803/com.tsinglink.android.mpu.p8 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tsinglink.android.mpu.p8:plugin, PID: 11803
    java.lang.UnsupportedOperationException: For security reasons, WebView is not allowed in privileged processes
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:187)
        at android.webkit.WebView.getFactory(WebView.java:2341)
        at android.webkit.WebView.ensureProviderCreated(WebView.java:2336)
        at android.webkit.WebView.setOverScrollMode(WebView.java:2395)
        at android.view.View.<init>(View.java:4023)
        at android.view.View.<init>(View.java:4146)
        at android.view.ViewGroup.<init>(ViewGroup.java:579)
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
        at android.webkit.WebView.<init>(WebView.java:627)
        at android.webkit.WebView.<init>(WebView.java:572)
        at android.webkit.WebView.<init>(WebView.java:555)
        at android.webkit.WebView.<init>(WebView.java:542)
        at android.webkit.WebView.<init>(WebView.java:532)
        at com.tencent.shadow.core.loader.blocs.CreateResourceBloc$create$1.run()
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6121)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by shifujun** [comment]
同#575
