### ISSUE TITLE
ClassNotFoundException: android.view.set

### ISSUE THREAD

**Issue by hf529270451** [Tencent/Shadow#595]
插件调用宿主class的时候  报错classNotFoundException，插件是通过compileOnly依赖的宿主

```
Caused by: java.lang.ClassNotFoundException: android.view.set
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.view.LayoutInflater.createView(LayoutInflater.java:825)
        at android.view.LayoutInflater.createView(LayoutInflater.java:786)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:923)
        at com.tencent.shadow.core.runtime.FixedContextLayoutInflater.onCreateView(FixedContextLayoutInflater.java:65)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:940)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:960)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1014)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:971)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:669)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
        at com.tencent.shadow.core.runtime.ShadowActivity.setContentView(ShadowActivity.java:40)
        at com.czb.chezhubang.plugin.map.MapActivity.onCreate(MapActivity.java:68)
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(Unknown Source:380)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:8214)
        at android.app.Activity.performCreate(Activity.java:8202)
    	at android.a
```

我打印了下pluginClassLoader的日志 报错是在 PluginClassLoader的
```
else if (className.inPackage(allHostWhiteList)
                || (Build.VERSION.SDK_INT < 28 && className.startsWith("org.apache.http"))) {//Android 9.0以下的系统里面带有http包，走系统的不走本地的) {
            Log.e("PluginClassLoader", "loadClass 1");
            return super.loadClass(className, resolve)
        }
```

class的名字都比较奇怪，叫什么
android.widget.set android.view.set android.widget.set

**Comment by shifujun** [comment]
看起来是你往`layout.xml`里写了类似于`<set />`的东西。这个`set`会被`android.view.LayoutInflater.onCreateView`拼接上`android.view`前缀，去查找系统的内置View。比如`TextView`、`FrameLayout`，可以直接使用都是由于这个逻辑。

**Comment by hf529270451** [comment]
大佬，找到问题了，是因为我替换了Resouces加载的逻辑换成了addAssetPath和主工程资源冲突了，我现在用aapt2
修改了插件工程的资源id，请问这么做会有其他隐患吗

**Comment by LinXueyuanStdio** [comment]
用给予 setFactory2 的换肤框架，也有这个问题。挺常见的。希望能讨论一个通用解法

**Comment by shifujun** [comment]
> 大佬，找到问题了，是因为我替换了Resouces加载的逻辑换成了addAssetPath和主工程资源冲突了，我现在用aapt2
> 修改了插件工程的资源id，请问这么做会有其他隐患吗

主要是这个构造器是`@Deprecated`的，以后新版本的系统上可能会不可用了。
```
@Deprecated
public Resources(AssetManager assets, DisplayMetrics metrics, Configuration config)
```

你用`packageManager.getResourcesForApplication`构造Resources，在`sharedLibraryFiles`里面添加其他apk的路径，也能达到`addAssetPath`的效果的。

Shadow这里直接复制了宿主的`sharedLibraryFiles`，是为了把WebView注入给宿主的资源复制给插件。WebView的资源ID就是有专门分区的。
https://github.com/Tencent/Shadow/blob/master/projects/sdk/core/loader/src/main/kotlin/com/tencent/shadow/core/loader/blocs/CreateResourceBloc.kt#L43

**Comment by shifujun** [comment]
> 用基于 setFactory2 的换肤框架（如android-skin-support），也有这个问题。挺常见的。希望能讨论一个通用解法

那我还是没明白它怎么会有添加`<set />`的效果。你是说 https://github.com/ximsfei/Android-skin-support 这个库，集成到Shadow的插件里就会复现`ClassNotFoundException: android.view.set`的问题吗？

**Comment by LinXueyuanStdio** [comment]
@shifujun 宿主集成了 https://github.com/ximsfei/Android-skin-support 这个库，然后插件正常写

比如插件的 layout 里有 activity_main.xml 里有个 <ImageView .../>，插件会在构建 ImageView 的时候崩溃，也是ClassNotFoundException

这个情况非常难debug，我是去掉宿主的Android-skin-support库后，插件自己就能正常构建 ImageView 了。
我也没搞懂，只能猜测是 这个库 置换了factory，然后插件通过宿主的factory 构建view，但是宿主的view对插件透明，然后找不到class

复现的话，在宿主加入Android-skin-support后，随便换一个肤，然后打开插件。应该就可以复现了。

**Comment by LinXueyuanStdio** [comment]
android.widget.set 我猜是用了某款框架置换了宿主的factory，没处理 <set />这种情况吧
感觉和 android.widget.ImageView 之于 <ImageView /> 的情况类似

**Comment by LinXueyuanStdio** [comment]
我尝试过把宿主的view加入白名单，但这样插件inflate的时候只能用宿主的view，就导致很多潜在bug了。

这个解法不行。看看有没有其他解法。

**Comment by shifujun** [comment]
> @shifujun 宿主集成了 https://github.com/ximsfei/Android-skin-support 这个库，然后插件正常写
> 
> 比如插件的 layout 里有 activity_main.xml 里有个 <ImageView .../>，插件会在构建 ImageView 的时候崩溃，也是ClassNotFoundException
> 
> 这个情况非常难debug，我是去掉宿主的Android-skin-support库后，插件自己就能正常构建 ImageView 了。
> 我也没搞懂，只能猜测是 这个库 置换了factory，然后插件通过宿主的factory 构建view，但是宿主的view对插件透明，然后找不到class
> 
> 复现的话，在宿主加入Android-skin-support后，随便换一个肤，然后打开插件。应该就可以复现了。

https://github.com/shifujun/Shadow/tree/testAndroidSkinSupportSDK
我没能复现。

**Comment by LinXueyuanStdio** [comment]
我又试了一下，确实没有问题。。。emm
