### ISSUE TITLE
插件出现IncompatibleClassChangeError偶发错误,复现不了

### ISSUE THREAD

**Issue by YiScond** [Tencent/Shadow#603]
首先情况是这样的
宿主和插件都集成了一个第三方sdk,版本不一致.
线上收集到了部分崩溃日志,集中在android10,android11,且其中华为设备占比较多
出现崩溃的设备在android10的用户中占比1%不到.
具体到某一个设备的使用记录，前一天还在正常使用插件，下一天就报错了
崩溃日志如下:

java.lang.IncompatibleClassChangeError: Class 'com.kwad.sdk.api.KsScene$Builder' does not implement interface 'com.kwad.sdk.api.KsScene' in call to 'void com.kwad.sdk.api.KsScene.setAdStyle(int)' (declaration of 'com.kwad.sdk.core.g.d' appears in /data/user/0/xxx.xxx.xx/app_p/5/5-plugin.apk)
	at com.kwad.sdk.core.g.d.loadRewardVideoAd(Unknown Source:15)
	at com.z.y.ad.c.e(Unknown Source:32)
	at com.z.y.ad.k.loadRewardAd(Unknown Source:2)
	at com.z.y.f.a.a(Unknown Source:72)
	at com.z.y.b.b.b.b.a(Unknown Source:4)
	at com.z.y.b.b.b.a.g(Unknown Source:18)
	at com.z.y.b.b.b.b.g(Unknown Source:0)
	at com.z.y.b.a.a.a(Unknown Source:41)
	at com.z.y.ad.c$2.run(Unknown Source:22)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

发现问题后 这边想复现出这个报错 也一直没有复现出来.
后面仔细对比了宿主和插件中该sdk的com.kwad.sdk.api.KsScene$Builder类 发现两个版本间有个方法差异，现在是将插件中的该sdk版本保持与宿主的一样,现在线上跑了2天了，以上的崩溃没再出现过。

这个问题比较奇怪，按照shadow的设计,宿主和插件间类是隔离的,而且白名单中也没有该第三方sdk的配置,理论上在该sdk上宿主和插件之间应该不会有联系才对,解决方案目前是将该sdk版本保持一致。

这边很是疑惑,具体原因还不明,但应该不是shadow导致的问题,想问下大佬有没有碰到这种报错。

**Comment by shifujun** [comment]
类似的问题一般是由于`dex2oat`过程的`inline optimization`（内联优化）造成的。大概就是宿主打包的代码oat化后，等到插件的那个同名的方法在oat时，发现可以内联优化。它就把宿主里那个同名方法的oat代码直接复制过来，内联到插件调用这个方法的oat部分了。所以插件的代码执行的时候，调用这个方法，实际上执行的是宿主里那个同名方法的实现。

也许解决这个问题最好的方向还是避免出现同名的类。也许可以考虑用更好的利用Proguard修改SDK的包名，如果SDK中涉及反射，可以保留几处。毕竟内联优化也不是会到处发生。

你也可以搜索一些“android 内联优化”方面的文章了解更多。

**Comment by qq8803128** [comment]
@shifujun 那么loader插件目录引用了kotlin-std库的话，如果host也存在不同版本的kotlin-std的库的话，是不是也会产生内联优化的问题呢？我其实有点好奇，为啥loader模块需要用kt写而不采用java

**Comment by shifujun** [comment]
kotlin-std库是对Proguard非常友好的。loader打包的kotlin-std库经过Proguard优化后几乎没有什么保留原来名字的类了。所以发生这种内联优化的情况应该概率很低。loader使用kotlin写也是在这个Proguard有效性基础上希望能多利用kotlin的一些便捷特性，减少自己实现一些util类。其余模块没有用kotlin主要是因为对apk大小太敏感了。

**Comment by qq8803128** [comment]
我看了下，感觉loader里面用到kt的扩展方法也不是很多吧，关键是如果用kt写loader的话，对于shadow工程的loader模块如果用远程依赖基本没法断点，真的不太好调试  @shifujun

**Comment by shifujun** [comment]
> 对于shadow工程的loader模块如果用远程依赖基本没法断点，真的不太好调试

这个问题的根本原因与用kotlin没太大关系。即便是Java，经过Proguard也是基本没法断点的。能否断点主要看debug信息，尤其是行号是否得以保留。

如果问题不是Proguard等release过程引起的，那么完全可以把loader模块替换成debug版。这个调试成本似乎不高的，因为我也调试过这种场景。

**Comment by qq8803128** [comment]
> > 对于shadow工程的loader模块如果用远程依赖基本没法断点，真的不太好调试
> 
> 这个问题的根本原因与用kotlin没太大关系。即便是Java，经过Proguard也是基本没法断点的。能否断点主要看debug信息，尤其是行号是否得以保留。
> 
> 如果问题不是Proguard等release过程引起的，那么完全可以把loader模块替换成debug版。这个调试成本似乎不高的，因为我也调试过这种场景。

我说的就是debug版本没有混淆的工程，主要是loader模块是kt写，如果直接依赖loader.jar的话，定位会到源码kt文件里面去，断点无法断下来，只能依赖源码才能调试
