### ISSUE TITLE
SDK location not found

### ISSUE THREAD

**Issue by 1step2hell** [Tencent/Shadow#698]
## 异常现象

首次克隆项目，`./gradlew build` 失败：
```
Caused by: com.android.builder.errors.EvalIssueException: SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/bob/AndroidProjects/Shadow/projects/sdk/coding/local.properties'.
        at com.android.builder.errors.IssueReporter.reportError(IssueReporter.kt:109)
        at com.android.builder.errors.IssueReporter.reportError$default(IssueReporter.kt:105)
        at com.android.build.gradle.internal.SdkLocator.getSdkLocation(SdkLocator.kt:239)
        at com.android.build.gradle.internal.SdkLocator.getSdkDirectory(SdkLocator.kt:197)
        at com.android.build.gradle.internal.SdkComponentsKt.getSdkDir(SdkComponents.kt:368)
        at com.android.build.gradle.internal.SdkComponentsBuildService$VersionedSdkLoader$sdkDirectoryProvider$1.call(SdkComponents.kt:198)
        at com.android.build.gradle.internal.SdkComponentsBuildService$VersionedSdkLoader$sdkDirectoryProvider$1.call(SdkComponents.kt:197)
        at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:66)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:64)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.MappingProvider.calculateOwnValue(MappingProvider.java:55)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:128)
        at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:25)
        at org.gradle.api.internal.provider.AbstractProperty.doCalculateValue(AbstractProperty.java:133)
        at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:127)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.FlatMapProvider.calculateOwnValue(FlatMapProvider.java:50)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:84)
        at org.gradle.api.provider.Provider$get.call(Unknown Source)
        at build_6980bvnws4asrriy8vrvrlha.run(/Users/bob/AndroidProjects/Shadow/projects/sdk/coding/get-android-jar/build.gradle:9)
```

环境：macOS 11.1(15款macbook pro)，Android Studio Arctic Fox | 2020.3.1 patch 3，openJDK 11，Gradle 7.0.2，Android Gradle Plugin 7.0.3

## 相关资料

[issue #355](https://github.com/Tencent/Shadow/issues/355) 

[patch](https://github.com/Tencent/Shadow/commit/f80ece3a5fcfd5e2fc0b4d7049ee797b5cfd2fbb)

Android Gradle Plugin 7.0.2 [SDKLocator.kt](https://github.com/Tencent/Shadow/files/7638592/SDKLocator.txt)

## 原因分析

最早 Shadow 项目依赖环境变量${ANDROID_HOME}，后改为 Shadow/projects/sdk/coding/get-android-jar module 提供 android.jar，通过 Shadow/projects/sdk/coding/get-android-jar/build.gradle 动态获取 Android SDK 位置的方式来找到 android.jar：
```groovy
def sdkPath = android.sdkComponents.getSdkDirectory().get().asFile.absolutePath
def androidJarPath = new File(sdkPath, "platforms/${android.compileSdkVersion}/android.jar")
```

但是，通过查看 AGP 7.0.2 代码发现最终调用获取的还是 local.properties 定义的 sdk.dir 或者 ${ANDROID_SDK_ROOT} ${ANDROID_HOME} 之类的环境变量，一旦这些方式无法获取 SDK location，就会默认赋值 missingSdkDirectory：
```
> Configure project :coding:get-android-jar
==> sdkPath=/Users/bob/AndroidProjects/Shadow/projects/sdk/coding/missingSdkDirectory
==> androidJarPath=/Users/bob/AndroidProjects/Shadow/projects/sdk/coding/missingSdkDirectory/platforms/android-30/android.jar
```

也就是说，这一改动其实是没有任何意义的，最终还是回到了依赖环境变量的方式（local.properties的方式肯定不能考虑，无法保证每个人的 SDK 位置一样），反而少了原来的环境变量检测告警。

## 复现及解决

分析完原因，复现也很简单，只需要把环境变量  ${ANDROID_SDK_ROOT} ${ANDROID_HOME}  之类给移除 并删除 module 的  local.propertie 后，build 一定会失败。

本地解决方式也简单，配置环境变量  ${ANDROID_SDK_ROOT} ${ANDROID_HOME}  任一即可。

对于Shadow项目来说，在没有更好的方式前建议还是回滚到原来的方案。事实上，以后应该也不会有更好方案，每个人本地的 SDK 位置不一样，AGP 也只能通过用户配置的 SDK 位置来获取，要么配置在文件(local.properties) 要么配置在环境变量。
如果不回滚方案，也可以考虑 readme 补回相关环境变量说明。

**Comment by shifujun** [comment]
那确实要改下readme了。现在不依赖ANDROID_HOME后，反而依赖Android Studio了。应该是先用Android Studio打开项目，它就会自动把local.propertie生成好了。那样就不用配置环境变量了。

**Comment by 1step2hell** [comment]
也许是项目结构的原因，我这里首次打开的时候没有生成 code-generate 的 local.properties，我新建了一个工程测试，每次都可以正确生成 local.properties，即便注释掉了 sdk.dir 都回重新自动打开。

但是确实不能依赖  local.properties，一方面 Android Studio 也许某天有 bug 不会自动生成，另一方面无法直接在 terminal 下 build。

**Comment by shifujun** [comment]
Android Studio不会对includeBuild的工程生成local.properties。但是打开根目录生成local.properties是足够的。

你可以把环境变量的ANDROID_SDK_ROOT和ANDROID_HOME都删了，再用`git clean -fdx`恢复到刚clone的状态。重新用Android Studio打开试试。

也可以对比下打开https://github.com/android/sunflower 的效果。

> 但是确实不能依赖 local.properties，一方面 Android Studio 也许某天有 bug 不会自动生成，另一方面无法直接在 terminal 下 build。

这个风险不大，这里主要是不想搞编译环境的特殊化，希望跟一般工程保持一致。其实从历史issue也能看出来，简单的对ANDROID_HOME环境变量的依赖造成了很多人编译失败，并且无法自行解决。

**Comment by 1step2hell** [comment]
刚测试了一下，光有根目录的 local.properties 依然报同样的错，includeBuild 工程还是需要自己的 local.properties。测试环境就是issue里写的

**Comment by shifujun** [comment]
你说的对，确实有问题。看起来Android Studio似乎总是在Preferences | Appearance & Behavior | Path Variables自动添加`ANDROID_HOME`环境变量，所以在Android Studio中才没有问题。

ANDROID_HOME是绝对路径，所以Android Studio为了简化开发者环境配置成本做了自动生成local.properties和`ANDROID_HOME`环境变量的设计。

我再看下怎么兼容好。目标还是尽量让编译环境没有特殊性。

**Comment by shifujun** [comment]
我想了一下，还是直接在根目录有local.properties时，如果includeBuild目录缺少这个文件，就复制一个。
这样的话，这个project的看起来应该就和普通工程一样了。也就是如果没有local.properties，也没有设置ANDROID_HOME，命令行是无法构建的，但是直接用Android Studio打开可以正常构建。
