### ISSUE TITLE
启动插件的Activity的时候报ActivityNotFoundException

### ISSUE THREAD

**Issue by MmingY** [Tencent/Shadow#726]
1、我在启动插件的时候发现在调用convertActivityIntent方法时activity没有被替换成代理的activity哎~
2、然后我去看了SampleComponentManager和ComponentManager类都没有被调用，不过DynamicPluginLoader类被调用了。
3、我也去检查CoreLoaderFactoryImpl的包名和build方法了。

具体错误信息如下：

2021-12-22 16:44:29.956 2286-2286/com.ming.shadowdemo3 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ming.shadowdemo3:plugin, PID: 2286
    android.content.ActivityNotFoundException: Unable to find explicit activity class {com.ming.shadowdemo3/com.ming.plugin.app.splash.SplashActivity}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2065)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
        at android.app.ContextImpl.startActivity(ContextImpl.java:1023)
        at android.app.ContextImpl.startActivity(ContextImpl.java:994)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:403)
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader$startActivityInPluginProcess$1.run(DynamicPluginLoader.kt:190)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

> `android.app.ContextImpl.startActivity(ContextImpl.java:1023)`

        at android.app.ContextImpl.startActivity(ContextImpl.java:994)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:403)
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader$startActivityInPluginProcess$1.run(DynamicPluginLoader.kt:190)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by shifujun** [comment]
跟#723 一样，自己debug一下关键代码吧。可以先debug一下可以正常运行的sample，对比一下你的app执行情况。

**Comment by MmingY** [comment]
1、我调试了一下，发现componentMap的数组是空的。给我感觉是componentManager.addPluginApkInfo()f方法没有执行的关系。
2、我仔细跟着看了，不过在执行到SamplePluginLoader类的super.loadPlugin(installedApk);调试无法进去，我没有办法看见里面的情况。
3、当执行DynamicPluginLoader类的convertActivityIntent()方法时，mComponentManager中的componentMap数组是空
![capture_20211223092044482](https://user-images.githubusercontent.com/25004212/147173798-dd407304-bde3-4d44-a6c8-103c25e05785.jpg)

**Comment by shifujun** [comment]
先搭建好debug环境，调试一下就不用猜了。你没法正常调试sample-host运行起来之后SDK的所有代码吗？检查下你的代码是不是最新的。把代码push上来我看看也行。着急自己解决的话，也可以用最原始的办法：加Log。

**Comment by MmingY** [comment]
我发现这个问题是插件里面的activity也需要在AndroidManifest.xml里面注册哈~

**Comment by shifujun** [comment]
> 我发现这个问题是插件里面的activity也需要在AndroidManifest.xml里面注册哈~

汗……你怎么能不先测测你的app不用shadow时能不能正常跑呢。

**Comment by MmingY** [comment]
嗯嗯，请教一个问题哈，插架替换activity的时候是根据AndroidManifest来查找的是吗？

**Comment by shifujun** [comment]
> 嗯嗯，请教一个问题哈，插架替换activity的时候是根据AndroidManifest来查找的是吗？

是的。建议主要通过debug插件的启动过程来了解这些实现细节。
