### ISSUE TITLE
插件引入MMKV，奔溃

### ISSUE THREAD

**Issue by BruceLiuTao** [Tencent/Shadow#730]
步骤：
插件新增MMKV框架，覆盖安装插件报如下错误，如果把之前的插件清理掉，重新下载就不会报错
java.lang.UnsatisfiedLinkError: com.tencent.shadow.core.loader.classloaders.PluginClassLoader[DexPathList[[zip file "/data/user/0/com.seuic.kysy/files/ShadowPluginManager/UnpackedPlugin/TakeDeliveryPluginManager/683cab219c8dbe04b6bfbe30d91f7ae/plugin-take-delivery.zip/iwrist_debug_2021-12-25_6.21.1213.99.sku.apk"],nativeLibraryDirectories=[/data/user/0/com.seuic.kysy/files/ShadowPluginManager/UnpackedPlugin/TakeDeliveryPluginManager/lib/1.4.6_lib, /system/lib]]] couldn't find "libmmkv.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
	at java.lang.System.loadLibrary(System.java:1669)
	at com.tencent.mmkv.MMKV.doInitialize(MMKV.java:194)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:181)
	at com.tencent.mmkv.MMKV.initialize(MMKV.java:134)
	at com.kye.utils.MMKVUtil.initMMKV(MMKVUtil.java:13)
	at com.kye.pad.base.BaseApplicationLike.onCreate(BaseApplicationLike.java:144)
	at com.tencent.shadow.core.loader.ShadowPluginLoader$callApplicationOnCreate$1.invoke(Unknown Source:34)
	at com.tencent.shadow.core.loader.ShadowPluginLoader$callApplicationOnCreate$2.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6713)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

**Comment by shifujun** [comment]
跟MMKV有什么关系吗？应该跟#691 是一个问题吧？
