### ISSUE TITLE
请问一下runtime、loader、manager正确的复用姿势

### ISSUE THREAD

**Issue by Daimhim** [Tencent/Shadow#743]
在目前开发中，插件代码是经常扩展、可变的，runtime、loader、manager变化极少。现在打个插件包都是runtime、loader、plugin三个元素，多个插件不同但runtime、loader相同的情况下 就难以支持了。所以想请教一下 在实际项目中插件分开打包的情况下 如何复用runtime、loader

**Comment by shifujun** [comment]
宿主和manager，manager和plugin之间分别都是一对多的版本关系，其中plugin包含runtime、loader以及不确定数量的插件apk。这个版本对应关系的控制是manager实现的，其目的在于更新发布后者而适配于多个前者。宿主不更新，而插件频繁更新，就是一对多的版本关系。

manager的存在是为了可以动态实现一些更复杂的插件分发逻辑，更复杂的逻辑隐含更复杂的bug，所以manager需要动态化。而host中的manager更新逻辑则更为简单可靠一些。

runtime、loader、插件apk组成的插件包，也就是目前代码中只支持的zip包。插件包可以有多个，也就是多个zip，但它们包含的组件的UUID是一致的。这个UUID的一致保证了它们是可以有类级别的编译依赖的，可以协同工作。

前面不管是一对多的版本关系，还是UUID的机制，核心目的都是分清楚哪些组件之间可以协同工作，哪些组件可以单独更新而不影响协同工作。

复用manager应该是比较容易的，只需要在host中控制它的更新下载逻辑就可以了。

复用插件包中的loader、runtime或者是某个公共插件，在现有的manager设计上是有考虑的，但是没有实现。没有实现的主要原因还是我们的业务没有这样的强需求。没有强需求的主要原因是业务采用了拆分多插件、预加载、优化apk体积等措施，使得新用户打开插件等速度可接受，老用户后台更新插件不用等待。这样使得插件的复用需求不强。同时也有更复杂的缓存设计会带来更多bug的成本问题。

实现下载复用不用打破现有的UUID机制，不同UUID的相同apk可以通过文件hash确定是同一个文件，从而跳过下载，在安装插件时复用旧版本不同UUID中已有的apk。现有代码中只支持从zip安装，需要先重构为从目录、文件安装。

再退一步讲，业务方也完全可以重新设计实现core.manager，loader与它耦合性很低。

这里也有之前类似的issue：
https://github.com/Tencent/Shadow/issues/583#issuecomment-899165484

**Comment by Daimhim** [comment]
我修改了一种新的解包路径，主要是把插件中的loader、runtime单独解压出来，并且以其文件的MD5值作为文件夹名，在后续的其他插件解压过程中，如果发现存在相同的MD5值文件夹，则不再重复解压。这样插件在运行的时候就会复用同一份loader和runtime了。
![image](https://user-images.githubusercontent.com/20254978/148390196-0157f40f-b186-4331-9996-848e51f4d748.png)

MD5保证了文件的唯一性

**Comment by Daimhim** [comment]
解压后的目录，不知道Shadow的解压是不是也可以改成这样？
![image](https://user-images.githubusercontent.com/20254978/148390878-0c203ac9-d934-4898-b8ff-33b0c9f613d5.png)

**Comment by shifujun** [comment]
每个业务的需求都有不一样的地方。像你说的，你的需求只是节省解压过程，复用相同文件的loader和runtime，你应该是达到了目的。可能对其他人来说，重复解压问题也不大，或者像避免重复下载它们。所以我们尽量只合并足够通用的代码。

**Comment by hehe2015** [comment]
我的需求是把公司的4个app合并到一个新的app里。我需要做个宿主app，和4个插件，刚开始研究这个shadow，这个4个插件都引入了loader和runtime，./gradlew packageDebugPlugin命令生成的.zip文件包含了loader、runtime.apk，但我在运行宿主时，打开的其中任意一个插件，其他3个都报错：
getPlugin exception:
java.lang.NullPointerException: Attempt to read from field 'java.io.File com.tencent.shadow.core.manager.installplugin.InstalledPlugin$Part.pluginFile' on a null object reference
	at com.tencent.shadow.dynamic.manager.BaseDynamicPluginManager.getPlugin(BaseDynamicPluginManager.java:192)
	at com.tencent.shadow.dynamic.manager.UuidManagerBinder.onTransact(UuidManagerBinder.java:50)
	at android.os.Binder.execTransactInternal(Binder.java:1157)
	at android.os.Binder.execTransact(Binder.java:1126)
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:593)
	at com.tencent.shadow.dynamic.manager.BinderPluginLoader.loadPlugin(BinderPluginLoader.java:46)
	at com.tencent.shadow.sample.manager.FastPluginManager.loadPlugin(FastPluginManager.java:124)
	at com.tencent.shadow.sample.manager.FastPluginManager.convertActivityIntent(FastPluginManager.java:107)
	at com.tencent.shadow.sample.manager.FastPluginManager.startPluginActivity(FastPluginManager.java:99)
	at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
*** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
com.tencent.shadow.dynamic.host.FailedException
	at com.tencent.shadow.dynamic.host.BinderUuidManager.checkException(BinderUuidManager.java:36)
	at com.tencent.shadow.dynamic.host.BinderUuidManager.getPlugin(BinderUuidManager.java:54)
	at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:80)
	at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:43)
	at android.os.Binder.execTransactInternal(Binder.java:1157)
	at android.os.Binder.execTransact(Binder.java:1126)
Timeline: Activity_launch_request time:80556348
FATAL EXCEPTION: pool-3-thread-1
Process: com.tencent.shadow.sample.host, PID: 17251
java.lang.RuntimeException: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.shadow.sample.host/com.example.testplugin.MainActivity}; have you declared this activity in your AndroidManifest.xml?
	at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.tencent.shadow.sample.host/com.example.testplugin.MainActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2079)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1737)
	at android.app.Activity.startActivityForResult(Activity.java:5436)
	at android.app.Activity.startActivityForResult(Activity.java:5394)
	at android.app.Activity.startActivity(Activity.java:5780)
	at android.app.Activity.startActivity(Activity.java:5733)
	at com.tencent.shadow.sample.manager.FastPluginManager.startPluginActivity(FastPluginManager.java:103)
	at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
	at java.lang.Thread.run(Thread.java:923) 
重启宿主app后任一个插件都无法打开了：
FATAL EXCEPTION: main
Process: com.tencent.shadow.sample.host:plugin, PID: 17351
java.lang.RuntimeException: Unable to create service com.tencent.shadow.sample.introduce_shadow_lib.MainPluginProcessService: java.lang.IllegalStateException: PPS出现多实例
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4308)
	at android.app.ActivityThread.access$1700(ActivityThread.java:258)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2002)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8060)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.IllegalStateException: PPS出现多实例
	at com.tencent.shadow.dynamic.host.BasePluginProcessService.onCreate(BasePluginProcessService.java:32)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4296)
	at android.app.ActivityThread.access$1700(ActivityThread.java:258) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2002) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loop(Looper.java:236) 
	at android.app.ActivityThread.main(ActivityThread.java:8060) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
Sending signal. PID: 17351 SIG: 9
FATAL EXCEPTION: pool-3-thread-1
Process: com.tencent.shadow.sample.host, PID: 22682
java.lang.RuntimeException: java.util.concurrent.TimeoutException: 连接Service超时 ,等待了：10001
	at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.util.concurrent.TimeoutException: 连接Service超时 ,等待了：10001
	at com.tencent.shadow.dynamic.manager.BaseDynamicPluginManager.waitServiceConnected(BaseDynamicPluginManager.java:127)
	at com.tencent.shadow.sample.manager.FastPluginManager.loadPluginLoaderAndRuntime(FastPluginManager.java:114)
	at com.tencent.shadow.sample.manager.FastPluginManager.loadPlugin(FastPluginManager.java:121)
	at com.tencent.shadow.sample.manager.FastPluginManager.convertActivityIntent(FastPluginManager.java:107)
	at com.tencent.shadow.sample.manager.FastPluginManager.startPluginActivity(FastPluginManager.java:99)
	at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
	at java.lang.Thread.run(Thread.java:923) 
请问这个怎么处理？🙏
