### ISSUE TITLE
android.util.SuperNotCalledException : .PluginDefaultProxyActivity did not call through to super.onCreate()

### ISSUE THREAD

**Issue by YiScond** [Tencent/Shadow#752]
崩溃日志:
```
android.util.SuperNotCalledException: Activity {com.xx.xx/com.tencent.shadow.sample.runtime.PluginDefaultProxyActivity} did not call through to super.onCreate()
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3149)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5076)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4985)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:55)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5035)
	at android.app.ActivityThread.access$3400(ActivityThread.java:241)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2050)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:928)
```
以下为其中一个设备的信息
机型: vivo X21i
系统版本: android 9.0
<br>
线上收集到的,从数据表现上看出现这个报错的非常少,目前还没复现。
根据调用栈的信息应该是在重新启动坑位Activity上的报错。
我初步看了下源代码，super.onCreate不管怎么样都是能被调用到的。
不知道这个问题该怎么分析和解决。

**Comment by YiScond** [comment]
> 有尝试主动构造Relaunch场景吗？应该可以通过开发者选项中设置不保留活动，然后将Activity切到后台再从历史页面返回来构造该场景。

设置不保留活动 然后在我的设备上测了下，并没有出现报错，进入插件页面回到桌面然后再点击任务栏回到插件页面，debug看到从任务栏回来,在 **PluginContainerActivity.onCreate**中执行的是hostActivityDelegate.onCreate(savedInstanceState)
```
PluginContainerActivity.onCreate

if (hostActivityDelegate != null) {
     hostActivityDelegate.onCreate(savedInstanceState);
} 
```
且回来后,通过ActivityLifecycleCallback可以发现坑位Activity只有onActivityCreated()和onActivityDestroyed()发生

**Comment by shifujun** [comment]
所以看起来是正常的。这块逻辑还是比较可靠的。还是检查下业务Activity是否某些情况下不会调用super.onCreate吧。实在没办法就加Log，上报到Crash日志中。

**Comment by YiScond** [comment]
> 所以看起来是正常的。这块逻辑还是比较可靠的。还是检查下业务Activity是否某些情况下不会调用super.onCreate吧。实在没办法就加Log，上报到Crash日志中。

还真的可能是插件业务Activity的逻辑影响到了，我再排查下插件Activity，shadow没问题。
感谢大佬回复
