### ISSUE TITLE
ShadowApplication receiverInfo未判空

### ISSUE THREAD

**Issue by gb18030** [Tencent/Shadow#755]
![image](https://user-images.githubusercontent.com/19511418/148347965-7ee92c4f-44f0-4884-8dcc-4be321e4f001.png)
报错:
`2022-01-06 15:50:01.525 9111-9136/? E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)

    java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.tencent.shadow.core.loader.exceptions.CreateApplicationException: java.lang.NullPointerException: storage == null
        at java.util.concurrent.FutureTask.report(FutureTask.java:93)
        at java.util.concurrent.FutureTask.get(FutureTask.java:163)
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:82)
        at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:43)
        at android.os.Binder.execTransact(Binder.java:446)
     Caused by: java.util.concurrent.ExecutionException: com.tencent.shadow.core.loader.exceptions.CreateApplicationException: java.lang.NullPointerException: storage == null
        at java.util.concurrent.FutureTask.report(FutureTask.java:93)
        at java.util.concurrent.FutureTask.get(FutureTask.java:163)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildRunningPlugin$1.run(LoadPluginBloc.kt:127)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: com.tencent.shadow.core.loader.exceptions.CreateApplicationException: java.lang.NullPointerException: storage == null
        at com.tencent.shadow.core.loader.blocs.CreateApplicationBloc.createShadowApplication(CreateApplicationBloc.kt:69)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildApplication$1.call(LoadPluginBloc.kt:108)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildApplication$1.call(LoadPluginBloc.kt:101)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.lang.NullPointerException: storage == null
        at java.util.Arrays$ArrayList.<init>(Arrays.java:38)
        at java.util.Arrays.asList(Arrays.java:155)
        at com.tencent.shadow.core.runtime.ShadowApplication.setBroadcasts(ShadowApplication.java:157) <----看这里!!!
        at com.tencent.shadow.core.loader.blocs.CreateApplicationBloc.createShadowApplication(CreateApplicationBloc.kt:58)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildApplication$1.call(LoadPluginBloc.kt:108) 
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildApplication$1.call(LoadPluginBloc.kt:101) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) `

**Comment by shifujun** [comment]
感谢反馈🌹
