### ISSUE TITLE
Task :app:transformClassesWithDexBuilderForDebug FAILED 

### ISSUE THREAD

**Issue by Braver888** [Tencent/Shadow#81]
com.android.builder.dexing.JarClassFileInput$JarClassFileInputsException: Unable to read jar file E:\project\EasyPlugInSample\EasyPlugInSample\app\build\intermediates\transforms\changeBtyeCodeTask\debug\20.jar
	at com.android.builder.dexing.JarClassFileInput.entries(JarClassFileInput.java:64)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:903)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.lambda$convertToDexArchive$6(DexArchiveBuilderTransform.java:834)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at com.android.builder.dexing.JarClassFileInput.entries(JarClassFileInput.java:61)
	... 7 more

**Comment by Braver888** [comment]
把jar复制出来 改成zip提示已损坏 ，还有就是Plugin里获取的sdk版本号是null

**Comment by shifujun** [comment]
代码push上来，看看你改了什么。

**Comment by Braver888** [comment]
没改什么 把 gradle plugin抽出来想单独写个转化插件的，是不是因为单独抽出来的原因




------------------ 原始邮件 ------------------
发件人: "shifujun"<notifications@github.com>; 
发送时间: 2019年8月4日(星期天) 晚上8:24
收件人: "Tencent/Shadow"<Shadow@noreply.github.com>; 
抄送: "1485328557@qq.com"<1485328557@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Tencent/Shadow] Task :app:transformClassesWithDexBuilderForDebug FAILED 以及 Plugin里获取plugin.extension.compileSdkVersion为null (#81)




代码push上来，看看你改了什么。
