### ISSUE TITLE
deleteInstalledPlugin 后再installPlugin 似乎不起作用

### ISSUE THREAD

**Issue by zeronewhepler** [Tencent/Shadow#813]
你好 @shifujun 
我想测试插件`deleteInstalledPlugin` 后再 `installPlugin` 。遇到了问题，效果没有达到预期。
首先我做了个插件，内容就是一个Activity，中间一个文字，点击文字展示一个toast

```
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        findViewById<TextView>(R.id.tv).setOnClickListener {
            // 第一次打印 1
            // 第一次打印 2
            Toast.makeText(this,"2",Toast.LENGTH_LONG).show()
        }
    }
}
```

先后进行2次打包并把zip文件放到指定位置
第一次打包：
```
shadow {
    transform {
//        useHostContext = ['abc']
    }

    packagePlugin {
        archivePrefix = "test-plugin-loader-and-runtime"
        pluginTypes {
            debug {
                loaderApkConfig = new Tuple2('loader-debug.apk', ':loader:assembleDebug')
                runtimeApkConfig = new Tuple2('runtime-debug.apk', ':runtime:assembleDebug')
            
                pluginApks {
                    pluginApk1 {
                        partKey = 'test-plugin'
                        buildTask = ':test-plugin:assemblePluginDebug'
                        apkPath = 'projects/plugin-project/test-plugin/build/outputs/apk/plugin/debug/test-plugin-plugin-debug.apk'
                    }
                }
            }

        }

        loaderApkProjectPath = 'projects/plugin-project/loader'

        runtimeApkProjectPath = 'projects/plugin-project/runtime'

        version = 4
        compactVersion = [1]
        uuidNickName = "1.1.5"
    }
}
```
第二次打包
```
shadow {
   // 其他内容和第一次 一致 
   .......
        version = 5
        compactVersion = [1]
        uuidNickName = "1.1.6"
    }
}
```

在manager 中的代码：
```
InstalledPlugin installedPlugin = installPlugin("/data/user/0/a.b.c/files/test-plugin-debug.zip", null, true);
TestManager.uuid = installedPlugin.UUID;
Intent pluginIntent = new Intent();
pluginIntent.setClassName(context.getPackageName(),className);
if (extras != null) {
                pluginIntent.replaceExtras(extras);
}
startPluginActivity(context, installedPlugin, partKey, pluginIntent);

// 10s后删除再启动一次
Thread.sleep(10000);
deleteInstalledPlugin(installedPlugin.UUID);
installedPlugin = installPlugin("/data/user/0/a.b.c/files/test-plugin-debug2.zip", null, true);
TestManager.uuid = installedPlugin.UUID;
startPluginActivity(context, installedPlugin, partKey, pluginIntent);

```

先后2次点击弹出的toast 都是 【1】
如果我调换 文件路径， 先加载2，再加载1， 则先后2次toast 都是 【2】

在使用shadow 时，想要更新正在使用的插件，该如何处理？

**Comment by shifujun** [comment]
可以先看一下你用的代码是否包含了这个修复：https://github.com/Tencent/Shadow/commit/34eaab1d548910aeb7d3b05f46774739a8da949c

如果包含了，可以在这个提交中引入的ReinstallPluginTest中修改复现你的问题。

**Comment by shifujun** [comment]
先看了一下#815 的代码，看代码的意思，你是想在不重启插件进程的情况下更新插件吗？这是不行的。

从代码上来说，
https://github.com/Tencent/Shadow/blob/15c99fa809c81e4c93b1736c14f58d328f364dcd/projects/sdk/dynamic/dynamic-manager/src/main/java/com/tencent/shadow/dynamic/manager/PluginManagerThatUseDynamicLoader.java#L94-L97

即使uuid变了，在PPS没有断开的情况下，它也不会加载新的。

**Comment by zeronewhepler** [comment]
好吧。
如果某个插件正在使用中，这个时候想要立刻更新该插件，在shadow中有什么好的处理方式吗？
只能粗暴的重启进程？

**Comment by shifujun** [comment]
你在界面上总要跟用户先交互一下吧？就算有热更新的能力，也不能直接更新界面吧？

处理好交互，保存好状态，重启进程然后启动新插件复用之前的状态。

**Comment by zeronewhepler** [comment]
你好 @shifujun
我正在测试 退出进程后 更新插件

但是在使用  `PluginManagerThatUseDynamicLoader.mPpsBinderController` 时发生了错误

使用：
`mPpsController.exit();`
报错：
```
Process: com.tencent.shadow.test.hostapp, PID: 3366
    java.lang.RuntimeException: android.os.DeadObjectException
        at com.tencent.shadow.test.dynamic.manager.ReinstallPluginTestDynamicPluginManager$2.run(ReinstallPluginTestDynamicPluginManager.java:177)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:540)
        at com.tencent.shadow.dynamic.host.PpsController.exit(PpsController.java:92)
        at com.tencent.shadow.test.dynamic.manager.ReinstallPluginTestDynamicPluginManager$2.run(ReinstallPluginTestDynamicPluginManager.java:155)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2022-02-19 11:15:11.150 519-600/? E/InputDispatcher: channel '38614e5 com.tencent.shadow.test.hostapp/com.tencent.shadow.test.dynamic.host.JumpToPluginActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```
换成更直接的方式：`android.os.Process.killProcess(getProcessId(mCurrentContext,".plugin"));` 则没什么问题

代码在：`https://github.com/zeronewhepler/Shadow/commit/6aedd837d081b978c59bbf98762a4f96c570ba9f`

运行 `ReinstallPluginTest.testReinstallPluginWhenUsed ` 发生的错误。

**Comment by shifujun** [comment]
优雅的退出程序总是比较难的，特别是终止JVM这件事。能忍受这些异常的话，catch一下也许比较简单。
