### ISSUE TITLE
插件间的跨进程通信

### ISSUE THREAD

**Issue by zeronewhepler** [Tencent/Shadow#822]
A 插件，一个Service，运行进程是p_a 
B 插件，一个Activity，运行进程是p_b

想要在B插件的activity 中获取 A插件Service 的binder

-------------------------------------------------------------------
在主进程 dynamic-manager 中，可以通过 `mPluginLoader.bindPluginService` 得到 A插件Service 的 binder。
但是 在插件B 不在主进程中，我该如何操作？

直接像使用普通service 一样， 在插件B Activity中 bindService 可以找到宿主注册的service，但是无法找到其他进程插件注册的service

插件B Activity中 启动 Service 的代码片段
```
            val pluginServiceIntent = Intent().apply {
                setClassName(this@MainActivity.packageName, "com.hzl.test_service_plugin.MyService")
            }
            this@MainActivity.bindService(pluginServiceIntent, object : ServiceConnection{
                override fun onServiceConnected(name: ComponentName?, service: IBinder?) {
                    //val iMyAidlInterface = IMyAidlInterface.Stub.asInterface(service)
                    try {
                        //val s = iMyAidlInterface.basicTypes(1, 2, true, 4.0f, 5.0, "6");
                        Log.i("SamplePluginManager", "iMyAidlInterface.basicTypes : ");
                    } catch ( e: RemoteException) {
                        throw RuntimeException(e);
                    }
                }

                override fun onServiceDisconnected(name: ComponentName?) {

                }
            }, Context.BIND_AUTO_CREATE)
```

log:
`W/ActivityManager: Unable to start service Intent { cmp=com.hzl.zero.neew/com.hzl.test_service_plugin.MyService } U=0: not found`

com.hzl.zero.neew 就是宿主的包名

**Comment by shifujun** [comment]
另外我没试过是否可行的是：通过广播直接传Binder。

**Comment by zeronewhepler** [comment]
你好 @shifujun !

按照这个顺序：
> 确实Loader没有自动同步其他进程Loader信息的能力。
> 
> 应该可以在A插件中按这个顺序绑定B插件的Service：
> 
> 1. A插件绑a定B插件进程的PPS
> 2. A插件通过B插件进程的PpsController绑定B插件进程的PluginLoader
> 3. A插件通过B插件进程的PluginLoader绑定B插件Service

确实得到了 Binder。但是也有几点问题：
1、` import com.tencent.shadow.dynamic.manager.BinderPluginLoader;` 需要在插件中额外引入一遍，白名单只能访问宿主，不能访问 dynamic-manager 。

2、 `BinderPluginLoader` 不是`public`，所以没办法在 插件或者宿主中正常 实例化，我是修改了源码 将其`public`了。希望Shadow能在合适的地方有对应的实现，这样可以更好的支持插件间的跨进程通信。

**Comment by zeronewhepler** [comment]
我把 `com.tencent.shadow.dynamic.manager.BinderPluginLoader` 拷贝出来，换了个名称， 这样可以不依赖 manager

但是 loader  就不能complieOnly了
```
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.shadow.dynamic.loader.PluginLoader" on path: DexPathList[[zip file "/data/user/0/com.tencent.shadow.test.hostapp/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/8789cb436509046a833c35e77fbec022/plugin-debug.zip/test-plugin-general-cases-plugin-debug.apk"],nativeLibraryDirectories=[/data/user/0/com.tencent.shadow.test.hostapp/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/lib/5BBDF8C1-2121-4614-91CB-2F2E8FEA4E5E_lib, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at com.tencent.shadow.core.loader.classloaders.PluginClassLoader.loadClass(PluginClassLoader.kt:101)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at dalvik.system.DexFile.defineClassNative(Native Method) 
        at dalvik.system.DexFile.defineClass(DexFile.java:294) 
        at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:287) 
        at dalvik.system.DexPathList$Element.findClass(DexPathList.java:773) 
        at dalvik.system.DexPathList.findClass(DexPathList.java:533) 
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:205) 
        at com.tencent.shadow.core.loader.classloaders.PluginClassLoader.loadClass(PluginClassLoader.kt:101) 
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312) 
        at com.tencent.shadow.test.plugin.general_cases.lib.usecases.application.TestApplicationActivity.bindService(TestApplicationActivity.java:60) 
        at com.tencent.shadow.test.plugin.general_cases.lib.usecases.application.TestApplicationActivity.$r8$lambda$oCU4OOYfHa2e-vlJEjUHf_jxtz4(Unknown Source:0) 
        at com.tencent.shadow.test.plugin.general_cases.lib.usecases.application.TestApplicationActivity$$ExternalSyntheticLambda0.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```
--------------------------------------------
最终，自己实现一个MyBinderPluginLoader， 和封装一个 插件间垮进程获取binder的工具类。做一个base-lib，被其他插件dependson。 
解决了这个issue。
