### ISSUE TITLE
从assets中复制apk出错,这个是什么原因

### ISSUE THREAD

**Issue by TA-J** [Tencent/Shadow#858]
Process: com.xqhy.shadow, PID: 9354
    java.lang.RuntimeException: 从assets中复制apk出错
        at com.xqhy.shadow.manager.PluginHelper.preparePlugin(PluginHelper.java:69)
        at com.xqhy.shadow.manager.PluginHelper.access$000(PluginHelper.java:16)
        at com.xqhy.shadow.manager.PluginHelper$1.run(PluginHelper.java:54)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.FileNotFoundException: pluginmanager.apk

**Comment by shifujun** [comment]
> com.xqhy.shadow

看起来你用的不是这里的代码。

**Comment by GaoHJ1112** [comment]
我自己写的demo，在运行的时候抛出的异常，目前没有找到问题出现在哪

**Comment by GaoHJ1112** [comment]
按照你们提供的demo写的

**Comment by GaoHJ1112** [comment]
> > com.xqhy.shadow
> 
> 看起来你用的不是这里的代码。

**Comment by jeesk** [comment]
> 我自己写的demo，在运行的时候抛出的异常，目前没有找到问题出现在哪 

问题解决了吗？  好像是android studio 在debug 的时候， 没有触发task
