### ISSUE TITLE
test-none-dynamic-host 报错

### ISSUE THREAD

**Issue by XuchengJie** [Tencent/Shadow#908]
设备版本：Android 4.4.2
Shadow版本：2.3.0 未做任何修改
运行test-none-dynamic-host后点启动插件，报错

> com.tencent.shadow.test.hostapp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.tencent.shadow.test.hostapp, PID: 26582
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:300)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.RuntimeException: 加载失败
        at com.tencent.shadow.test.none_dynamic.host.HostApplication$1.doInBackground(HostApplication.java:96)
        at com.tencent.shadow.test.none_dynamic.host.HostApplication$1.doInBackground(HostApplication.java:86)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
     Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: hostAppContext.applicationInfo.sharedLibraryFiles must not be null
        at java.util.concurrent.FutureTask.report(FutureTask.java:93)
        at java.util.concurrent.FutureTask.get(FutureTask.java:177)
        at com.tencent.shadow.test.none_dynamic.host.HostApplication$1.doInBackground(HostApplication.java:93)
        at com.tencent.shadow.test.none_dynamic.host.HostApplication$1.doInBackground(HostApplication.java:86) 
        at android.os.AsyncTask$2.call(AsyncTask.java:288) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
     Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: hostAppContext.applicationInfo.sharedLibraryFiles must not be null
        at java.util.concurrent.FutureTask.report(FutureTask.java:93)
        at java.util.concurrent.FutureTask.get(FutureTask.java:163)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildRunningPlugin$1.run(LoadPluginBloc.kt:126)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
     Caused by: java.lang.NullPointerException: hostAppContext.applicationInfo.sharedLibraryFiles must not be null
        at com.tencent.shadow.core.loader.blocs.CreateResourceBloc.create(CreateResourceBloc.kt:62)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildResources$1.call(LoadPluginBloc.kt:88)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildResources$1.call(LoadPluginBloc.kt:87)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841)

**Comment by shifujun** [comment]
CI自动化测试只在API 28上测试了。近期没有测试过低版本的系统。会尽快修复的。

**Comment by XuchengJie** [comment]
大佬修复的真快，测试低版本已OK
