### ISSUE TITLE
插件中使用AndroidX AppCompatActivity的问题

### ISSUE THREAD

**Issue by onyx-chenhj** [Tencent/Shadow#915]
改动的2个commit:
https://github.com/onyx-chenhj/Shadow/commit/9ab7e79cd8d759596fffb6b4c9586b6745b3c99b
https://github.com/onyx-chenhj/Shadow/commit/1157f72b9c833e410c17926bfdaef076642381d1

插件增加TestFragmentActivityOnCreate，TestAppCompatActivityOnCreate测试
1.
启动TestFragmentActivityOnCreate正常；
启动TestAppCompatActivityOnCreate(super Landroidx/appcompat/app/AppCompatActivity)失败，报You need to use a Theme.AppCompat theme。
在TestAppCompatActivityOnCreate，PluginDefaultProxyActivity配置中加了android:theme="@style/Theme.AppCompat"还是报这个错误。

2.继承Activity的类编译时会更改为.super Lcom/tencent/shadow/core/runtime/ShadowActivity;
继承FragmentActivity，AppCompatActivity的类编译时不会更改父类，这是正常的么

.class public Lcom/tencent/shadow/sample/plugin/app/lib/usecases/activity/TestActivityReCreate;
.super Lcom/tencent/shadow/core/runtime/ShadowActivity;
.source "TestActivityReCreate.java"

.class public Lcom/tencent/shadow/sample/plugin/app/lib/usecases/activity/TestFragmentActivityOnCreate;
.super Landroidx/fragment/app/FragmentActivity;
.source "TestFragmentActivityOnCreate.java"

.class public Lcom/tencent/shadow/sample/plugin/app/lib/usecases/activity/TestAppCompatActivityOnCreate;
.super Landroidx/appcompat/app/AppCompatActivity;
.source "TestAppCompatActivityOnCreate.java"

第1个问题log：
`
   --------- beginning of crash
2022-04-21 20:45:02.918 21556-21556/com.tencent.shadow.sample.host E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.shadow.sample.host:plugin, PID: 21556
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity}: java.lang.RuntimeException: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2933)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3068)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1825)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6797)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(ShadowActivityDelegate.kt:159)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3068) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1825) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6797) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.tencent.shadow.sample.plugin.app.lib.usecases.activity.TestAppCompatActivityOnCreate.onCreate(TestAppCompatActivityOnCreate.java:54)
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(ShadowActivityDelegate.kt:156)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3068) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1825) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6797) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2022-04-21 20:45:02.933 1027-3534/system_process W/ActivityManager:   Force finishing activity com.tencent.shadow.sample.host/com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity
`

**Comment by shifujun** [comment]
我跑起来测试`TestAppCompatActivityOnCreate`是正常的：
<img width="200" alt="image" src="https://user-images.githubusercontent.com/3535204/164636732-8ed8d12d-f50c-4610-a27b-cb05e3430c1a.png">

另外Shadow里原本就有androidx的测试用例的：`com.tencent.shadow.test.cases.plugin_androidx.AppCompatActivityTest`
。

> 2.继承Activity的类编译时会更改为.super Lcom/tencent/shadow/core/runtime/ShadowActivity;
继承FragmentActivity，AppCompatActivity的类编译时不会更改父类，这是正常的么

这是正常的。FragmentActivity虽然是第三方库，但是对于shadow来说，也算是业务自己写的Activity子类而已。对于Shadow来说，androidx的类和你写的类没有区别，不需要特殊处理。所以Shadow只需要把Activity的直接子类的父类改为ShadowActivity。Activity的孙子类因为继承关系也会是ShadowActivity的子类了，这很正常吧？

**Comment by onyx-chenhj** [comment]
感谢回复。

> 这是正常的。FragmentActivity虽然是第三方库，但是对于shadow来说，也算是业务自己写的Activity子类而已。对于Shadow来说，androidx的类和你写的类没有区别，不需要特殊处理。所以Shadow只需要把Activity的直接子类的父类改为ShadowActivity。Activity的孙子类因为继承关系也会是ShadowActivity的子类了，这很正常吧？

明白了，谢谢。

> 我跑起来测试TestAppCompatActivityOnCreate是正常的：

奇怪，刚才在另一台电脑上clone代码重新跑了下，还是报You need to use a Theme.AppCompat theme (or descendant) with this activity.
请问你是直接使用我的commit么，代码上有做调整么（比如宿主预埋的PluginDefaultProxyActivity加Theme.AppCompat）

**Comment by shifujun** [comment]
没有任何改动。我用的是api 28的官方虚拟机。

**Comment by code-czh** [comment]
Android 5.0上：
在宿主的AndroidManifest中为"com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity"添加android:theme="@style/Theme.AppCompat"；

**Comment by shifujun** [comment]
AppCompatActivityTest 确实在API21-25闭区间内都复现该问题。

<img width="1842" alt="image" src="https://user-images.githubusercontent.com/3535204/165239817-3a49cb75-f01c-4636-b432-5a974a0e60ef.png">

**Comment by code-czh** [comment]
@shifujun OPPO手机的 Android 5.x 系统仍然有问题，报相同的错误。

**Comment by shifujun** [comment]
> @shifujun OPPO手机的 Android 5.x 系统仍然有问题，报相同的错误。

如果你能复现调试的话，可以尝试把资源id分区改回0x7f，来判断一下是否只有资源id分区影响了此问题。

**Comment by code-czh** [comment]
> > @shifujun OPPO手机的 Android 5.x 系统仍然有问题，报相同的错误。
> 
> 如果你能复现调试的话，可以尝试把资源id分区改回0x7f，来判断一下是否只有资源id分区影响了此问题。

把插件的资源id分区改回0x7f，还是复现问题，请问还有其他思路吗？
