### ISSUE TITLE
单进程多插件问题

### ISSUE THREAD

**Issue by 235069815** [Tencent/Shadow#927]
写了两个插件demo，分别是plugin1和plugin2，plugin1 和plugin2使用相同的uuid，不同的partkey。loader和runtime也均相同（使用的2.1.1版本）。
在在shadow-2.1.1版本上面进行修改，主要修改点：修改两个插件使用同一个pps。
启动插件1正常，退出插件1页面，然后启动插件2就会崩溃，崩溃信息如下：
com.tencent.shadow.sample.host E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.tencent.shadow.sample.host, PID: 19917
    java.lang.RuntimeException: android.os.DeadObjectException
        at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:126)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: android.os.DeadObjectException
        at android.os.BinderProxy.transact(Native Method)
        at com.tencent.shadow.dynamic.manager.BinderPluginLoader.loadPlugin(BinderPluginLoader.java:46)
        at com.tencent.shadow.sample.manager.FastPluginManager.loadPlugin(FastPluginManager.java:145)
        at com.tencent.shadow.sample.manager.FastPluginManager.convertActivityIntent(FastPluginManager.java:123)
        at com.tencent.shadow.sample.manager.FastPluginManager.startPluginActivity(FastPluginManager.java:116)
        at com.tencent.shadow.sample.manager.SamplePluginManager$1.run(SamplePluginManager.java:124)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 

具体修改点如下：
plugin1:
```
shadow {
    packagePlugin {
      pluginTypes {
		pluginApk1 {
			businessName = 'plugin1'
			partKey = 'plugin1'
			}
		}
	}
}
```

plugin2:
```
shadow {
    packagePlugin {
        pluginTypes {
		pluginApk1 {
			businessName = 'plugin2'
			partKey = 'plugin2'
			}
		}
	}
}
```

修改com.tencent.shadow.sample.host.MainActiviy：
```
        startPluginButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String partKey = (String) partKeySpinner.getSelectedItem();
                Intent intent = new Intent(MainActivity.this, PluginLoadActivity.class);
                intent.putExtra(Constant.KEY_PLUGIN_PART_KEY, partKey);
                switch (partKey) {
                   
                    case Constant.PART_KEY_PLUGIN_MAIN_APP:
                        intent.putExtra(Constant.KEY_PLUGIN_ZIP_PATH, "/sdcard/shadow/plugin1-debug.zip"); // 修改插件包地址
                        intent.putExtra(Constant.KEY_ACTIVITY_CLASSNAME,"com.example.plugin1.MainActivity"); // 修改启动页
                        break;
                    case Constant.PART_KEY_PLUGIN_ANOTHER_APP:
                        intent.putExtra(Constant.KEY_PLUGIN_ZIP_PATH, "/sdcard/shadow/plugin2-debug.zip");// 修改插件包地址
                        intent.putExtra(Constant.KEY_ACTIVITY_CLASSNAME,"com.example.plugin2.MainActivity");// 修改启动页
                        break;

                }
                startActivity(intent);
            }
        });
```

修改com.tencent.shadow.sample.manager.SamplePluginManager：
```
    @Override
    protected String getPluginProcessServiceName(String partKey) {
        return "com.tencent.shadow.sample.host.PluginProcessPPS"; 
    }

```
	
修改获取插件包，改为从bundle获取：
```
private void onStartActivity(final Context context, Bundle bundle, final EnterCallback callback) {
        final String pluginZipPath = bundle.getString(Constant.KEY_PLUGIN_ZIP_PATH);
        final String partKey = bundle.getString(Constant.KEY_PLUGIN_PART_KEY);
        final String className = bundle.getString(Constant.KEY_ACTIVITY_CLASSNAME);
	}
```
	
因为runtime使用的是maven仓库生成的jar，同步需要修改sample-host的manifest.xml，
将
	`android:name="com.tencent.shadow.sample.plugin.runtime.PluginDefaultProxyActivity"`
修改为
`	android:name="com.tencent.shadow.sample.runtime.PluginDefaultProxyActivity"`

请问大佬这个可能是什么原因。

**Comment by shifujun** [comment]
> Caused by: android.os.DeadObjectException
at android.os.BinderProxy.transact(Native Method)

这个异常只能表明跨进程通信时，对面进程已经终止了。

建议先将插件改到和manager相同的进程，sample中就是改到主进程。这样异常的抛出顺序会更加线性，有利于找到最初的异常。

**Comment by 235069815** [comment]
改到主进程后又出现了其他的崩溃，在调试的时候发现uuid_oDex下只有一个dex文件，排查后发现是两个插件包里的apk名字相同导致。
