### ISSUE TITLE
插件添加混淆后文件后，在宿主项目运行报了如下错误，看到之前有人反馈有类似的问题，请问有没有解决方案？

### ISSUE THREAD

**Issue by onenoobinit** [Tencent/Shadow#945]
* What went wrong:
Execution failed for task ':mggkpluginapp:minifyDebugWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.W.a(:87)
	at com.android.tools.r8.R8.a(:28)
	at com.android.tools.r8.R8.run(:3)
	at com.android.builder.dexing.R8Tool.runR8(r8Tool.kt:247)
	at com.android.build.gradle.internal.tasks.R8Task$Companion.shrink(R8Task.kt:472)
	at com.android.build.gradle.internal.tasks.R8Task.doTaskAction(R8Task.kt:334)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:74)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:34)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:91)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:57)
	at jdk.internal.reflect.GeneratedMethodAccessor883.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	... 119 more
Caused by: com.android.tools.r8.utils.b: Error: /Users/wangqiang/Downloads/migu/mggkpluginapp/mggkpluginapp/build/intermediates/transforms/ShadowTransform/debug/122.jar:com/tencent/smtt/sdk/WebView$a.class, Illegal invoke-super to void android.webkit.WebView.computeScroll()

**Comment by shifujun** [comment]
你有测试过用Proguard而不是R8的效果吗？可能也要怀疑一下是不是R8的bug： https://issuetracker.google.com/issues/128987064

看报错的类可能是腾讯的X5内核吧，你可以把你用的版本添加到shadow的sample上，如果能复现，就push上来代码看看。
