### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/shadow/sample/host/lib/LoadPluginCallback;

### ISSUE THREAD

**Issue by withyi9223** [Tencent/Shadow#958]
E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/shadow/sample/host/lib/LoadPluginCallback;
        at com.tencent.shadow.sample.plugin.loader.SamplePluginLoader.loadPlugin(SamplePluginLoader.java:59)
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:86)
        at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:49)
        at android.os.Binder.execTransactInternal(Binder.java:1215)
        at android.os.Binder.execTransact(Binder.java:1179)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.shadow.sample.host.lib.LoadPluginCallback" on path: DexPathList[[zip file "/data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/f2674343238ce46956aedbe035023a59/plugin-debug.zip/sample-loader-debug.apk"],nativeLibraryDirectories=[/system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at com.tencent.shadow.dynamic.apk.ApkClassLoader.loadClass(ApkClassLoader.java:72)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tencent.shadow.sample.plugin.loader.SamplePluginLoader.loadPlugin(SamplePluginLoader.java:59) 
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:86) 
        at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:49) 
        at android.os.Binder.execTransactInternal(Binder.java:1215) 
        at android.os.Binder.execTransact(Binder.java:1179) 
E/AndroidRuntime: FATAL EXCEPTION: Binder:19425_2
    Process: com.tencent.shadow.sample.host:plugin, PID: 19425
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/shadow/sample/host/lib/LoadPluginCallback;
        at com.tencent.shadow.sample.plugin.loader.SamplePluginLoader.loadPlugin(SamplePluginLoader.java:59)
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:86)
        at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:49)
        at android.os.Binder.execTransactInternal(Binder.java:1215)
        at android.os.Binder.execTransact(Binder.java:1179)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.shadow.sample.host.lib.LoadPluginCallback" on path: DexPathList[[zip file "/data/user/0/com.tencent.shadow.sample.host/files/ShadowPluginManager/UnpackedPlugin/test-dynamic-manager/f2674343238ce46956aedbe035023a59/plugin-debug.zip/sample-loader-debug.apk"],nativeLibraryDirectories=[/system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at com.tencent.shadow.dynamic.apk.ApkClassLoader.loadClass(ApkClassLoader.java:72)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tencent.shadow.sample.plugin.loader.SamplePluginLoader.loadPlugin(SamplePluginLoader.java:59) 
        at com.tencent.shadow.dynamic.loader.impl.DynamicPluginLoader.loadPlugin(DynamicPluginLoader.kt:86) 
        at com.tencent.shadow.dynamic.loader.impl.PluginLoaderBinder.onTransact(PluginLoaderBinder.kt:49) 
        at android.os.Binder.execTransactInternal(Binder.java:1215) 
        at android.os.Binder.execTransact(Binder.java:1179)

**Comment by shifujun** [comment]
这个issue的内容只能让人猜到你遇到了问题。但是别人没法给你任何建议。如果你有什么能补充的，为什么不在一开始就写上呢？

最好的反馈问题的方式是把复现问题的代码和操作都提供上，说明预期表现和实际表现。

**Comment by withyi9223** [comment]
> 这个issue的内容只能让人猜到你遇到了问题。但是别人没法给你任何建议。如果你有什么能补充的，为什么不在一开始就写上呢？
> 
> 最好的反馈问题的方式是把复现问题的代码和操作都提供上，说明预期表现和实际表现。
是我自己的问题，已经解决了，谢谢你
