### ISSUE TITLE
请注意每个插件apk构建时都需要apply plugin: 'com.tencent.shadow.plugin'

### ISSUE THREAD

**Issue by androiddong** [Tencent/Shadow#977]
test工程的general-cases run之后的apk复制到宿主none-dynamic的assets目录下，运行报错。apply plugin: 'com.tencent.shadow.plugin' 明明已经配置

2022-06-30 17:13:58.573 17837-17924/com.tencent.shadow.test.hostapp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.tencent.shadow.test.hostapp, PID: 17837
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.RuntimeException: 加载失败
        at com.tencent.shadow.test.none_dynamic.host.HostApplication$1.doInBackground(HostApplication.java:96)
        at com.tencent.shadow.test.none_dynamic.host.HostApplication$1.doInBackground(HostApplication.java:86)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.Error: 请注意每个插件apk构建时都需要apply plugin: 'com.tencent.shadow.plugin'
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:207)
        at com.tencent.shadow.test.none_dynamic.host.HostApplication$1.doInBackground(HostApplication.java:93)
        at com.tencent.shadow.test.none_dynamic.host.HostApplication$1.doInBackground(HostApplication.java:86) 
        at android.os.AsyncTask$3.call(AsyncTask.java:378) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.Error: 请注意每个插件apk构建时都需要apply plugin: 'com.tencent.shadow.plugin'
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildRunningPlugin$1.run(LoadPluginBloc.kt:124)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.Error: 请注意每个插件apk构建时都需要apply plugin: 'com.tencent.shadow.plugin'
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildPackageManager$1.call(LoadPluginBloc.kt:77)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildPackageManager$1.call(LoadPluginBloc.kt:76)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.util.concurrent.ExecutionException: java.lang.Error: 请注意每个插件apk构建时都需要apply plugin: 'com.tencent.shadow.plugin'
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildPluginApplicationInfo$1.call(LoadPluginBloc.kt:66)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildPluginApplicationInfo$1.call(LoadPluginBloc.kt:65)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.lang.Error: 请注意每个插件apk构建时都需要apply plugin: 'com.tencent.shadow.plugin'
        at com.tencent.shadow.core.loader.classloaders.PluginClassLoader.loadPluginManifest$loader(PluginClassLoader.kt:120)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildPluginManifest$1.call(LoadPluginBloc.kt:60)
        at com.tencent.shadow.core.loader.blocs.LoadPluginBloc$loadPlugin$buildPluginManifest$1.call(LoadPluginBloc.kt:58)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2022-06-30 17:13:58.573 17837-17924/com.tencent.shadow.test.hostapp E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.shadow.core.manifest_parser.PluginManifest" on path: DexPathList[[zip file "/data/user/0/com.tencent.shadow.test.hostapp/files/test-plugin-general-cases-normal-release.apk"],nativeLibraryDirectories=[/data/user/0/com.tencent.shadow.test.hostapp/files/test-plugin-general-cases-normal-release.apk_lib, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at com.tencent.shadow.core.loader.classloaders.PluginClassLoader.loadPluginManifest$loader(PluginClassLoader.kt:117)
        	... 6 more
2022-06-30 17:14:12.872 6863-7157/? E/memtrack: Couldn't load memtrack module

**Comment by shifujun** [comment]
你复制的是`normal` flavor的apk，它是用来正常安装运行的。`plugin` flavor的apk是不能正常安装运行的。
