### ISSUE TITLE
非动态方式白名单不生效

### ISSUE THREAD

**Issue by androiddong** [Tencent/Shadow#982]
项目中把部分页面拆分出来作为插件，采用了非动态的方式把插件框架放到宿主中，插件中引用了宿主的module代码，在宿主中配了白名单，但是始终找不到宿主中的类。
==========宿主中配了白名单
    if (mPluginLoader.getPluginParts(partKey) == null) {
            // 插件访问宿主类的白名单
            String[] hostWhiteList = new String[]{
//                    "cn.emagsoftware.gamehall"//测试插件访问宿主白名单类,
            };
            LoadParameters loadParameters = new LoadParameters(null,
                    partKey,
                    null,
                    hostWhiteList);

-----------------报错信息
    java.lang.NoClassDefFoundError: Failed resolution of: Lcn/emagsoftware/gamehall/presenter/gametab/GameTabRankPresenter;
        at com.example.apkplugin.GameRankingActivity.getData(GameRankingActivity.java:71)
        at com.example.apkplugin.GameRankingActivity.onCreate(GameRankingActivity.java:62)
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(Unknown Source:352)
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7894)
        at android.app.Activity.performCreate(Activity.java:7883)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1353)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3655)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3835)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:230)
        at android.app.ActivityThread.main(ActivityThread.java:8024)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "cn.emagsoftware.gamehall.presenter.gametab.GameTabRankPresenter" on path: DexPathList[[zip file "/data/user/0/cn.emagsoftware.gamehall/files/apkplugin-plugin-dev-normal-debug.apk"],nativeLibraryDirectories=[/data/user/0/cn.emagsoftware.gamehall/files/apkplugin-plugin-dev-normal-debug.apk_lib, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at com.tencent.shadow.core.loader.classloaders.PluginClassLoader.loadClass(Unknown Source:80)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.example.apkplugin.GameRankingActivity.getData(GameRankingActivity.java:71) 
        at com.example.apkplugin.GameRankingActivity.onCreate(GameRankingActivity.java:62) 
        at com.tencent.shadow.core.loader.delegates.ShadowActivityDelegate.onCreate(Unknown Source:352) 
        at com.tencent.shadow.core.runtime.container.PluginContainerActivity.onCreate(PluginContainerActivity.java:84) 
        at android.app.Activity.performCreate(Activity.java:7894) 
        at android.app.Activity.performCreate(Activity.java:7883) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1353) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3655) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3835) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:230) 
        at android.app.ActivityThread.main(ActivityThread.java:8024) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
    	Suppressed: java.lang.ClassNotFoundException: cn.emagsoftware.gamehall.presenter.gametab.GameTabRankPresenter
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:1358)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:1418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tencent.shadow.core.loader.classloaders.PluginClassLoader.loadClass(Unknown Source:68)
        		... 20 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by shifujun** [comment]
我也检查了一下sample中测试用例。sample中的none-dynamic宿主忘记打包被依赖的类了（#983），你可以看一下你的场景是不是也忘了。

也可能是宿主的Proguard将这些类删掉或重命名了。

另外这一逻辑与dynamic层没什么关系，不会受是否使用dynamic层影响。

**Comment by androiddong** [comment]
这个引用的module本身是供其它模块使用的，确定是打包了这个依赖。

**Comment by androiddong** [comment]
测试了下，白名单的类必须包含全包名，配置上一级目录就会出现类找不到。这样的话要引用宿主的gametest这个module下的所有类就要配置很多的包名。白名单里配置com.example.gametest这个包名，不能找到gametwo下面的MyGameView。
![image](https://user-images.githubusercontent.com/10593455/171975470-66ed141d-943e-4015-97eb-4f557e83c577.png)

**Comment by androiddong** [comment]
你好，插件中引用了宿主中的sdk,这种方式还是找不到sdk中的类。我在白名单中也配置了sdk的包名

**Comment by shifujun** [comment]
编译时“依赖”是不影响安装包体积的，只有把被依赖的类打包进来才会影响体积。在Gradle配置中，注意`compileOnly`和`implementation`的区别。

和”非动态方式白名单不生效“不相关的问题应该另外提issue。
