### ISSUE TITLE
插件中使用C++库，java.lang.UnsatisfiedLinkError：not accessible for the namespace

### ISSUE THREAD

**Issue by haizhiyun** [Tencent/Shadow#998]
java.lang.UnsatisfiedLinkError: dlopen failed: library "/product/lib64/libc++_shared.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1672)
        at tv.danmaku.ijk.media.player.MediaPlayerSoLoader$1.loadLibrary(MediaPlayerSoLoader.java:33)
        at tv.danmaku.ijk.media.player.MediaPlayerSoLoader.loadIjkLibsOnce(MediaPlayerSoLoader.java:60)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:213)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:257)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:253)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:240)

**Comment by shifujun** [comment]
https://stackoverflow.com/a/60949833/11616914
